- pulp_smash/tests/platform/api_v2/test_user.py
Add comments in response to requests. Test results:
$ python -m unittest2 pulp_smash.tests.platform.api_v2.test_user
...............
Ran 15 tests in 15.437s
OK
> Add comments to API v2 tests for users

- pulp_smash/tests/platform/api_v2/test_repository.py
Expand the `ReadUpdateDeleteSuccessTestCase` in module
`pulp_smash.tests.platform.api_v2.test_repository`. In the test set-up, add HTTP
GET requests that ask for "importers", "distributors" and "details". Add test
methods that inspect Pulp's responses to those requests.
Before and after this commit, 11 and 13 tests run, respectively. Results both
before and after commit:
============  ==================
Pulp Version  Test Suite Results
============  ==================
2.7           OK (skipped=6)
dev (2.8)     OK (skipped=6)
============  ==================
Command used:
PULP_SMASH_CONFIG_FILE=$PS_CONFIG \
python -m unittest2 pulp_smash.tests.platform.api_v2.test_repository
Ported from #44.
> Add several new repository read tests

- pulp_smash/constants.py
- pulp_smash/tests/puppet/api_v2/test_sync_publish.py
- pulp_smash/tests/rpm/api_v2/test_broker.py
- pulp_smash/utils.py
Add a function for resetting pulp in the first commit, and make use of that function to twiddle with the tests in the second commit.
> Reset pulp

- pulp_smash/tests/rpm/api_v2/test_export.py
From a comment in the source code:
> When executing commands over SSH, in a non-login shell, and as a non-root
> user, the PATH environment variable is quite short. For example:
>
>     /usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin
In cases where these conditions hold true, such as when Jenkins logs
into a Nodepool test system, several private functions that work with
`/usr/sbin/getenforce` will malfunction. Make these functions more
resilient by hard-coding in references to `/usr/sbin/getenforce`. This
approach is inflexible and inelegant. However:
> We're doing this it's simple (see _has_getenforce()), because Pulp is
> available on a limited number of platforms, and because we may move to
> an SSH client that allows for shell expansion.
Are there other solutions available? Sure! …
> Fix a partially broken test

- pulp_smash/tests/rpm/api_v2/test_unassociate.py
Do at least the following:
* Rename class `RemoveAssociatedUnits` to `RemoveUnitsTestCase`.
* Update the assertions on `RemoveUnitsTestCase`. Drop the assertion
that checks that a unit randomly selected from a list is present in
the list. Of course it is - that's guaranteed by Python itself.
Refactor the remaining assertions to, hopefully, provide more concise
and useful messages upon test failure.
* Heavily refactor the private methods in the module, and make use of
them as appropriate.
This commit does not introduce any failures. Test results generated
with:
python -m unittest2 pulp_smash.tests.rpm.api_v2.test_unassociate
> Refactor RPM unassociation tests

- README.rst
- docs/index.rst
- docs/installation.rst
- docs/usage.rst
The first commit fixes an outdated link, and the second adds syntax highlighting.
> Make minor updates to docs

- pulp_smash/api.py
Do this with the intent of making the class easier to learn. The
explanation of the ``request_kwargs`` attribute was especially wonky.
> Rewrite docstring for pulp_smash.api.Client

- pulp_smash/tests/rpm/api_v2/test_download_policies.py
Tests executed against both F23 and RHEL6 servers with the following
command:
pulp_smash.tests.rpm.api_v2.test_download_policies.BackgroundTestCase
When targeting F23, no test results change. When targeting RHEL 6, the
entire test case is skipped. This is because:
* Pulp issue 1905 [1] only affects RHEL 6.
* Letting the test run against a RHEL 6 server and skipping only the
failing test methods appears to damage the Pulp services.
[1] https://pulp.plan.io/issues/1905
> Skip tests affected by Pulp issue 1905

- pulp_smash/tests/platform/api_v2/test_search.py
Pulp issue 1332 [1] describes how searches that attempt to restrict
which fields appear in search results produce malformed results. The
tests for this issue have been blocked for longer than appropriate:
`unittest2.skip` decorators were applied to the relevant test cases
before the current `selectors.bug_is_untestable` function (and other
useful functions in that module) was made available.
Tests results are clean. Tests executed with:
python -m unittest2 pulp_smash.tests.platform.api_v2.test_search
[1] https://pulp.plan.io/issues/1332
> Update tests affected by Pulp issue 1332

- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
Fix test case `RedundantPublishSameMetadataTestCase` in module
`pulp_smash.tests.rpm.api_v2.test_sync_publish`. Formerly, this test
case had two errors:
* It failed to include distributor information when creating a
repository.
* It failed to provide a distributor ID when publishing the repository.
These issues went unnoticed because Pulp issue 1724 was causing the test
to be skipped. Test results do not change when run against a Pulp 2.8
server (the test skips), and the test succeeds when run against a Pulp
2.9 server (the test passes). Tests executed with:
pulp_smash.tests.rpm.api_v2.test_sync_publish.RedundantPublishSameMetadataTestCase
> Fix a broken RPM publish test

- pulp_smash/tests/rpm/api_v2/test_export.py
Pulp issue 616 [1] describes how SELinux prevents Pulp from writing to
an export directory. `ExportDistributorTestCase.test_export_to_dir` is
skipped if that bug is open and SELinux is in enforcing mode on the
target system. While this behaviour prevents test failures from
occurring, it's too aggressive: it prevents us from knowing whether
exporting to a directory functions when SELinux is in permissive mode.
Update the test. If the bug is open and SELinux is in enforcing mode on
the target system, then disable SELinux for the duration of that one
test.
[1] https://pulp.plan.io/issues/616
> Partially enable a test affected by Pulp 616

- pulp_smash/tests/rpm/api_v2/test_export.py
The `ExportDistributorTestCase` in module
`pulp_smash.tests.rpm.api_v2.test_export` has three methods:
`setUpClass`, `test_publish_to_web`, and `test_publish_to_dir`. The
first creates and syncs a repository, then adds an export distributor to
the repository. The second and third methods each publish the repository
and verify that the published files can be fetched.
As described by Pulp issue 1928, [1] export distributors cannot be
re-used in this manner. Pulp will silently fail to complete the second
publish. You can prove this to yourself by running the tests with this
command:
python -m unittest2 pulp_smash.tests.rpm.api_v2.test_export.ExportDistributorTestCase.test_publish_to_dir
python -m unittest2 pulp_smash.tests.rpm.api_v2.test_export.ExportDistributorTestCase.test_publish_to_web …
> Fix RPM repo export tests

- pulp_smash/tests/rpm/api_v2/test_export.py
Consider this series of commands:
```sh
d="$(mktemp --directory)"
setfacl -m user:apache:rwx "${d}"  # let apache user rwx in dir
sudo -u apache install -D /dev/null "${d}/foo/bar"
sha256sum "${d}/foo/bar"
```
In this scenario, `${d}/foo/` is owned by apache, which means that the
current user doesn't have permissions necessary to read `${d}/foo/bar`.
A similar issue is encountered by
`ExportDistributorTestCase.test_export_to_dir`. This test creates a
directory on the target Pulp server and asks Pulp to export a repository
to this directory. The "apache" user writes files into this directory,
meaning that the user executing this test may not have permissions
necessary for manipulating the exported files.
Fix this issue.
As an aside, fixing this issue *and* removing the logic related to …
> Fix permissions in directory export tests

- pulp_smash/tests/rpm/api_v2/test_export.py
Pulp issue 1928 only affects Pulp 2.9. Update tests accordingly, so that
a work-around is only applied a Pulp 2.9 system is under test and the
system under test is affected by the bug.
> Correct test for Pulp issue 1928

- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
`PublishTestCase` in module
`pulp_smash.tests.rpm.api_v2.test_sync_publish` creates a pair of
distributors and publishes to them, among other things. One of the tests
in that test case is to fetch the published RPM files and verify their
sanity.
The test should run in its entirety regardless of whether the RPM files
can be fetched. Move these actions into a test method, thus helping to
isolate this action. As a side effect, this slightly simplifies the test
case.
> Refactor an RPM publish test case

- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
This fixes a benign bug introduced by
eb383cd06144dac7f213478b619572140a09d7e1.
> Drop an unused variable

- pulp_smash/tests/rpm/cli/test_copy_units.py
As of Pulp 2.9, it is possible to use the `pulp-admin rpm repo copy
langpacks` command to copy langpacks from one repository to another. Add
a test case for this feature.
Fix: https://github.com/PulpQE/pulp-smash/issues/255
> Ensure langpacks can be copied with CLI

- pulp_smash/tests/rpm/api_v2/test_export.py
Also refactor tests in `pulp_smash.tests.rpm.api_v2.test_export` to use a
mixin to avoid code repetition.
Thanks @ichimonji10 for all the help on making this commit better.
Close #291
> Add export yum repo with specified checksum test

- docs/api/pulp_smash.tests.rpm.cli.utils.rst
- docs/index.rst
- docs/introductory-video.rst
Create a new document, "Introductory Video." Make it the very first page
linked to from the index, before even the installation instructions, and
make it links to the "Pulp Smash Introduction" video on Vimeo.
> Add an introductory video to the documentation

- pulp_smash/tests/rpm/api_v2/test_upload_publish.py
According to Pulp issue 2042, the `updateinfo.xml` file is missing
checksums on Pulp 2.9. Work around this issue. See:
https://pulp.plan.io/issues/2042
> Work around Pulp issue 2042

- tests/test_cli.py
- tests/test_config.py
Pylint version 1.6.1 was just released. Update the code base to satisfy
the new version.
> Make code satisfy updated pylint

- docs/about.rst
Define the meaning of the following labels:
* Issue Type: Bug
* Issue Type: Discussion
* Issue Type: Plan
* Issue Type: Test Case
* Status: LGTM
* Status: Needs Review
* Status: Needs Work
Add this explanation to the documentation at Pulp Smash → About →
Contributing → Labels.
> Explain meaning of issue & pull request labels

- pulp_smash/tests/rpm/cli/test_sync.py
Do at least the following:
* Make the test case docstring reference correct Pulp and Pulp Smash
issues.
* Make the test case docstring correctly describe what the test case
does.
* Greatly simplify the test case implementation. Formerly, the test case
defined `setUpClass` and `tearDownClass` methods, among others,
despite having just one `test*` method and inheriting directly from
`unittest2.TestCase`. Now, the test case has a single `test*` method
and a simple classmethod.
> Refactor ForceSyncTestCase

- pulp_smash/utils.py
The `reset_pulp` function executes `runuser -u apache pulp-manage-db`.
This doesn't work on RHEL 6, because RHEL 6 ships with an old version of
runuser that doesn't support `-u`. Work around this limitation.
For exact details, see runuser(1).
> Make reset_pulp function compatible with RHEL 6

- pulp_smash/tests/rpm/api_v2/test_upload_publish.py
Errata may list one or more checksums for each of the packages they
reference. However, the errata published by pulp list at most one
checksum for each package they reference. As a result, Pulp has to be
smart about which checksum to place in the errata it generates. This
logic is outlined in Pulp issue 2042.
Update the checksum-checking logic in `UploadErratumTestCase`.
See: https://pulp.plan.io/issues/2042
See: https://github.com/PulpQE/pulp-smash/issues/325
> Update tests for erratum checksums

- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
Add a new function, `_get_dists_by_type_id`. It finds information about
all of a repository's distributors, and returns that information as a
dict keyed by distributor type IDs. The dict is in this form:
{'yum_distributor': {…}, 'rpm_rsync_distributor': {…}}
Add a new method, `_RsyncDistUtilsMixin.make_repo`. It creates a
repository with a yum importer, yum distributor and RPM rsync
distributor.
Finally, rename `_MakeUserMixin` to `_RsyncDistUtilsMixin`. This
reflects the fact that the class contains tools for working with RPM
rsync distributors, not just users.
These changes reduce the amount of duplicated logic in the test cases
(`PublishTestCase` and `PublishBeforeYumTestCase`), and should be useful
when writing more test cases.
The RPM rsync distributor test cases were added in …
> Refactor just-added RPM rsync distributor tests

- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
Add a new test case, `VerifyOptionsTestCase`, that test Pulp's
validation of the RPM rsync distributor configuration options. This test
case targets the following issues:
* Pulp issue 2191: The RPM rsync distributor's "predistributor_id"
config option isn't validated
* Pulp issue 2192: The RPM rsync distributor's "root" config option
isn't validated
See:
* https://pulp.plan.io/issues/2191
* https://pulp.plan.io/issues/2192
> Test Pulp's validation of rsync dist. config opts.

- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
Expand `PublishTestCase` in module
`pulp_smash.tests.rpm.api_v2.test_rsync_distributor`. The test now
performs the following steps, where steps 4 and 5 are new:
1. Create a repository with a yum distributor and RPM rsync distributor.
Add content units to the repository.
2. Publish with the yum distributor.
3. Publish with the RPM rsync distributor. Verify that the correct files
are in the target directory.
4. Remove all files from the target directory. Publish again, and verify
that:
* The task for publishing has a result of "skipped."
* No files are placed in the target directory. (This tests Pulp's
fast-forward logic.)
5. Publish with the RPM rsync distributor, with `force_full` set to
true. Verify that files are placed in the target directory. Skip this
step if Pulp issue 2202 [1] is …
> Test the RPM rysnc distrib's fast-forward logic

- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
`PublishBeforeYumDistTestCase` creates an RPM repository with both a yum
distributor and an RPM rsync distributor, and it publishes with the
latter before the former. Currently, the test case asserts that the
publish fails. However, according to Pulp issue 2187, this should result
in the publish skipping. Update the test case accordingly.
See: https://pulp.plan.io/issues/2187
> Update assertion for PublishBeforeYumDistTestCase

- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
Add `DeleteTestCase` to module
`pulp_smash.tests.rpm.api_v2.test_rsync_distributor`. This test case
verifies that the `delete` option has an effect, and it targets Pulp
issue 2221.
See: https://pulp.plan.io/issues/2221
> Add DeleteTestCase for the RPM rsync distributor

- Makefile
- scripts/run_functional_tests.py
This new script can be used like so:
python -m cProfile -o run.prof scripts/run_functional_tests.py
> Add script for profiling test runs

- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
If a sync is performed and matching orphans are on disk, Pulp will
re-use them instead of syncing downloading the content units from a
remote system.
Update the test cases for the RPM rsync distributor. Drop the call to
delete orphans after each test case, and instead delete orphans when the
module has finished executing.
> Use orphans to speed up RPM rsync distrib tests

- pulp_smash/tests/rpm/api_v2/test_crud.py
Check if a distributor can be updated when no checksum_type is provided.
Close #385
> Add RPM distributor testcase

- docs/api.rst
- docs/api/pulp_smash.tests.ostree.api_v2.test_publish.rst
- docs/api/pulp_smash.tests.ostree.api_v2.test_sync.rst
- docs/api/pulp_smash.tests.ostree.api_v2.test_sync_publish.rst
- pulp_smash/tests/ostree/api_v2/test_publish.py
- pulp_smash/tests/ostree/api_v2/test_sync.py
- pulp_smash/tests/ostree/utils.py
The first commit is a simple refactor.
The test added by the second commit is extremely simple. Definitely do check out the linked-to Pulp issues for a sense of why the test is so simple.
> OSTree tests

- pulp_smash/tests/rpm/api_v2/test_crud.py
Check if the checksum_type was actually updated instead for just checking for
raised errors.
> Refactor RPM distributor test_update_checksum_type

- pulp_smash/tests/rpm/api_v2/test_signatures_checked_for_uploads.py
Refactor the fixture handling code in module
`pulp_smash.tests.rpm.api_v2.test_signatures_checked_for_uploads`. Drop
the single `_PACKAGES` global in favor of a pair of globals named
`_SIGNED_PACKAGES` and `_UNSIGNED_PACKAGES`, and move all references to
issue 1806 from the individual test methods into `setUpModule`.
These changes have no functional impact, but they make the code more
legible.
> Refactor fixture handling code

- pulp_smash/tests/rpm/api_v2/test_upload_publish.py
This test case verifies that it's possible to upload an SRPM to a
repository.
See: https://github.com/PulpQE/pulp-smash/issues/402
> Add UploadSrpmTestCase

- pulp_smash/tests/docker/cli/test_sync_publish.py
See: https://pulp.plan.io/issues/2287
> Skip tests affected by Pulp issue 2287

- pulp_smash/tests/docker/cli/test_copy.py
pulp-admin's output has changed when working with Docker tags has
changed. Update tests to properly screen-scrape its current output.
It doesn't seem appropriate to file a bug asking for the changes to be
reverted. Pulp Admin's output is intended to be human-friendly, not
machine parse-able. (Status codes should have been used for this
purpose.) And a close look at pulp-admin's output when copying images,
manifests or tags between repositories shows that there's already subtle
differences between the types of output. The same is true when searching
for images, manifests or tags in existing repositories.
> Update Docker CLI tests

- pulp_smash/tests/python/api_v2/test_duplicate_uploads.py
See: https://pulp.plan.io/issues/2334
> Skip test affected by Pulp issue 2334

- pulp_smash/constants.py
See: https://github.com/PulpQE/pulp-fixtures/pull/41
> Update constant PYTHON_PULP_FEED_URL

- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
See: https://pulp.plan.io/issues/2337
> Skip a test affected by Pulp issue 2337

- pulp_smash/tests/rpm/api_v2/test_repomd.py
See: https://pulp.plan.io/issues/1088
Fix: https://github.com/PulpQE/pulp-smash/issues/425
Thanks to @jortel for help with designing the test.
> Add a test for Pulp issue 1088

- pulp_smash/tests/rpm/api_v2/test_download_policies.py
The tests ensure that Pulp is able to create a repo using one download policy
and then it can be updated to a different one and works as expected for the
updated download policy.
Each test method exercise a different permutation of the download policies.
Tested against pulp-server-2.10.0-1.el7.noarch machine and got the following:
```
py.test -v pulp_smash/tests/rpm/api_v2/test_download_policies.py::SwitchPoliciesTestCase
========================== test session starts ===========================
platform linux -- Python 3.5.2, pytest-3.0.2, py-1.4.31, pluggy-0.3.1 -- /home/elyezer/.virtualenvs/pulp-smash/bin/python3
cachedir: .cache
rootdir: /home/elyezer/code/pulp-smash, inifile: 
collected 6 items 
pulp_smash/tests/rpm/api_v2/test_download_policies.py::SwitchPoliciesTestCase::test_backgr …
```
> Add test to check download policy switching

- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
See:
* https://pulp.plan.io/issues/2199
* http://docs.pulpproject.org/plugins/pulp_rpm/tech-reference/iso-rsync-distributor.html#configuration
> Enable pulp_manage_rsync boolean for rsync tests

- docs/api.rst
- docs/api/pulp_smash.tests.platform.cli.test_selinux.rst
- pulp_smash/tests/platform/cli/test_selinux.py
Add module `pulp_smash.tests.platform.cli.test_selinux`.
Fix: https://github.com/PulpQE/pulp-smash/issues/444
> Test Pulp process labels

- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
SELinux may not be installed on the systems tested by Pulp Smash, and it
seems sensible for Pulp Smash to be able to run even if SELinux is not
installed.
Do not call `semanage` if said executable is not available.
Fix: https://github.com/PulpQE/pulp-smash/issues/451
> Do not call `semanage` if not available

- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
The Pulp rsync publisher transfers files to target systems via SSH. For
whatever reason, those SSH sessions can live on after file transfers
have completed. Several test cases fail because of this: the completed
test cases try to clean up by deleting no-longer-needed users, but the
user deletion requests fail due to dangling SSH sessions.
Fix this by waiting for a short period of time, so that the SSH sessions
can die.
> Wait for user processes to die after publish

- pulp_smash/tests/rpm/api_v2/test_orphan_remove.py
Test whether Pulp reports how many content units are deleted when an
HTTP DELETE call is made to `/pulp/api/v2/content/orphans/`.
See: https://pulp.plan.io/issues/1268
Fix: https://github.com/PulpQE/pulp-smash/issues/459
> Test Pulp reports a count of deleted orphans

- pulp_smash/tests/platform/api_v2/test_login.py
The `pulp_smash.utils.BaseAPITestCase` is fragile when dealing with
cleanup logic, and the addition of `pulp_smash.selectors.skip_if`
greatly reduces the need for such a method. Do not introduce newbies to
the class.
> Drop BaseAPITestCase from test_login

- pulp_smash/tests/platform/api_v2/test_consumer.py
The `pulp_smash.utils.BaseAPITestCase` is fragile when dealing with
cleanup logic, and the addition of `pulp_smash.selectors.skip_if`
greatly reduces the need for such a method. Drop it.
> Drop BaseAPITestCase from test_consumer

- pulp_smash/tests/rpm/api_v2/test_updateinfo.py
Add `CleanUpTestCase` to module
`pulp_smash.tests.rpm.api_v2.test_updateinfo`.
Fix: https://github.com/PulpQE/pulp-smash/issues/480
> Test old updateinfo.xml files are cleaned up

- pulp_smash/tests/rpm/api_v2/test_comps_xml.py
If an existing package group is uploaded to a repository, subsequent
uploads update the existing package group.
See: https://pulp.plan.io/issues/2514
Fix: https://github.com/PulpQE/pulp-smash/issues/477
> Add a test for the .../import_upload/ API call

- pulp_smash/tests/rpm/api_v2/test_unassociate.py
Check if Pulp only associate missing repo content on an already created
RPM repository.
Close #478
> Add selective associate test case

- pulp_smash/tests/rpm/api_v2/test_packages_directory.py
- pulp_smash/tests/rpm/api_v2/test_repository_layout.py
Added two commits:
1. Drop tests that are not relevant anymore since the `packages_directory` option was added and dropped on Pulp 2.9
2. Rename the `test_packages_directory.py` to `test_repository_layout.py` to better describe the module purpose. Also update test case and docstrings to reflect the renaming.
> Update tests for the YUM repository layout

- pulp_smash/tests/rpm/cli/test_sync.py
Do at least the following:
* Make test case clean-up more robust in the face of failure.
* Make assertion failures more informative.
* Eliminate the possibility of string splitting producing a malformed
command.
* Ensure no extraneous content units are present on disk. This ensures
`RemovedContentTestCase` will produce more reliable results.
> Refactor RPM repo syncing tests

- pulp_smash/tests/rpm/api_v2/test_crud.py
Make sure Pulp unquote Feed URLs.
Close #529
> Add FeedURLUnquoteTestCase

- pulp_smash/utils.py
Function `pulp_smash.utils.reset_squid` stops squid, deletes and
recreates its cache, and starts squid. As part of the cache recreation
process, it executes the following command: [1]
squid -z
This works in most cases. However, if all of the following are true...
* The command is executed over SSH.
* The remote system has SELinux enabled.
* Squid version 4 is installed.
...then the command will leave stray files in `/dev/shm/`. These files
will have SELinux contexts set in such a way that Squid is unable to
touch them, and as a result, Squid will be unable to successfully start.
For whatever reason, a solution is to use the `--foreground` flag:
squid -z --foreground
This flag was introduced in Squid 4: [2]
> The squid binary now has a new --foreground command line option which
> prevents …
> Make reset_squid() work with Squid version 4

- docs/api/pulp_smash.tests.docker.api_v2.test_tags.rst
See: 0819b30304f609c7b4682f770c663edf9ef04101
> Add missing page to API docs

- pulp_smash/tests/puppet/cli/test_sync.py
See: https://pulp.plan.io/issues/2574
> Skip tests affected by Pulp issue 2574

- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
Make at least the following changes:
* Ensure the class cleans up after itself in the face of unexpected
errors.
* Make a `skipTest` call conditional, not absolute.
* Make assertion error messages more verbose.
> Refactor SyncInvalidFeedTestCase

- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
Add `ChangeFeedTestCase`. From its docstring:
> The test case procedure is as follows:
>
> 1. Create three repositories — call them A, B and C.
> 2. Populate repository A and B with identical content, and publish
>    them.
> 3. Set C's feed to repository A. Sync and publish repository C.
> 4. Set C's feed to repository B. Sync and publish repository C.
>
> The entire procedure should succeed. This test case targets `Pulp
> #1922 <https://pulp.plan.io/issues/1922>`_.
Fix: https://github.com/PulpQE/pulp-smash/issues/528
> Test a repository's feed can be changed

- pulp_smash/tests/python/api_v2/test_sync_publish.py
Version 2 of the pulp_python plugin will add support for dealing with
python wheels, and most of the necessary work is already done. As a
result, certain issues on Pulp's issue tracker are marked as MODIFIED,
and several of Pulp Smash's selectors designed to skip tests were not
producing test skips. Fix this.
> Skip certain Python tests

- pulp_smash/cli.py
When managing SYSV services from Jenkins services and related files gets
the `unconfined_java_t` label. That is because SYSV does not deal great
with the labels as systemd. In order to get better results, on RHEL6,
when running on Jenkins disable SELinux temporarily when restarting the
services for pulp_reset.
> Disable SELinux when managing services on Jenkins

- pulp_smash/tests/docker/cli/test_sync_publish.py
Method `SyncPublishV2TestCase.setUpClass` does quite a bit of work,
including creating and syncing a repository and fetching some additional
information about the repository. This design has two weaknesses:
* If the repository sync fails, it doesn't make sense to continue on and
get additional information about the repository. The test should stop.
* If the repository creation or sync fails, no clean-up work will occur.
Fix these issues. This is an issue that was encountered in the real
world during troubleshooting.
> Make test more robust in the face of failures

- pulp_smash/tests/rpm/api_v2/test_updateinfo.py
Historically, Pulp has always published errata in an RPM repository,
regardless of whether those errata reference any packages, and
regardless of whether referenced packages exist in the same published
RPM repository.
The current development versions of Pulp 2.12 and 2.13 change how errata
are handled. Now, an errata is only included in a published RPM
repository if it references a package, and if that package is present in
the same published repository.
Update `UpdateInfoTestCase`, so that it observes this new behaviour.
See: https://pulp.plan.io/issues/2559
> Fix some broken errata tests

- pulp_smash/tests/rpm/api_v2/test_updateinfo.py
Class `ErratumPkgListCountTestCase` does the following:
1. Create and sync an RPM repository with a feed and distributor.
2. Unassociate the "gorilla" package from the repository.
3. Publish the repository.
It then verifies that the published repository's `updateinfo.xml` file
is valid. Unfortunately, this test recently broke, primarily because of
the changes implemented for Pulp issue 2559: errata are omitted if they
don't reference any packages, or if they reference packages not in the
currently published repository. In this case, an erratum that references
the "gorilla" erratum is now being omitted, which broke the test.
Update the test case:
* Make the test case comply with the changes outlined in Pulp issue
2559.
* Make the test clean up after itself even when an error occurs during …
> Rewrite test that updates updateinfo.xml

- pulp_smash/constants.py
See: 1f9ef98d105f97cca20e2fa47dc9b3ce17bfa8ee
> Fix a broken constant

- pulp_smash/tests/puppet/api_v2/test_sync_publish.py
If a Puppet repository without a feed is synced, the sync should fail in
a graceful way. Add a test to verify that this is so.
See: https://pulp.plan.io/issues/2628
Fix: https://github.com/PulpQE/pulp-smash/issues/583
> Add test case to sync Puppet repo w/out a feed

- pulp_smash/tests/puppet/api_v2/test_install_distributor.py
The first commit refactors the test case in some minor ways. The second fixes the assertion made at the end of the test case.
See: b3d228fe8932e3253205c014f66271ab5e7d002e
> Update new Puppet test case

- pulp_smash/tests/docker/cli/test_copy.py
The output produced by ``pulp-admin docker repo copy`` changes in Pulp
2.13. Rather than listing the checksum of every copied unit, the total
number of copied units is listed. Update `CopyAllManifestsTestCase` so
that it can deal with both types of output.
> Make CLI test correctly parse stdout

- pulp_smash/tests/python/api_v2/test_sync_publish.py
See: https://pulp.plan.io/issues/140
See: https://github.com/PulpQE/pulp-smash/issues/493
> Expand docstring for Pulp issue 140

- docs/api.rst
- docs/api/pulp_smash.tests.platform.cli.test_pulp_manage_db.rst
- pulp_smash/tests/platform/cli/test_pulp_manage_db.py
Some of the tests may be skipped due to:
* https://pulp.plan.io/issues/2186
* https://pulp.plan.io/issues/2684
Fix: https://github.com/PulpQE/pulp-smash/issues/487
> Add tests for conditional pulp-manage-db execution

- pulp_smash/tests/rpm/api_v2/test_crud.py
The tests ensure the last_unit_added field is updated when syncing a
repository and when copying units from on repository to the another.
Close #550
> Add tests for last_unit_added update

- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
See: https://pulp.plan.io/issues/1376
> Maybe skip test affected by Pulp issue 1376

- pulp_smash/tests/rpm/api_v2/test_crud.py
Do at least the following:
* Add an assertion to method `test_update_on_copy`. Assert that the
`last_unit_added` repository attribute is non-null immediately after a
content unit is associated with a repository.
* Move assertions in `test_update_on_copy` into `subTest` context
managers.
* Fiddle with docstrings, comments, and variable names.
> Refactor test case for last_unit_added repo attr

- pulp_smash/api.py
- pulp_smash/cli.py
- pulp_smash/exceptions.py
- pulp_smash/selectors.py
- pulp_smash/tests/puppet/cli/test_sync.py
- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
- pulp_smash/tests/rpm/api_v2/test_signatures_checked_for_copies.py
- pulp_smash/tests/rpm/api_v2/test_signatures_saved_for_packages.py
- pulp_smash/tests/rpm/cli/utils.py
See: https://docs.pylint.org/en/latest/whatsnew/1.7.html
> Make code comply with Pylint 1.7.0

- pulp_smash/cli.py
- pulp_smash/config.py
Also, tweak some of the surrounding prose.
> Fix errors in code examples

- pulp_smash/config.py
- pulp_smash/exceptions.py
- tests/test_config.py
Validate Pulp Smash configuration file and ensure only expected values
and roles are present.
> Add config validation

- pulp_smash/tests/ostree/api_v2/test_crud.py
An OSTree distributor may have a `relative_path` defined. Relative paths
must be globally unique within a Pulp installation. The following test
cases verify that this is so:
* `CreateDistributorsTestCase`
* `UpdateDistributorsTestCase`
Refactor the test cases so that clean-up is more deterministic, and so
that test failures are easier to diagnose.
Also, skip tests affected by Pulp issue 2769.
See: https://pulp.plan.io/issues/2769
> Refactor OSTree distributor test cases

- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
Expand `PublishBeforeYumDistTestCase` so that, when executed, it will do
the following:
1. Create a repository with a yum distributor and rsync distributor.
2. Publish with the rpm rsync distributor. Verify that:
* The publish has a result of "skipped."
* No files are placed on the remote system.
3. Publish with the rpm rsync distributor again. Perform the same
verification steps.
Step 3 is new.
Fix: https://github.com/PulpQE/pulp-smash/issues/637
See: https://pulp.plan.io/issues/2722
> Test publishing an RPM rsync distributor twice

- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
Add `PublishTwiceTestCase` to module
`pulp_smash.tests.rpm.api_v2.test_rsync_distributor`. From its
docstring:
Do the following when executed:
1. Create a yum repository with a yum and rsync distributor.
2. Add some content to the repository.
3. Publish with the yum and rsync distributor.
4. Publish with the yum and rsync distributor again.
The second publish with the rsync distributor should be a
fast-forward publish, as no new units were added to the repository
between the first and second publishes. Verify that the first rsync
publish is not a fast-foward publish and that the second one is.
Fix: https://github.com/PulpQE/pulp-smash/issues/615
See: https://pulp.plan.io/issues/2666
> Add test case for multiple RPM rsync publishes

- pulp_smash/config.py
Make sure the expected properties on root and system are present.
> Update config schema

- pulp_smash/tests/docker/cli/test_sync_publish.py
Several Docker CLI tests issue HTTP GET requests to:
* /crane/repositories
* /crane/repositories/v1
* /crane/repositories/v2
The tests issue these requests to verify that synced and published
repositories contain appropriate. However, according to Pulp issue 2723,
`/crane/repositories/v2` returns incorrect messages, and the fix is
different than originally anticipated by the test. Update the tests that
fetch these paths. See: https://pulp.plan.io/issues/2723
Several tests get `/crane/repositories` when they should be getting
`/crane/repositories/v2`. Fix those paths.
`SyncPublishV1TestCase` inappropriately deletes the repository it
creates. Fix the clean up procedure.
> Fix issues with docker sync publish tests

- pulp_smash/tests/rpm/api_v2/test_iso_sync_publish.py
Make `UploadIsoTestCase` do the following:
1. Create an ISO repository.
2. Upload :data:`pulp_smash.constants.FILE_URL` to the repository.
3. Publish the repository.
4. Download the published ISO, and assert it's equal to the uploaded
ISO.
Steps 3 and 4 are new.
See: 1e3c9f1affdaf9280e4474f6b7491efdb30b5358
> Flesh out UploadIsoTestCase

- pulp_smash/tests/rpm/api_v2/test_retain_old_count.py
Make the test shorter and more robust in the face of unexpected
failures.
> Refactor API test for retain_old_count sync option

- pulp_smash/tests/rpm/cli/test_retain_old_count.py
The CLI test case for the `retain_old_count` feature already ensures
that the flag works correctly when set to zero. However, it doesn't
ensure that the flag works for values greater than zero. Fix this
omission.
Fix: https://github.com/PulpQE/pulp-smash/issues/662
See: https://pulp.plan.io/issues/2785
> Expand CLI test case for `retain_old_count`

- setup.py
Pulp Smash works with Python 3.6.
> Update classifier in setup.py

- docs/about.rst
I also added a sentence to elaborate on uses of Issue Type: Plan.
> add Pulp Version: 3 label description 

- pulp_smash/tests/docker/api_v2/test_sync_publish.py
The following test cases in module
`pulp_smash.tests.docker.api_v2.test_sync_publish` have (nearly)
identical set-up procedures, and differ primarily in the assertions that
are performed:
* `ManifestListTestCase`
* `V2RegistryTestCase`
Consolidate the two test cases into one.
> Consolidate two Docker test cases into one

- pulp_smash/tests/docker/api_v2/test_sync_publish.py
Add a new Docker test case, `NoAmd64LinuxTestCase`. From its docstring:
> A manifest list lets a single Docker repository contain multiple
> images.  This is useful in the case where an image contains
> platform-specific code, and an image must be built for each each
> supported architecture, OS, etc.
>
> When a modern Docker client fetches an image, it does the following:
>
> 1. Get a manifest list.
> 2. Look through the list of available images.
> 3. Pick out an image that functions on the current host's platform.
> 4. Get a manifest for that image.
> 5. Use the information in the manifest to get the image layers.
>
> Older Docker clients aren't aware of manifest lists, and when they go
> to fetch an image, they just ask for any old manifest from a
> repository. When a Docker registry …
> Test fetching an image w/out an amd64/linux build

- pulp_smash/tests/rpm/api_v2/test_upload_publish.py
Remove assertion related to HTTP status code, change parent class to be unittest.TestCase, and add self.addCleanup.
Closes: #709
> Refactor of UploadDRPMTestCase class

- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
* Problem: It is possible to trigger the sync of repo with an invalid feed URL,
ater read the task, the error report fields were empty.
* Test:
1. Create, and sync a repository using an invalid feed URL.
2. Read the related task.
3. Assert that error report is according to error cause.
Closes: #525
> Test whether error report is according to error cause.

- pulp_smash/tests/rpm/api_v2/test_crud.py
- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
Atemmpt to perform the following actions over a non-existent
repository: Sync, Publish, Update and Delete.
In all these actions is expected an exception to be raised. HTTP 4XX.
These actions are testing the failures scenarios mentioned in the
issue #157.
Closes: #157
> Test actions over a non-existent repository using API.

- pulp_smash/tests/rpm/api_v2/test_unassociate.py
* Refactor of class `RemoveUnitsTestCase` to be more generic, create a
`do_test` method, and add tests related to DRPM and SRPM.
See: #115
> Add tests for DRPM and SRPM class RemoveUnitsTestCase.

- docs/api.rst
- docs/api/pulp_smash.tests.pulp3.pulpcore.api_v3.test_crud_users.rst
- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crud_users.py
Add CRUD user tests for `Pulp3`.
See: #748
> Add CRUD users tests.

- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crud_users.py
* Assert that user passwords are never returned when searching for users
or getting info about a particular user. Formerly, the tests simply
ignored passwords.
* Add a test that searches for users.
* Fix a method name in `UsersCRUDTestCase`.
See: https://github.com/PulpQE/pulp-smash/issues/748
> Expand user CRUD tests

- pulp_smash/tests/pulp2/rpm/cli/test_process_recycling.py
The test case in `pulp_smash.tests.pulp2.rpm.cli.test_process_recycling`
sets and unsets `PULP_MAX_TASKS_PER_CHILD` in
`/etc/default/pulp_workers`, and verifies that Pulp respects this option
when starting up. Unfortunately, this test case frequently fails on
Fedora 26, during step four. It's unclear why this test fails, and even
worse, the failure is a heisenbug.
Refactor this module:
* Expand the debugging messages in the assertions. This should make it
easier to understand whether or not the test failures are significant,
or if they're insignificant, such as due to a dying process living too
long.
* Deduplicate clean-up logic in the test case, and make clean-up more
robust in the case of unexpected failures.
* Drop a function for restarting services, in favor of function …
> Refactor tests for process recycling

- pulp_smash/utils.py
Fix a minor description in a docstring.
> Fix minor description docstring.

- docs/about.rst
Add more non mandatory items to existing Code Standards.
In order to make clear in the documentation what expect from a
contributor, add few more details about code standard.
> Add more items to guidelines Code Standards.

- pulp_smash/tests/pulp2/ostree/api_v2/test_crud.py
Add tests to verify if the importer of ostree can be updated using HTTP
PUT.
1. Create and sync a repository.
2. Update the `importer` associated with the repository.
3. Perform assertions about the just updated `importer`.
Closes: #839
> Test if importer config of ostree can be updated.

- pulp_smash/tests/pulp3/file/api_v3/test_sync.py
1. Create a repository, and an importer.
2. Sync the repository an arbitrary number of times.
3. Verify that the repository version is equal to the previous number
of syncs.
This test explores the design choice described [Sync of an unchanged
importer changes repository version](https://pulp.plan.io/issues/3308)
> Verify whether sync update repository version. 

- pulp_smash/tests/pulp2/puppet/api_v2/test_install_distributor.py
This fixes errors introduced by:
5dfcc7ec983bf4b010bc88d5edb5bb7dc53b933d
> Add missing commas

- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crud_users.py
Expand user test cases. Add an extra test to filter user by its
username.
See: https://pulp.plan.io/issues/3142
Closes: #748
> Add test to filter user by its username.

- docs/api.rst
- docs/api/pulp_smash.tests.pulp3.file.api_v3.test_publications.rst
- pulp_smash/tests/pulp3/constants.py
- pulp_smash/tests/pulp3/file/api_v3/test_publications.py
Add basic tests to perform actions over publications.
Closes: #861
> Add tests to publications.

- pulp_smash/tests/pulp3/pulpcore/utils.py
Function `gen_distribution()` which is part of `pulpcore/utils` was
updated. It was appended '/' to the generated `base_path` of the
`gen_distribution`.
> Modify function gen_distribution for Pulp3.

- setup.py
We use Pulp Smash in production, all the time. Let's classify it as
such.
> Classify Pulp Smash as production-ready

- pulp_smash/tests/pulp3/file/api_v3/test_download_content.py
- pulp_smash/tests/pulp3/file/api_v3/test_unlinking_repo.py
- pulp_smash/tests/pulp3/utils.py
Updating content fields based on changes in:
https://github.com/pulp/pulp_file/pull/51
> Update content fields

- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crud_users.py
Remove `from random import choice` from test_crud_users.
Make linter happy.
> Remove imported but unused module.

- pulp_smash/tests/pulp3/pulpcore/api_v3/test_status.py
Requires PR: https://github.com/pulp/pulp/pull/3406
> Changes to status API

- pulp_smash/tests/pulp3/pulpcore/api_v3/test_status.py
> Revert "Changes to status API"

- pulp_smash/tests/pulp3/file/api_v3/utils.py
auto_publish was removed from the MVP
re: #3545
https://pulp.plan.io/issues/3545
> Remove auto_publish field from publisher

- pulp_smash/tests/pulp3/file/api_v3/test_crd_publications.py
- pulp_smash/tests/pulp3/file/api_v3/test_crud_content_unit.py
- pulp_smash/tests/pulp3/file/api_v3/test_crud_remotes.py
- pulp_smash/tests/pulp3/file/api_v3/test_download_content.py
- pulp_smash/tests/pulp3/file/api_v3/test_publish.py
- pulp_smash/tests/pulp3/file/api_v3/test_repo_version.py
- pulp_smash/tests/pulp3/file/api_v3/test_sync.py
- pulp_smash/tests/pulp3/file/api_v3/test_unlinking_repo.py
Requires PR: https://github.com/pulp/pulp/pull/3423
Requires PR: https://github.com/pulp/pulp_file/pull/64
re: #3543
https://pulp.plan.io/issues/3543
> Rename Remote.feed_url to Remote.url

- pulp_smash/constants.py
- pulp_smash/tests/pulp3/file/api_v3/test_repo_version.py
- pulp_smash/tests/pulp3/utils.py
Add 2 test cases.
First:
1. Delete a version (e.g. 1) and verify doesn't affect the content of successive versions (e.g. 2, 3, ...).
2. Assert that the last version can be deleted.
3. Verify whether when the last version is deleted and then a new version is created, it should not have the previously deleted version content.
Second:
1. Test if delete a given repo version will delete its publication.
Closes:#871
> Add tests to delete any repo version.

- docs/api.rst
- docs/api/pulp_smash.tests.pulp3.pulpcore.api_v3.test_api_docs.rst
- pulp_smash/tests/pulp3/constants.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/test_api_docs.py
Add basic test coverage to the API auto generated docs.
Verify whether the API auto generated docs are available.
Closes:#893
> Add tests to auto generated docs.

- pulp_smash/tests/pulp3/file/api_v3/test_crd_publications.py
Add two extra test cases:
* Read a publication using its created time.
* Read a publication using its distribution.
These tests were created using the MVP, and the auto generated API
documentation as technical reference.
See:#861
> Expand CRUD tests for publications.

- pulp_smash/tests/pulp3/file/api_v3/test_repo_version.py
Test whether content present in a repo version is immutable.
1. Create a repository that has at least one repository version.
2. Attempt to update the content of a repository version.
3. Assert that an HTTP exception is raised.
4. Assert that the repository version was not updated.
Closes:#953
> Verify content immutability for repo version.

- pulp_smash/tests/pulp3/pulpcore/api_v3/test_workers.py
Update variable in the ``test_03_positive_filters``. Use
``last_heartbeat__gte`` instead of ``last_update__gte``.
Besides that, remove assertions related to ``last_heartbeat`` once this
parameter can be udpated between the query and assertion moment.
> Update assertions and variable name for workers.

- pulp_smash/tests/pulp3/pulpcore/api_v3/test_workers.py
>Filtering workers is indetermanistic
See: https://pulp.plan.io/issues/3586
> Skip test affected by Pulp issue 3586

- pulp_smash/tests/pulp3/constants.py
See: 7c034270ed381ebf8b227642c7fce29b3da3cc85
> Drop unused constants

- docs/usage.rst
Rewrite `docs/usage.rst` for readability purposes.
> Wordsmith the Pulp Smash usage documentation

- pulp_smash/tests/pulp3/constants.py
Per https://pulp.plan.io/issues/3601.
> Updating file content path

- pulp_smash/tests/pulp3/file/api_v3/test_auto_distribution.py
Perform a series of assertions about the mandatory parameters,
`publisher` and `repository` related to the auto distribution feature.
* Attempt to create a distribution with repository but no publisher.
* Create a distribution with repository and publisher.
* Update the distribution`s repository to None. Assert that an HTTP
exception is raised.
* Update the distribution`s publisher to None. Assert that an HTTP
expeption is raised.
* Update distribution`s publisher and repository to None at same time.
* Publish the repository. Assert that distribution does not point to
the new publication.
Closes:#883,#917
> Test the set up of mandatory parameters auto distribution.

- pulp_smash/tests/pulp3/file/api_v3/test_auto_distribution.py
Move repeated logic from the main test method into functions.
> Refactor SetupAutoDistributionTestCase

- pulp_smash/tests/pulp2/puppet/api_v2/test_sync_publish.py
See: https://pulp.plan.io/issues/3692
> Skip test affected by Pulp issue 3692

- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crud_distributions.py
Add tests to ensure that `base_path` on distributions are validated.
Assert that `base_path` should be unique, without spaces, and should not
begin or end with slashes.
Closes:#906
> Ensure that base_path on distributions are validated.

- pulp_smash/tests/pulp3/pulpcore/api_v3/test_workers.py
Sort importers for `pulp3/pulpcore/api_v3/test_workers.py`.
> Sort importers.

- pulp_smash/tests/pulp2/platform/utils.py
Fix broken link on the documentation. Add link to
`pulp_smash.config.PulpSmashConfig` on function `require_selinux`.
> Fix broken link documentation.

- pulp_smash/pulp2/utils.py
- pulp_smash/tests/pulp2/docker/utils.py
- pulp_smash/tests/pulp2/ostree/utils.py
- pulp_smash/tests/pulp2/platform/utils.py
- pulp_smash/tests/pulp2/puppet/utils.py
- pulp_smash/tests/pulp2/python/utils.py
- pulp_smash/tests/pulp2/rpm/utils.py
See: https://pulp.plan.io/issues/3687
> Skip tests affected by Pulp issue 3687

- pulp_smash/cli.py
- pulp_smash/pulp2/utils.py
- pulp_smash/tests/pulp2/docker/utils.py
- pulp_smash/tests/pulp2/platform/cli/test_pulp_manage_db.py
- pulp_smash/tests/pulp2/platform/cli/test_selinux.py
- pulp_smash/tests/pulp2/puppet/api_v2/test_install_distributor.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_content_sources.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_copy.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_crud.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_download_policies.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_errata.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_export.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_iso_sync_publish.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_republish.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_rsync_distributor.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_service_resiliency.py
- pulp_smash/tests/pulp2/rpm/api_v2/utils.py
- pulp_smash/tests/pulp2/rpm/cli/test_copy_units.py
- pulp_smash/tests/pulp2/rpm/cli/test_process_recycling.py
- pulp_smash/tests/pulp2/rpm/cli/test_sync.py
- pulp_smash/tests/pulp2/rpm/utils.py
- pulp_smash/tests/pulp3/file/api_v3/test_orphans.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crd_artifacts.py
- pulp_smash/utils.py
- tests/test_cli.py
- tests/test_utils.py
Fix: https://github.com/PulpQE/pulp-smash/issues/1036
> Move is_root to pulp_smash.cli

- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crud_distributions.py
Test overlapping of `base_path` when creating distributions.
Asssuming that a  distributions `base_path` is `foo/bar`. Assert that
this `base_path` or part of it can not be used as a new `base_path` for
a different distribution. No overlapping.
Closes:#956
> Add test for overlapping `base_path`.

- pulp_smash/api.py
* Let the `poll_spawned_tasks` function use a `pulp_smash.api.Client`
object when polling Pulp's API, rather than directly using the
underlying Requests library. This makes polling code more concise, and
it makes some other simplifications possible.
* Don't set a default value for the `pulp_host` parameter. If a user
passes no value for this parameter, just pass the `None` through to
`pulp_smash.api.Client`, which will provide a default value if needed.
In short: this change makes the logic for providing a default value
for `pulp_host` more DRY.
> Overhaul task polling functions

- pulp_smash/api.py
- tests/test_api.py
This response handler is similar to `json_handler`, but:
* It is only compatible with Pulp 3.
* If it detects that the response is a page, it will walk through all
pages of results, collect the results into a single list, and return
that list.
> Add new API response handler called page_handler

- pulp_smash/constants.py
A new fixture was added. Add a constant to this new fixture.
Currently the number of files on this fixture is equal to 250.
See:https://github.com/PulpQE/pulp-fixtures/pull/81
> Add new constant to fixture file-many.

- pulp_smash/tests/pulp3/file/api_v3/test_pagination.py
The `PaginationTestCase` verifies that Pulp properly pages results. For
example, if a client GETs the list of repositories and there are more
than 100 results, then Pulp will return only 100 results, plus a link to
the next page of results. There's also a "previous" link. Pulp Smash
assumes that each page will contain 100 elements. This assumption was
valid until today, when the `page_size` parameter was introduced.
Make Pulp Smash take advantage of this parameter, by requesting
relatively small `page_size`. This lets test cases be much faster. This
is of critical importance to the Pulp 3 development team, which runs
tests on Travis hosts, which may have limited CPU resources.
Unfortunately, this change does reduce test coverage. Pagination is
still tested for the following use cases:
* …
> Make PaginationTestCase use small pages

- Makefile
- docs/Makefile
- docs/conf.py
The current version of Sphinx allows one to make use of an extremely
short make file. Take advantage of this capability.
> Dramatically shorten docs/Makefile

- setup.py
See: 37b1a41d2b4e274cca7c6b44dec955139aba0f7b
> Drop unused dependency: python-dateutil

- docs/changelog.rst
- docs/index.rst
Fix: https://github.com/PulpQE/pulp-smash/issues/1126
> Add a changelog

- pulp_smash/cli.py
- pulp_smash/pulp2/utils.py
- Implemented a cache on `cli.Client` to store `is_superuser` state and avoid calling it again if the same client is re-used.
- Used `sudo=True` on all `run` calls that demands sudo
> Refactor to use `sudo=True` argument on cli module

- Makefile
Remove just added install-dev from make all
> Remove install-dev from make all

- .github/ISSUE_TEMPLATE.md
- docs/about.rst
Add section about the proper location to create issues related to specific Pulp
versions.
Moreover, update the ISSUE_TEMPLATE to reflect the proper place to create
issues.
> Update documentation section creating issues

- pulp_smash/api.py
re #3978
https://pulp.plan.io/issues/3978
> Update api.py due to changes in core

- pulp_smash/cli.py
Demanded by pulp/pulp#3720 to check whether a pulp worker is running on systemd.
example:
```py
if not ServiceManager(...).is_active(['pulp_worker@*']):
raise unittest.SkipTest('Requires pulp workers running on systemd')
```
It is using the return code by `service status` or `systemctl is-active`
if != 0 then the methods returns False.
> Add ServiceManager.is_active to check if a worker is active.

- pulp_smash/pulp3/constants.py
Add a new constant to Pulp 3 namespace.
`MEDIA_PATH = /var/lib/pulp`
> Add a new constant - MEDIA_PATH to Pulp 3 namespace

- pulp_smash/pulp3/utils.py
- tests/test_pulp3_utils.py
Notes is being removed until we can better evaluate the design.
> Remove 'notes' field from gen_repo()

- pulp_smash/pulp3/constants.py
https://pulp.plan.io/issues/4243
re #4243
> Add download policies constant

- pulp_smash/pulp3/constants.py
Update the constant `DOWNLOAD_POLICIES` to be a tuple.
See: https://github.com/PulpQE/pulp-smash/issues/1157
> Update Pulp 3 constant to be a tuple

- pulp_smash/pulp3/utils.py
Reverts PulpQE/pulp-smash#1154
> Revert "API Changes"

- pulp_smash/pulp3/utils.py
The name of this field is changing in core
> Change name of 'artifacts' field to '_artifacts'

- pulp_smash/pulp3/utils.py
https://github.com/pulp/pulp_file/pull/169/files#r256499995
> Add `download_content_unit` helper function for Pulp 3

- pulp_smash/pulp3/constants.py
certguard plugin has a new endpoint
> Fix certguard endpoint

- pulp_smash/api.py
Update docs to add task_handler.
Also remove some pylints comments.
> Update documentation about task_handler

- pulp_smash/pulp3/constants.py
ref #4678
https://pulp.plan.io/issues/4678
> Publications are now typed in the API

- pulp_smash/pulp3/constants.py
Add consntant related to uploads endpoint for Pulp 3.
See: https://pulp.plan.io/issues/4196
> Add constant related to uploads for Pulp 3

- pulp_smash/pulp3/constants.py
ref #4785
https://pulp.plan.io/issues/4785
> Pulp 3 "distributions" endpoint is master/detail now

- docs/about.rst
Update docs about the usage of pre-commit hooks. How to install Pulp
Smash in dev mode.
> Update docs about dev mode

- pulp_smash/api.py
- pulp_smash/pulp3/utils.py
- tests/test_pulp3_utils.py
ref #5457
https://pulp.plan.io/issues/5457
> Renaming _href to pulp_href for pulp3

- pulp_smash/pulp3/utils.py
_versions_href to pulp_versions_href
_latest_version_href to pulp_latest_version_href
ref #5548
https://pulp.plan.io/issues/5548
Required PR: https://github.com/pulp/pulpcore/pull/329
> Renaming RepositoryVersion fields

- .gitignore
- pulp_smash/pulp3/constants.py
- pulp_smash/pulp3/utils.py
- tests/test_pulp3_utils.py
re: #5625
https://pulp.plan.io/issues/5625
> Modifications for typed repositories

- pulp_smash/config.py
https://pulp.plan.io/issues/5873
ref #5873
> Option for local fixture

- COPYRIGHT
- LICENSE
- setup.py
> Add Copyright and License like all pulp repos

- README.rst
- docs/index.rst
*   Sync up the two documentation landing pages.
*   Fix a syntax error in the "Pulp" link.
> Sync and fix docs landing pages

- pulp_smash/config.py
- setup.py
https://pulp.plan.io/issues/6339
ref #6339
> Generate bindings config

- pulp_smash/cli.py
fixes #6409
https://pulp.plan.io/issues/6409
> Add cli transport for podman

- pulp_smash/cli.py
> Add push and tag to RegistryClient

- pulp_smash/constants.py
> Changing fixtures to new URL

- pulp_smash/api.py
- pulp_smash/pulp3/bindings.py
Addressing: https://github.com/pulp/pulp_rpm/pull/1722#pullrequestreview-422964847
> Moving bindings utils from plugins to pulp-smash

- pulp_smash/cli.py
- pulp_smash/utils.py
- tests/test_cli.py
- tests/test_pulp_smash_cli.py
> Adds utils.get_pulp_setting() for retrieving pulp 3 settings

- pulp_smash/utils.py
> Use json to retrieve pulp settings

- pulp_smash/utils.py
Handle sets pulp settings in get_pulp_settings function.
> Handle sets in get_pulp_settings

- pulp_smash/pulp3/bindings.py
There are a lot of use cases for needing parts of the task output that
are not created resources. It's easy enough to get the created
resources if you do want them that we should just return the raw task
output.
[noissue]
> Change the output of the monitor_task utility

- pulp_smash/utils.py
This adds execute_pulpcore_python to utils as a wrapper around
`pulpcore-manager shell -c`.
> Add ability to run python code in pulpcore env

- pulp_smash/cli.py
> Remove 'sudo' from commands that are run inside containers

- setup.py
> Pin 'click' to <8.0.0 due to compatibility issues.

- setup.py
> Move to latest-click-release (~=8.0.1).

- pulp_smash/pulp3/utils.py
In some cases we need not just the contnet, but the entire response
object.
[noissue]
> Adds unit fetch that returns entire response obj

- pulp_smash/pulp3/bindings.py
> Adjust orphan cleanup call given recent changes in pulpcore 3.15.

- setup.py
> Add aiohttp dep

- pulp_smash/pulp3/pytest_plugin/__init__.py
> Make pulp-smash compatible with python 3.6

- pulp_smash/pulp3/pytest_plugin/__init__.py
> Add serial and parallel marks for pytest

- pulp_smash/pulp3/pytest_plugin/__init__.py
- setup.py
> Adds proxy.py fixtures

- pulp_smash/pulp3/pytest_plugin/__init__.py
The `gen_object_with_cleanup` was not compatible with objects that
required the monitoring of a task for completion. This PR monitors the
task and then handles the created_resource.
[noissue]
> Adds task following support for pytest fixtures

- pulp_smash/pulp3/pytest_plugin/__init__.py
> Adds nightly pytest marker

- pulp_smash/utils.py
> Adding a fallback for bin dir

- pulp_smash/pulp3/constants.py
> The path needed is actually V3_API_ROOT

- pulp_smash/pulp3/pytest_plugin/__init__.py
> Add cli_client fixture to pytest plugin

- pulp_smash/pulp3/pytest_plugin/__init__.py
> Make Api imports backwards compatible

- pulp_smash/pulp3/pytest_plugin/__init__.py
This fixture will collect references to pulp objects to be deleted after
a test. It will attempt deletion in reversed order and await all tasks
in parallel.
> Add add_to_cleanup fixture

- pulp_smash/cli.py
> Do not run podman with sudo

- pulp_smash/pulp3/pytest_plugin/__init__.py
- pulp_smash/pulp3/pytest_plugin/pulphooks.py
> Adds the --pulp-no-leftover-objs pytest arg

- pulp_smash/pulp3/pytest_plugin/__init__.py
> Use the new way the bindings are imported

- pulp_smash/pulp3/pytest_plugin/__init__.py
The pulpcore fixtures are moving to the pulpcore repo so they can be
versioned with pulpcore.
Required PR: https://github.com/pulp/pulpcore/pull/2562
[noissue]
> Removes pulpcore fixtures

- pulp_smash/pulp3/pytest_plugin/__init__.py
> Remove stray import

- pulp_smash/pulp3/pytest_plugin/__init__.py
> Stop depending on config at import time

- pulp_smash/pulp3/pytest_plugin/__init__.py
> Add --nightly flag to commandline

- pulp_smash/pulp3/pytest_plugin/__init__.py
When creating objects that need cleanup later, you may end up with
multiple created_resource objects in the task. This adds support for
that situation, and it will find the right type instead of raising an
Exception.
[noissue]
> Add support for multiple created_resources

- pulp_smash/utils.py
> Fixes how pulpcore-manager command is discovered

- setup.py
> Remove upperbound on click pin

- pulp_smash/cli.py
> Update s6-svc commands

- pulp_smash/pulp3/pytest_plugin/__init__.py
- tests/test_cli.py
> Replace the function scope with the class scope
