pulp/pulp-smash

- pulp_smash/__main__.py
The capitalized False in the example is not proper JSON. I was getting an error until I changed it to a lower case.
> Fixed example of config for verify setting.

- README.rst
Fix the link pointing to `www.pulpproject.org`.
> Fix link in README.rst

- .travis.yml
Given that the purpose of Pulp Smash is to test Pulp, it makes more sense for
Pulp contributors to see notifications than Robottelo contributors.
> Make Travis notify chat.freenode.net#pulp

- pulp_smash/tests/test_login.py
Update method `pulp_smash.tests.test_login.LoginFailureTestCase.test_body`. Formerly, the test asserted that the response body did not contain "key" and "certificate" keys, as documented [here](https://pulp.readthedocs.org/en/latest/dev-guide/integration/rest-api/authentication.html). Now, the test asserts that the response body has the keys documented [here](https://pulp.readthedocs.org/en/latest/dev-guide/conventions/exceptions.html#exception-handling), plus the "href" key as documented [here](PulpQE#9 (comment)).
Test results:
$ python -m unittest2 pulp_smash.tests.test_login
F...
======================================================================
FAIL: test_body (pulp_smash.tests.test_login.LoginFailureTestCase)
Assert that the response is valid JSON and does not have "key" and …
> Update login test

- docs/about.rst
- pulp_smash/tests/__init__.py
Fix #4:
> Let's suppress SSL verification warnings. If a user sets "verify": False in
> their configuration file, then the responsibility for the fall-out of that
> decision lies with them. And if they do not suppress SSL verification, then a
> different warning is raised.
Do this by using `warnings.simplefilter`. Example results:
$ python -m unittest2 discover pulp_smash.tests
....F...
======================================================================
FAIL: test_body (pulp_smash.tests.test_login.LoginFailureTestCase)
Assert that the response is valid JSON and does not have "key" and
Traceback (most recent call last):
File "/home/ichimonji10/code/pulp-smash/pulp_smash/tests/test_login.py", line 70, in test_body …
> Ignore SSL verification warnings

- docs/api.rst
- docs/api/pulp_smash.tests.platform.api_v2.test_search.rst
- pulp_smash/tests/platform/api_v2/test_search.py
Add a new module, `pulp_smash.tests.platform.api_v2.test_search`:
> """Test Pulp's `Searching`_ facilities.
>
> The tests in this module make use of the `User APIs`_. However, few
> user-specific references are made. These tests could be rewritten to use
> repositories or something else with only minimal changes. Thus, the name of
> this module.
>
> Each test case executes one or more pair of semantically identical POST and GET
> requests. Each pair of search results should match exactly.
Beware that the tests are slightly doctored to achieve these results. When
searching for users, search results do not contain an "id" attribute. The
affected tests work around this issue by referencing `['_id']['$oid']` instead.
Test results:
$ python -m unittest2 …
> Add tests for Pulp's searching facilities

- Makefile
- docs/api.rst
- docs/api/pulp_smash.tests.platform.api_v2.test_repository.rst
- docs/api/pulp_smash.utils.rst
- pulp_smash/constants.py
- pulp_smash/tests/platform/api_v2/test_repository.py
- pulp_smash/utils.py
This commit also introduces a ``utils`` module which currently only
provides a function to generate random strings using ``uuid.uuid4``.
> Add basic tests for repository CRUD.

- docs/api.rst
- docs/api/pulp_smash.tests.rpm.api_v2.rst
- docs/api/pulp_smash.tests.rpm.api_v2.test_sync_publish.rst
- docs/api/pulp_smash.tests.rpm.rst
- pulp_smash/constants.py
- pulp_smash/tests/rpm/__init__.py
- pulp_smash/tests/rpm/api_v2/__init__.py
- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
Add RPM repository tests. Module `pulp_smash.tests.rpm.api_v2.test_repo_create`
includes the following test cases:
* `CreateTestCase` ensures it is possible to create repositories with and
without feeds.
* `SyncValidFeedTestCase` and `SyncInvalidFeedTestCase` ensure that Pulp
correctly handles sync requests, regardless of whether the feed is valid.
* `PublishTestCase` ensures it is possible to upload an RPM file to a
repository, copy the repository's contents to a second repository, add a
distributor to the first repository, publish the first repository, and
download the original RPM.
Test results:
$ python -m unittest2 pulp_smash.tests.rpm.api_v2.test_sync_publish
.............s........
Ran 22 tests in 27.118s
OK …
> Add RPM Repository tests

- Makefile
- pulp_smash/tests/platform/api_v2/test_repository.py
- pulp_smash/tests/platform/api_v2/test_search.py
- pulp_smash/tests/platform/api_v2/test_user.py
- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
- pulp_smash/utils.py
- tests/test_utils.py
Rename function `pulp_smash.utils.rand_str` to `pulp_smash.utils.uuid4` to
better reflect the actual nature of the function. Walk through modules and
fiddle with imports as needed, and in some cases drop private random string
generation functions. Make the `test-coverage` make target cover module
`pulp_smash.utils`.
Test results when rebased onto the `failures` branch (#38) and run against a
Pulp 2.6 system:
$ python -m unittest2 discover pulp_smash.tests
....s...ssssssss.ss.....ssss........................................s........
Ran 72 tests in 66.057s
OK (skipped=16)
Fix #35.
> Rename utility function, expand coverage

- .travis.yml
- requirements-dev.txt
- setup.py
From #2:
> The canonical way to run Pulp Smash's unit tests is via the `make test` command.
> This works, but its implementation is entirely ad-hoc. We should consider
> supporting the `test` command provided by setuptools. According to [the
> documentation](http://pythonhosted.org/setuptools/setuptools.html#test):
>
> > The test command runs a project’s unit tests without actually deploying it, by
> > temporarily putting the project’s source on sys.path, after first running
> > build_ext -i and egg_info to ensure that any C extensions and project metadata
> > are up-to-date.
Remove `unittest2` from `requirements-dev.txt`. It is already listed in
`setup.py`, and the duplication was a bug.
Move `mock` from `requirements-dev.txt` to `setup.py`. This change means that
Pulp Smash has a new …
> Support `./setup.py test`

- Makefile
- requirements-dev.txt
Update the `lint` make target so it passes. See individual commit messages for more details.
Fix #46.
> Fix failing `lint` make target

- pulp_smash/tests/platform/api_v2/test_repository.py
- pulp_smash/utils.py
Add a decorator for skipping tests, `pulp_smash.utils.require`. Use it to skip a test that is known to fail under Pulp 2.6 and older. See individual commit messages for more details.
> Skip tests affected by bug 695

- pulp_smash/utils.py
Fix #58:
> Many places in the tests combine URLs and paths with simple string addition.
> This has the potential to produce incorrect results. […] Pulp should produce
> paths that behave correctly with urljoin, and we've had problems in the past
> with developers making "relative paths" that have a leading slash.
Using urljoin instead of plain string concatenation lets Pulp Smash test the
paths returned by Pulp. If Pulp returns a relative path with a leading slash,
plain string concatenation will produce a path containing a (typically harmless
but incorrect) `//`, but urljoin will produce a just-plain-wrong URL.
Test results both before and after change:
============  =========================================
Pulp Version  Test Suite Results
============ …
> Use urljoin in `pulp_smash.utils`

- Makefile
- docs/api.rst
- docs/api/pulp_smash.api.rst
- docs/api/pulp_smash.selectors.rst
- docs/api/tests.test_selectors.rst
- pulp_smash/api.py
- pulp_smash/selectors.py
- pulp_smash/tests/platform/api_v2/test_content_applicability.py
- pulp_smash/tests/platform/api_v2/test_login.py
- pulp_smash/tests/platform/api_v2/test_repository.py
- pulp_smash/tests/platform/api_v2/test_search.py
- pulp_smash/tests/platform/api_v2/test_user.py
- pulp_smash/tests/rpm/api_v2/test_iso_crud.py
- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
- pulp_smash/utils.py
- tests/test_api.py
- tests/test_selectors.py
- tests/test_utils.py
Partially address #64. Introduce, document and partially unit test a new class, `pulp_smash.api.Client`. This series of commits reworks the following modules:
* `pulp_smash.tests.platform.api_v2.test_user`
* `pulp_smash.tests.platform.api_v2.test_login`
* `pulp_smash.tests.platform.api_v2.test_content_applicability`
* `pulp_smash.tests.platform.api_v2.test_search`
Also move functions for selecting and deselecting tests (such as `@require`) to `pulp_smash.selectors`.
> Introduce `pulp_smash.api.Client`

- Makefile
- docs/api.rst
- docs/api/pulp_smash.cli.rst
- docs/api/tests.test_cli.rst
- pulp_smash/__main__.py
- pulp_smash/cli.py
- pulp_smash/config.py
- setup.py
- tests/test_cli.py
- tests/test_config.py
Add, document and test module `pulp_smash.cli`. This module provides "tools for
working with Pulp's CLI." This fixes #32:
> It'd be nice if we could inspect the state of remote systems under test. For
> example, it may be useful to log in to a remote system and determine whether
> certain files are lying around in certain places in the file system.
Here's a simple example of how to use the new module:
```python
>>> from pulp_smash import cli, config
>>> server_config = config.ServerConfig('localhost')
>>> client = cli.Client(server_config)
>>> response = client.run(('echo', '-n', 'foo'))
>>> response.returncode == 0
True
>>> response.stdout == 'foo'
True
>>> response.stderr == ''
True
```
The `Client` class is flexible enough that both request and response handling
can be customized on a …
> Add a CLI helper

- docs/api.rst
- docs/api/pulp_smash.tests.rpm.api_v2.test_broker.rst
- pulp_smash/cli.py
- pulp_smash/tests/rpm/api_v2/test_broker.py
- pulp_smash/utils.py
- tests/test_cli.py
- tests/test_utils.py
This PR is comprised of two commits:
1. Add utilities for managing system services. These utilities execute shell commands like "systemctl start httpd" or "sudo service httpd stop," and they do so either locally or over SSH.
2. Add broker (re)connect tests.
I *just* ran the tests one final time as a sanity check. Each of the following commands run as expected on my system:
```sh
PULP_SMASH_CONFIG_FILE=$PS_CONFIG \
python -m unittest2 pulp_smash.tests.rpm.api_v2.test_broker
PULP_SMASH_CONFIG_FILE=$PS_CONFIG \
python -m unittest2 discover pulp_smash.tests
```
Related to #31 and #55.
> Add broker (re)connect tests

- docs/api.rst
- docs/api/pulp_smash.tests.rpm.api_v2.test_broker.rst
- pulp_smash/cli.py
- pulp_smash/tests/puppet/api_v2/test_sync_publish.py
- pulp_smash/tests/rpm/api_v2/test_broker.py
- pulp_smash/utils.py
- tests/test_cli.py
- tests/test_utils.py
Skip known-failing test code affected by Pulp issue 1440. [1] This issue affects
`pulp_smash.tests.puppet.api_v2.test_sync_publish.PublishTestCase`. Test results
before this commit (21 and 11 tests, respectively):
============  =============================
Pulp Version  Test Suite Results
============  =============================
2.7           OK
dev (2.8)     FAILED (errors=1)
============  =============================
Test results after this commit (21 tests):
============  ==================
Pulp Version  Test Suite Results
============  ==================
2.7           OK
dev (2.8)     OK
============  ==================
Test results produced locally with the following command:
PULP_SMASH_CONFIG_FILE=$PS_CONFIG \
python -m unittest2 pulp_smash.tests.puppet.api_v2.test_sync_publish …
> Skip tests affected by Pulp 1440

- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
This PR includes two logically separate commits. The first commit refactors a test and places assertions within a `subTest` context manager. This allows the various assertions to all run, even if some fail. The second commit skips one of those assertions due to [issue 1570](https://pulp.plan.io/issues/1570). See the individual commit messages for more details.
> Refactor test, skip known failing assertion

- pulp_smash/config.py
Make ConfigFileNotFoundError error when searching for the configuration
file more clear in terms of which paths have been searched.
After the changes:
```
$ XDG_CONFIG_DIRS=`pwd`/pulp_smash python -c "from pulp_smash.config import get_config; get_config()"
Traceback (most recent call last):
...
pulp_smash.exceptions.ConfigFileNotFoundError: No configuration files could be located after searching for a file named "settings.json" in the standard XDG configuration paths, the following paths were searched: /home/elyezer/.config/pulp_smash/settings.json, /home/elyezer/pulp-smash/pulp_smash/pulp_smash/settings.json.
```
> More descriptive ConfigFileNotFoundError message

- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
SyncValidFeedTestCase and SyncInvalidFeedTestCase didn't delete
repositories after completition.
Fixed by adding repositories' paths to resources for deletion.
This commit does not affect functionality of pulp-smash.
> RPM tests bugfix

- Makefile
By default, Pylint acts in a completely single-threaded manner. This is a
horrible inefficiency on modern CPUs that often offer four or more cores. Edit
the `lint-pylint` make target and set the `--jobs` flag for each pylint
invocation.
This change brings significant performance improvements. On one test system
available to the author, `lint-pylint` execution time dropped from 16 to 11
seconds. On a second test system, execution time dropped from 43 to 22 seconds.
> Let pylint use all CPU cores

- pulp_smash/cli.py
Refactor function `pulp_smash.cli._get_service_manager`. This function currently attempts to determine which service manager is used by executing commands like:
which systemctl
which service
This works in some cases. But on some systems, like RHEL 6, both of these commands will fail — despite the fact that `/sbin/service` exists! The issue is that, when executing commands remotely (e.g. `ssh pulp.example.com which service`), a non-interactive shell is launched. And the commands that add `/sbin` to `$PATH` only are contained in `/etc/profile`, which only executes for interactive shells.
Edit the `_get_service_manager` function and make it also execute the following:
test -x /sbin/service
Also, edit several details of that function, including the message generated when no service manager …
> Refactor logic for detecting a service manager

- docs/about.rst
Fix #5:
> The *Pulp Smash* → *About* → *Scope and Limitations* →
> [*Destructiveness*](http://pulp-smash.readthedocs.org/en/latest/about.html#destructiveness)
> section in the documentation should be expanded. That section currently
> states:
>
> > Should Pulp Smash record all changes it makes to a remote system and revert
> > them when testing is complete, or should systems be treated as throw-away?
> > In other words, should the systems under test be treated like pets or
> > cattle? [3] This has yet to be decided.
>
> It would be good to decide this so that we can adapt tests from the existing
> Pulp Automation test suite with confidence.
As of 7297270084267b4ffe8e9279542b558cc93dbf04, we have clearly decided that Pulp Smash is a destructive test suite that does terrible things to the …
> Explain that Pulp Smash is highly destructive

- pulp_smash/tests/rpm/api_v2/test_broker.py
In the first commit, better isolate each of the broker reconnect tests. In the second commit, skip a known-failing test.
> Make broker reconnect tests green

- docs/api.rst
- docs/api/pulp_smash.tests.docker.cli.rst
- docs/api/pulp_smash.tests.docker.cli.test_crud.rst
- docs/api/pulp_smash.tests.docker.cli.test_sync.rst
- pulp_smash/tests/docker/cli/__init__.py
- pulp_smash/tests/docker/cli/test_crud.py
- pulp_smash/tests/docker/cli/test_sync.py
Add CLI tests for creating & syncing docker repos
Add and document the following modules:
* `pulp_smash.tests.docker.cli`
* `pulp_smash.tests.docker.cli.test_crud`
* `pulp_smash.tests.docker.cli.test_sync`
Test results after this addition:
=========  ==========  ==================
Pulp Ver.  Num. Tests  Test Suite Results
=========  ==========  ==================
2.7        9           OK (skipped=2)
dev (2.8)  12          OK (skipped=1)
=========  ==========  ==================
Test results generated with:
python -m unittest2 discover pulp_smash.tests.docker.cli
Submit Pulp issue 1637 [1], "Pulp Admin returns 0 even when docker sync fails." This issue accounts for one skipped test on both Pulp 2.7 and dev.
Submit Pulp issue 1640 [2], "Pulp 2.7 should gracefully fail with Docker v2 …
> Add CLI tests for creating & syncing docker repos

- pulp_smash/constants.py
- pulp_smash/tests/ostree/__init__.py
- pulp_smash/tests/ostree/api_v2/test_sync_publish.py
Remove the unconditional `skipTest` exception raised by function `setUpModule` in module `pulp_smash.tests.ostree.api_v2.test_sync_publish`.
Add a `load_tests` function [1] to package `pulp_smash.tests.ostree`. This function talks to the Pulp server under test, asks it for a list of content unit types, and uses that information in choosing whether to run the OSTree tests.
This works because each plugin adds one (or more?) content unit type to Pulp. The types added by a given plugin are listed in the documentation for those plugins. For example, see:
* http://pulp-ostree.readthedocs.org/en/latest/tech-reference/type.html
* http://pulp-python.readthedocs.org/en/latest/reference/python-type.html
Due to Pulp issue 1642 [2], this only works well on Pulp 2.7. On Pulp 2.8, the OSTree plugin does …
> Conditionally execute OSTree tests

- docs/api.rst
- docs/api/pulp_smash.tests.rpm.api_v2.test_duplicate_uploads.rst
- pulp_smash/tests/rpm/api_v2/test_duplicate_uploads.py
Add and document a new module,
`pulp_smash.tests.rpm.api_v2.test_duplicate_uploads`. This module tests Pulp's
ability to correctly handle uploads of duplicate RPM files. The newly added
tests pass:
=========  ==========  ==================
Pulp Ver.  Num. Tests  Test Suite Results
=========  ==========  ==================
2.7        1           OK
dev (2.8)  1           OK
=========  ==========  ==================
Test suite results generated with:
python -m unittest2 pulp_smash.tests.rpm.api_v2.test_duplicate_uploads
Related to #81 and https://pulp.plan.io/issues/1406.
> Test Pulp's handling of duplicate RPM uploads

- pulp_smash/tests/rpm/api_v2/test_retain_old_count.py
Refactor the docstring and contents of
`RetainOldCountTestCase.test_retain_old_count_works`. Make the docstring
more clearly explain the Pulp feature being tested, and make the test
itself more concise, with only one assertion instead of two.
Test results do not change as a result of this commit.
> Refactor RPM test for retain_old_count option

- pulp_smash/tests/ostree/api_v2/test_sync_publish.py
Using super small repository keeps the test from timing out and taking a ton of storage.  Also, nice that it runs much faster.
> Update OSTree test to use small repo on fedorapeople.

- pulp_smash/tests/rpm/api_v2/test_schedule_sync.py
According to Pulp issue 1745 [1]:
> If an incorrect JSON data type is provided when creating a sync
> schedule (say an array rather than an object), Pulp returns an HTTP
> 500 rather than HTTP 400. […] This issue affects Pulp 2.7, but not
> Pulp 2.8.
This issue is likely to be marked as WONTFIX. Permanently skip the
relevant assertion. Test suite results do not change. Test suite results
generated with:
pulp_smash.tests.rpm.api_v2.test_schedule_sync.CreateFailureTestCase
[1] https://pulp.plan.io/issues/1745
> Permanently skip an RPM test under Pulp 2.7

- pulp_smash/exceptions.py
- pulp_smash/selectors.py
- pulp_smash/tests/docker/cli/test_crud.py
- pulp_smash/tests/docker/cli/test_sync_publish.py
- pulp_smash/tests/platform/api_v2/test_login.py
- pulp_smash/tests/platform/api_v2/test_repository.py
- pulp_smash/tests/puppet/api_v2/test_sync_publish.py
- pulp_smash/tests/rpm/api_v2/test_broker.py
- pulp_smash/tests/rpm/api_v2/test_iso_crud.py
- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
- pulp_smash/tests/rpm/api_v2/test_updateinfo.py
- tests/test_selectors.py
Change the signatures of `bug_is_testable` and `bug_is_untestable` in module `pulp_smash.selectors`, from this:
```python
bug_is_testable(bug_id)
bug_is_untestable(bug_id)
```
To this:
```python
bug_is_testable(bug_id, pulp_version)
bug_is_untestable(bug_id, pulp_version)
```
The new `pulp_version` parameter is "A ``packaging.version.Version`` object telling the version of the Pulp server we are testing." It lets the function determine whether a bug is testable or not based not only on the state of a bug, but the Pulp version in which the bug was fixed relative to the Pulp version we're testing against. Sample usage:
```python
>>> from packaging.version import Version
>>> from pulp_smash.selectors import bug_is_testable
>>> bug_is_testable(1743, Version('2.7.0'))
False
>>> …
```
> Respect target_platform_release bug tracker field

- docs/about.rst
- docs/installation.rst
Do not attempt to lay out a comprehensive set of installation strategies with wordy explanations. Instead, list a recipe for creating a virtualenv, followed by three strategies for installing Pulp Smash, followed by a link to the official Python documentation.
Drop a redundant set of instructions in the "About" page, and reference the recipes in the "Installation" page instead.
This change is made on the theory that those people who need instructions for installing a Python package will benefit from a concise recipe-oriented approach, and those people who are interested in more in-depth explanations of Python packaging are (should be!) looking elsewhere.
> Rewrite "Installation" documentation section

- docs/about.rst
Fix #131.
Rewrite `docs/about.rst`, with a focus on the "Contributing" section.
> Document best practices for collaboration

- pulp_smash/tests/rpm/api_v2/test_download.py
- pulp_smash/utils.py
- tests/test_utils.py
When called, this new function will "tell if we are root on the target
system." Test suite results don't change as a result of this commit.
Test results generated with:
python -m unittest2 discover pulp_smash.tests
> Add function pulp_smash.utils.is_root

- Makefile
- release.sh
- requirements-dev.txt
Add release.sh script that will run all the steps to release a new version and
publish make target to upload the created package to PyPi.
> Add automated release and publish scripts

- pulp_smash/tests/platform/api_v2/test_repository.py
- pulp_smash/tests/rpm/api_v2/test_iso_crud.py
According to RFC 7231, the HTTP Location header may be either an
absolute or relative URL. Thus, given this request:
GET /index.html HTTP/1.1
Host: www.example.com
These two responses are equivalent:
HTTP/1.1 302 FOUND
Location: http://www.example.com/index.php
HTTP/1.1 302 FOUND
Location: /index.php
Update tests to abide by the RFC and allow Pulp to return either
absolute or relative URLs. This change does not affect test results on
the author's test systems, and should fix spurious test failures on some
systems. Test results generated with:
pulp_smash.tests.rpm.api_v2.test_iso_crud.CreateTestCase \
pulp_smash.tests.platform.api_v2.test_repository.CreateSuccessTestCase
Related to https://github.com/PulpQE/pulp-smash/issues/167
> Edit tests for the HTTP Location header

- pulp_smash/api.py
When Pulp Smash receives an HTTP 202 "accepted" response from Pulp, it
polls each of the spawned tasks and waits for them to complete. (This is
the default behaviour.) Pulp Smash gives each individual task roughly
two minutes to complete before timing out and raising a
`TaskTimedOutError`. Timing out in this manner has value: we don't want
to let a single misbehaved task to block the test suite from executing,
and if a single task takes excessively long, this can be considered a
bug in its own right.
Unfortunately, real world test results show that a wide variety of tasks
occasionally take longer than two minutes. The failures occur at a low
rate, but are widely spread through the test suite. In one especially
bad test run, five of roughly eighty test cases failed.
There are at least two …
> Increase task polling timeout

- Makefile
The `lint-pylint` make target runs the Pylint linter over the code base.
A small number of checks are disabled, including import checks. Why are
import checks disabled? The import checks will issue a warning in the
case where four or more import lines are identical, and it will
therefore catch the following:
```python
try:  # try Python 3 first
from urllib.parse import urljoin
except ImportError:
from urlparse import urljoin
```
This was considered a low-priority issue for some time. However, the
introduction of module `pulp_smash.compat` has solved this issue, and
there is now much less reason to ignore this check.
Update the `lint-pylint` make target and let Pylint check for
import-related issues.
> Let linter check imports

- pulp_smash/tests/docker/api_v2/test_crud.py
- pulp_smash/tests/docker/cli/test_copy.py
- pulp_smash/tests/docker/cli/test_crud.py
- pulp_smash/tests/docker/cli/test_sync_publish.py
- pulp_smash/tests/ostree/api_v2/test_crud.py
- pulp_smash/tests/ostree/api_v2/test_sync_publish.py
- pulp_smash/tests/ostree/utils.py
- pulp_smash/tests/puppet/api_v2/test_sync_publish.py
- pulp_smash/tests/rpm/api_v2/test_broker.py
- pulp_smash/tests/rpm/api_v2/test_comps_groups.py
- pulp_smash/tests/rpm/api_v2/test_download.py
- pulp_smash/tests/rpm/api_v2/test_duplicate_uploads.py
- pulp_smash/tests/rpm/api_v2/test_export.py
- pulp_smash/tests/rpm/api_v2/test_iso_crud.py
- pulp_smash/tests/rpm/api_v2/test_orphan_remove.py
- pulp_smash/tests/rpm/api_v2/test_remove_unit.py
- pulp_smash/tests/rpm/api_v2/test_repomd.py
- pulp_smash/tests/rpm/api_v2/test_republish.py
- pulp_smash/tests/rpm/api_v2/test_retain_old_count.py
- pulp_smash/tests/rpm/api_v2/test_schedule_publish.py
- pulp_smash/tests/rpm/api_v2/test_schedule_sync.py
- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
- pulp_smash/tests/rpm/api_v2/test_unassociate.py
- pulp_smash/tests/rpm/api_v2/test_updateinfo.py
- pulp_smash/utils.py
- tests/test_utils.py
This pull request contains two commits. The first commit rewrites existing logic for skipping tests based on whether or not a plugin is installed. It doesn't expand that logic to any new modules. It just takes what's already in place and shuffles around the pieces. This makes it easy to verify: one need only run tests for two test modules and verify that nothing has broken. The second commit expands the per-plugin test skipping logic to the entire test suite.
> Skip tests for which a plugin is not installed

- Makefile
- docs/Makefile
Create a "phony" target, `gen-api-docs`, in `docs/Makefile`. This new
target generates reStructuredText API documents in `docs/api/`. Ensure
this target is called by other make targets as appropriate.
Fix #204.
> Ensure docs/Makefile builds API docs

- docs/api.rst
Add module `pulp_smash.tests.puppet.api_v2.utils` to API docs. This
should have been done in 6cd0dae698ac44d8b31281d38267421c7eb66e5d.
> Add module to API docs

- pulp_smash/tests/puppet/api_v2/test_duplicate_uploads.py
Add a new test case, `DuplicateUploadsTestCase`, in module
`pulp_smash.tests.puppet.api_v2.test_duplicate_uploads`. This module
uploads and imports a Puppet module into a single repository twice in a
row, and verifies that the procedure completes without any issues. The
new test case passes. Tests executed with:
pulp_smash.tests.puppet.api_v2.test_duplicate_uploads
Related to #81.
> Add test for duplicate uploads of a Puppet module

- docs/api.rst
- pulp_smash/tests/python/__init__.py
- pulp_smash/tests/python/api_v2/__init__.py
- pulp_smash/tests/python/api_v2/test_crud.py
- pulp_smash/tests/python/api_v2/utils.py
- pulp_smash/tests/python/utils.py
Add package `pulp_smash.tests.python`. Populate it with a variety of
modules, including a several utility modules and some CRUD tests. The
new CRUD tests pass with the following commands:
```sh
python -m unittest2 discover pulp_smash.tests.python
python -m unittest2 pulp_smash.tests.python.api_v2.test_crud
```
> Add Python CRUD tests

- pulp_smash/constants.py
- pulp_smash/tests/python/api_v2/test_duplicate_uploads.py
Add a new test case, `DuplicateUploadsTestCase`, in module
`pulp_smash.tests.python.api_v2.test_duplicate_uploads`. This module
uploads and import a Python package into a single repository twice in a
row, and verifies that the procedure completes without any issues. The
new test case passes. Tests executed with:
pulp_smash.tests.python.api_v2.test_duplicate_uploads
Related to: https://github.com/PulpQE/pulp-smash/issues/81
This commit is highly similar to
4b11dbb73f820aa76b6756f550a2b84a5a7844f6. It would be beneficial to
refactor out the commonalities.)
> Add test for duplicate uploads of a Python package

- pulp_smash/api.py
- pulp_smash/tests/puppet/api_v2/test_duplicate_uploads.py
- pulp_smash/tests/puppet/api_v2/test_sync_publish.py
- pulp_smash/tests/python/api_v2/test_duplicate_uploads.py
- pulp_smash/tests/rpm/api_v2/test_broker.py
- pulp_smash/tests/rpm/api_v2/test_duplicate_uploads.py
- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
- pulp_smash/utils.py
The http_get function helps on getting files over HTTP[S], for example getting
the contents of a RPM published over HTTP[S].
Also refactor places where API client was used to get the files. This will
avoid SSL issue when the default server configuration specifies a verify
certificate.
Finally issue a warning on the API client when the user is doing requests to
other host than the one specified by its server config.
> Add http_get util function

- pulp_smash/tests/rpm/api_v2/test_updateinfo.py
If no value is specified for an errata's `reboot_suggested` field, the
errata is uploaded into a repository, and the repository is published,
the repository's `updateinfo.xml` file should not suggest a reboot. The
file's `<reboot_suggested>` tag should have a value of "False".
Add a test for: https://pulp.plan.io/issues/1782
Fix: https://github.com/PulpQE/pulp-smash/issues/214
> Test whether updateinfo.xml suggests a reboot

- docs/api.rst
- docs/api/pulp_smash.tests.puppet.api_v2.test_crud.rst
- pulp_smash/tests/docker/api_v2/test_crud.py
- pulp_smash/tests/ostree/api_v2/test_crud.py
- pulp_smash/tests/puppet/api_v2/test_crud.py
- pulp_smash/tests/python/api_v2/test_crud.py
- pulp_smash/utils.py
Create a new class, `pulp_smash.utils.BaseAPICrudTestCase`, use it for all CRUD tests, and add Puppet CRUD tests. This new base test case ships with seven test methods, so the number of tests is greatly expanded. And if we want to add any new test coverage or edit the existing test, it'll be much easier to do so now.
This PR is split in to three commits for the purpose of logically separating several different tasks.
> Unify and expand CRUD testing

- docs/api.rst
- docs/api/pulp_smash.tests.python.api_v2.test_duplicate_uploads.rst
Add module `pulp_smash.test.python.api_v2.test_duplicate_uploads` to the
API documentation. This commit corrects
6dfa9294a6c63a0724e0b5d2dbb68bf7ca885757.
> Add missing page to API documentation

- pulp_smash/constants.py
- pulp_smash/tests/puppet/api_v2/test_duplicate_uploads.py
- pulp_smash/tests/python/api_v2/test_duplicate_uploads.py
- pulp_smash/tests/rpm/api_v2/test_broker.py
- pulp_smash/tests/rpm/api_v2/test_duplicate_uploads.py
- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
- pulp_smash/utils.py
- tests/test_utils.py
All five of the plugins listed in #81 should have a test case for duplicate uploads. For the third of five plug-ins, I simply copied and pasted a module and fiddled with a few things. That's about when I knew it was a good time to refactor things.
Work is split into three commits for the sake of logical separation.
> Refactor Duplicate Upload Test Cases

- pulp_smash/tests/python/api_v2/test_duplicate_uploads.py
Every module of tests should check to see if the necessary Pulp plugins
are installed before executing. If the plugin is missing, that module
should skip. Unfortunately, module
`pulp_smash.tests.python.api_v2.test_duplicate_uploads` is missing this
check. Add it in. This should fix a failing test in Jenkins. Test
results are sane, both when run against systems with and without the
plugin, with the following command:
python -m unittest2 discover pulp_smash.tests.python.api_v2
> Conditionally skip Python duplicate upload tests

- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
Pulp's RPM plugin has the ability to sync not only RPM repositories, but
DRPM and SRPM repositories too. Add test cases which do this.
Implementation notes:
* Add two new constants, `DRPM_FEED_URL` and `SRPM_FEED_URL`.
* Create a new base test case, `SyncRepoBaseTestCase`, and three child
classes, `SyncRpmRepoTestCase`, `SyncDrpmRepoTestCase` and
`SyncSrpmRepoTestCase`.
* Class `SyncValidFeedTestCase` has effectively been renamed to
`SyncRpmRepoTestCase`.
All affected tests pass. Tests executed with:
python -m unittest2 pulp_smash.tests.rpm.api_v2.test_sync_publish
Fix https://github.com/PulpQE/pulp-smash/issues/161
> Sync DRPM and SRPM repositories

- pulp_smash/tests/docker/cli/test_sync_publish.py
Pulp issue 1868 [1] affects the Docker CLI test
`SyncPublishV2TestCase.test_blob_digests` on RHEL 6. Skip the test as
appropriate. This change does not affect test results on other
platforms, such as Fedora 22 or 23. Tests executed with:
pulp_smash.tests.docker.cli.test_sync_publish.SyncPublishV2TestCase
[1] https://pulp.plan.io/issues/1868
> Skip test affected by Pulp issue 1868

- pulp_smash/tests/rpm/api_v2/test_comps_groups.py
According to the bug [1], if an input package group has no
`display_order` element, then output XML should also omit said element.
The relevant test asserts that said element always appears exactly once
in the output — not good!
Thanks to @rohanpm for finding this issue.
Test results do not change as a result of this commit. (The test is
currently skipped.) Tests executed with:
python -m unittest2 pulp_smash.tests.rpm.api_v2.test_comps_groups
[1] https://pulp.plan.io/issues/1787
> Fix test for Pulp bug 1787

- pulp_smash/__main__.py
- pulp_smash/config.py
- pulp_smash/exceptions.py
- tests/test_config.py
Fix https://github.com/PulpQE/pulp-smash/issues/224
It's technically already possible to create test cases that target both
a Pulp server and a Pulp agent. However, there is not proper
documentation for how to do this. Create such.
The most significant change in this commit regards the contents of
configuration files. Configuration files may now have two sections.
Here's what `python -m pulp_smash` has to say about the topic:
> The configuration file should have this structure:
>
>     {
>         "pulp": {
>             "base_url": "https://pulp.example.com",
>             "auth": ["username", "password"],
>             "verify": true,
>             "version": "2.7.5",
>             "cli_transport": "local"
>         },
>         "pulp agent": {
>             "base_url": …
> Change expected configuration file contents

- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
Class `SyncRepoBaseTestCase` is an abstract base class, and it should
not run. However, children of this class are expected to implement
abstract functionality and should run. The current attempt to implement
this is as follows:
```python
@unittest2.skip(…)
class SyncRepoBaseTestCase(…):
```
This fails, of course: child classes also execute this decorator. Use
reflection instead: a `SkipTest` exception is raised only if the first
element in the MRO tree is `SyncRepoBaseTestCase`.
This change allows more tests to run, without introducing any test
failures. Tests executed with:
python -m unittest2 pulp_smash.tests.rpm.api_v2.test_sync_publish
> Run children of SyncRepoBaseTestCase

- pulp_smash/constants.py
The new Pulp Fixtures [1] project is now being used to generate RPM and
Docker fixture files. Make use of them, instead of the old demo files.
The following command succeeds:
python -m unittest2 pulp_smash.tests.rpm.api_v2.test_sync_publish
[1] https://github.com/PulpQE/pulp-fixtures
> Update RPM_FEED_URL constant

- docs/api.rst
- docs/api/pulp_smash.tests.docker.api_v2.test_duplicate_uploads.rst
- pulp_smash/constants.py
- pulp_smash/tests/docker/api_v2/test_duplicate_uploads.py
Add module `pulp_smash.tests.docker.api_v2.test_duplicate_uploads`. This
new module has one test case, `DuplicateUploadsTestCase`, which uploads
a Docker image to a Docker repository twice in a row, and verifies that
the upload succeeds. The new test succeeds when run with:
pulp_smash.tests.docker.api_v2.test_duplicate_uploads
Also add a new constant, `DOCKER_IMAGE_URL`:
> The URL to a Docker iamge as created by `Docker save`.
Fix: https://github.com/PulpQE/pulp-smash/issues/81
> Add a duplicate file upload test for Docker

- docs/api.rst
- docs/api/pulp_smash.tests.rpm.cli.rst
- docs/api/pulp_smash.tests.rpm.cli.test_copy_units.rst
- pulp_smash/tests/rpm/cli/__init__.py
- pulp_smash/tests/rpm/cli/test_copy_units.py
Add module `pulp_smash.tests.rpm.cli.test_copy_units`. Add two test
cases:
1. `CopyTestCase`
2. `CopyRecursiveTestCase`
The first test case copies a single unit named "chimpanzee" from a
source repository to a target repository. The second test case
*recursively* copies a single unit named "chimpanzee" from a source
repository to a target repository.
The second test fails, and is skipped so long as Pulp issue 1895 is
open. See: https://pulp.plan.io/issues/1895
Test results are OK. Tests executed with:
python -m unittest2 pulp_smash.tests.rpm.cli.test_copy_units
Fix: https://github.com/PulpQE/pulp-smash/issues/107
> Test copying units between RPM repositories w/CLI

- pulp_smash/tests/rpm/api_v2/test_download_policies.py
Having this information should make debugging test failures easier. This
change does not affect test results for systems on which the tests
already pass. Tests executed with:
pulp_smash.tests.rpm.api_v2.test_download_policies
> Make test assertions more verbose

- pulp_smash/tests/rpm/api_v2/test_download_policies.py
Test results do not change on systems for which the test passes. Tests
executed with:
pulp_smash.tests.rpm.api_v2.test_download_policies.BackgroundTestCase
> Make an assertion more verbose

- README.rst
- docs/installation.rst
- pulp_smash/api.py
- pulp_smash/cli.py
- pulp_smash/constants.py
- pulp_smash/exceptions.py
- pulp_smash/selectors.py
- pulp_smash/tests/ostree/api_v2/test_crud.py
- pulp_smash/tests/ostree/api_v2/test_sync_publish.py
- pulp_smash/tests/platform/api_v2/test_consumer.py
- pulp_smash/tests/platform/api_v2/test_content_applicability.py
- pulp_smash/tests/platform/api_v2/test_login.py
- pulp_smash/tests/platform/api_v2/test_repository.py
- pulp_smash/tests/platform/api_v2/test_search.py
- pulp_smash/tests/platform/api_v2/test_user.py
- pulp_smash/tests/puppet/api_v2/test_sync_publish.py
- pulp_smash/tests/rpm/api_v2/test_export.py
- pulp_smash/tests/rpm/api_v2/test_iso_crud.py
- pulp_smash/tests/rpm/api_v2/test_remove_unit.py
- pulp_smash/tests/rpm/api_v2/test_retain_old_count.py
- pulp_smash/tests/rpm/api_v2/test_schedule_publish.py
- pulp_smash/tests/rpm/api_v2/test_schedule_sync.py
- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
- pulp_smash/tests/rpm/api_v2/test_unassociate.py
- pulp_smash/utils.py
From an announcement sent on 2016-04-27:
> Starting today, Read the Docs will start hosting projects from
> subdomains on the domain readthedocs.io, instead of on
> readthedocs.org. This change addresses some security concerns around
> site cookies while hosting user generated data on the same domain as
> our dashboard.
> Link to readthedocs.io, not readthedocs.org

- pulp_smash/tests/rpm/api_v2/test_download_policies.py
Test case `FixFileCorruptionTestCase` in module
`pulp_smash.tests.rpm.api_v2.test_download_policies` is affected by Pulp
issue 1905. [1] This can be proved by running the test case and
examining logs on the target system as the tests run. Skip the test case
when the Pulp host is running RHEL 6. Tests executed against F23 and
RHEL6 hosts with the following command:
pulp_smash.tests.rpm.api_v2.test_download_policies.FixFileCorruption
Test results are improved on RHEL 6 and unchanged on other platforms.
[1] https://pulp.plan.io/issues/1905
> Skip another test affected by Pulp issue 1905

- pulp_smash/tests/docker/cli/test_sync_publish.py
Pulp issue 1909 [1] describes how Pulp 2.9 cannot sync Docker
repositories. Skip test cases affected by this issue:
* `pulp_smash.tests.docker.cli.test_sync_publish.SyncPublishV2TestCase`
* `pulp_smash.tests.docker.cli.test_sync_publish.SyncUnnamespacedV2TestCase`
* `pulp_smash.tests.docker.cli.test_sync_publish.SyncV1TestCase`
Tests executed with:
python -m unittest2 pulp_smash.tests.docker.cli.test_sync_publish
Test results are unaffected when the target Pulp system is running Pulp
2.8, and are improved when the target Pulp system is running Pulp 2.9.
> Skip tests affected by Pulp issue 1909

- pulp_smash/tests/docker/cli/test_copy.py
Pulp issue 1909 [1] describes how Pulp 2.9 cannot sync Docker
repositories. Skip the following test cases affected by this issue:
* `pulp_smash.tests.docker.cli.test_copy.CopyAllManifestsTestCase`
* `pulp_smash.tests.docker.cli.test_copy.CopyAllTagsTestCase`
Tests executed with:
python -m unittest2 pulp_smash.tests.docker.cli.test_copy
Test results are unaffected when the target Pulp system is running Pulp
2.8, and are improved when the target Pulp system is running Pulp 2.9.
Related to:
* bac8cc958420e0b913f0bd726667066cceb1783b
* a0ed1153240f7d38b5991836c847d03127e22354
* 873acbe7ca2f54f5eff34897c54a2464235f4e86
[1] https://pulp.plan.io/issues/1909
> Skip more tests affected by Pulp issue 1909

- pulp_smash/tests/rpm/api_v2/test_download_policies.py
Support for langpacks has been added in Pulp 2.9. In earlier versions of
Pulp, repositories do not track this type of content unit. Consequently,
tests that verify the number of content units in repositories must take
this in to account.
Update test `FixFileCorruptionTestCase.test_units_after_download` in
module `pulp_smash.tests.rpm.api_v2.test_download_policies`. This test
now succeeds when run against a Pulp 2.9 system, and there is no change
when the test is run against a Pulp 2.8 system. Tests executed with:
python -m unittest2 pulp_smash.tests.rpm.api_v2.test_download_policies
> Fix test for RPM repo content unit counts

- pulp_smash/tests/rpm/api_v2/test_comps_groups.py
According to Pulp issue 1787 [1], the ``display_order`` value in a
``comps.xml`` file should be "1024" if omitted from the original unit.
Update the test accordingly. Tests succeed when executed against Pulp
2.9 with:
python -m unittest2 pulp_smash.tests.rpm.api_v2.test_comps_groups
Fix https://github.com/PulpQE/pulp-smash/issues/239
[1] https://pulp.plan.io/issues/1787
> Fix RPM test for comps.xml

- pulp_smash/tests/rpm/api_v2/test_export.py
Function `utils.is_root` tells whether the Pulp Smash CLI client has
root access on a target system. A common use case for this function is
deciding whether to prefix a command with `sudo` or not. (`sudo` is an
optional system utility.) Fix an incorrect bit of logic that prepends
CLI commands with "sudo" when the test already has root access.
> Fix broken sudo logic

- pulp_smash/tests/rpm/api_v2/test_orphan_remove.py
Update module `pulp_smash.tests.rpm.api_v2.test_orphan_remove`. Expand
the set of tests executed by the test case therein. The test methods are
highly independent, so this opportunity was taken to experiment with
placing more business logic in the `test_*` methods, instead of the
`setUpClass` method.
Tested against Pulp 2.8.3 on Fedora 23 and master (2.9) on Fedora 22,
with success.
Fix: https://github.com/PulpQE/pulp-smash/issues/134
Related: https://github.com/PulpQE/pulp-smash/issues/257
> Test orphan removal API calls

- pulp_smash/tests/platform/api_v2/test_content_applicability.py
test_content_applicability makes use of an abstract test case class for the
success tests, make sure it will be skipped and not counted as a valid test.
> Skip an abstract test case class

- pulp_smash/tests/platform/api_v2/test_search.py
Pulp issue 1332 [1] has been closed in favor of Pulp issue 1933. [2]
Update bug references as appropriate. This change fixes four test
failures.
[1] https://pulp.plan.io/issues/1332
[2] https://pulp.plan.io/issues/1933
> Update outdated bug reference

- docs/api.rst
- docs/api/pulp_smash.tests.rpm.api_v2.test_search.rst
- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_search.py
Add module `pulp_smash.tests.rpm.api_v2.test_search`. This module has
two test cases:
* `SearchRpmTestCase`
* `SearchSrpmTestCase`
The `SearchRpmTestCase` creates and syncs an RPM repository, then
executes a variety of searches for RPM content units. The
`SearchSrpmTestCase` does the same, but for SRPM.
Add a new constant, `SRPM`. This new constant is the name of an SRPM
file, and it's used by `SearchSrpmTestCase`.
Related to https://github.com/PulpQE/pulp-smash/issues/133
> Add tests that search for RPM & SRPM units

- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
When one reads an RPM repository, the `content_unit_counts` attribute
lists how many units of each type are present in the repository.  Pulp
2.9 introduces support for the `package_langpacks` content type.  Update
a test that verifies the values in a repository's `content_unit_counts`
attribute.
The tests originally walked through each of the content types one at a
time and verified only specific content types. This works, but it means
that new content types can be added and the test will not notice. Make
the test more strict.
Related to: https://github.com/PulpQE/pulp-smash/issues/233
> Update content unit counts tests

- pulp_smash/tests/rpm/api_v2/test_orphan_remove.py
According to the Pulp API documentation for the POST
`/pulp/api/v2/content/actions/delete_orphans/` call, one should specify
the orphans to delete with a list of dicts, like so:
[{"content_type_id": "erratum", "unit_id": "abc123"}]
The test for this path currently passes a bare dict:
{"content_type_id": "erratum", "unit_id": "abc123"}
Fix the test.
> Fix test for the delete_orphans API call

- docs/about.rst
- docs/index.rst
- docs/introductory-module.rst
- pulp_smash/tests/platform/api_v2/test_login.py
From https://github.com/PulpQE/pulp-smash/issues/276:
> The Pulp Smash documentation has "installation," "usage," "about" and
> "API documentation" sections. One thing that's sorely lacking is a
> primer explaining how to read the existing tests and how to write new
> ones.
Address this need by adding numerous comments to module
`pulp_smash.tests.platform.api_v2.test_login`, and by including this
module in the documentation.
Fix: https://github.com/PulpQE/pulp-smash/issues/276
> Add a primer for understanding test modules

- pulp_smash/api.py
Pulp Smash has a task polling function, `poll_task`, that waits for a
task to complete and then polls each task spawned by the current task.
This function includes a hard-coded time-out. This is intended to let
Pulp Smash continue testing, even if Pulp produces a never-ending task.
The time-out is currently set to 3+ minutes. [1] This is generally
reasonable, but frequently, one or several tasks will take more than
this long. This is problematic: Pulp Smash is not in the business of
enforcing performance metrics, and it should not fail simply because of
an annoying level of slowness.
Change the time-out to 30+ minutes. This is an enormously long period of
time for any single task, and it should produce very few false-positive
test errors.
> Increase hard-coded timeout by order of magnitude

- pulp_smash/tests/docker/api_v2/test_duplicate_uploads.py
- pulp_smash/tests/puppet/api_v2/test_duplicate_uploads.py
- pulp_smash/tests/python/api_v2/test_duplicate_uploads.py
- pulp_smash/tests/rpm/api_v2/test_duplicate_uploads.py
- pulp_smash/utils.py
The `DuplicateUploadsMixin` is designed to test the following procedure:
1. Create a repository without a feed.
2. Upload a package into the repository.
3. Upload the same package into the repository.
The class is currently designed such that the two uploads should occur
in method `setUpClass`.
Refactor the test case so that repository creation occurs in
`setUpClass` and the uploads occur in the test methods. This makes it
easier to tell which of the two uploads failed, and it ensures the class
always cleans up after itself.
This change doesn't affect test coverage or introduce any test failures.
It adds four new tests. Tests executed with:
pulp_smash.tests.docker.api_v2.test_duplicate_uploads \
pulp_smash.tests.puppet.api_v2.test_duplicate_uploads \ …
> Refactor DuplicateUploadsMixin base test case

- docs/api.rst
- docs/api/pulp_smash.tests.puppet.cli.test_sync_from_puppet_skip_duplicate_content.rst
- pulp_smash/tests/puppet/cli/test_sync_from_puppet_skip_duplicate_content.py
This commit fixes the issue: https://github.com/PulpQE/pulp-smash/issues/269.
It creates two repositories with the same feed content. By synchronizing both repos, check if the 2nd repo would have content; otherwise, the sync will fail.
Test output:
```
[vagrant@dev pulp-smash]$ python -m unittest pulp_smash.tests.puppet.cli
.test_sync_from_puppet_skip_duplicate_content.SyncFromPuppetSkipDuplicateContentTestCase
F
======================================================================
FAIL: test_sync_puppet_forge (pulp_smash.tests.puppet.cli
.test_sync_from_puppet_skip_duplicate_content.SyncFromPuppetSkipDuplicateContentTestCase)
Create two Puppet repositories and trigger their syncs.
Traceback (most recent call last): …
```
> Fix up Pulp Issue #1937

- docs/api.rst
- docs/api/pulp_smash.tests.rpm.cli.test_langpacks.rst
- pulp_smash/tests/rpm/cli/test_langpacks.py
This commit fixes the issue: https://github.com/PulpQE/pulp-smash/issues/270.
It creates a new repository, uploads langpacks into it and finally remove all
langpacks from it.
Test output:
```
[vagrant@dev pulp-smash]$ python -m unittest pulp_smash.tests.rpm.cli.test_langpacks.
UploadAndRemoveLangpacksTestCase
..
Ran 2 tests in 5.546s
OK
```
> Fix up Pulp Smash #270

- docs/api.rst
- docs/api/pulp_smash.tests.rpm.api_v2.test_crud.rst
- pulp_smash/tests/rpm/api_v2/test_crud.py
- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
Move RPM CRUD tests from module
`pulp_smash.tests.rpm.api_v2.test_sync_publish` to module
`pulp_smash.tests.rpm.api_v2.test_crud`. This is in line with how other
plugin tests are structured: there are similarly-named modules for the
docker, puppet, ostree and python modules too.
Refactor the RPM CRUD tests. Use the `BaseAPICrudTestCase`, instead of
writing out numerous redundant test methods.
Simplify the docstring for module
`pulp_smash.tests.rpm.api_v2.test_sync_publish`.
> Move and refactor RPM CRUD tests

- docs/api.rst
- docs/api/pulp_smash.tests.rpm.api_v2.test_upload_publish.rst
- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
- pulp_smash/tests/rpm/api_v2/test_upload_publish.py
Move RPM upload and publish tests from module
`pulp_smash.tests.rpm.api_v2.test_sync_publish to module
`pulp_smash.tests.rpm.api_v2.test_upload_publish`. This has several
benefits:
* The `test_sync_publish` module is now as advertised: it only contains
tests that sync and publish repositories.
* The task of uploading and publishing RPM repositories is a broad one,
as a variety of content types can come in to play. They include RPM
modules, erratum, and `comps.xml` files. There's now a clear home for
these tests.
> Move RPM upload and publish tests

- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_crud.py
- pulp_smash/tests/rpm/api_v2/utils.py
Introduce a new test case class which is responsible for ensure basic CRUD for
repository group works.
Related to #159
Test results for Pulp 2.9.0:
```
$ py.test pulp_smash/tests/rpm/api_v2/test_crud.py
================================ test session starts ================================
platform linux -- Python 3.4.3, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/elyezer/code/pulp-smash, inifile: 
collected 18 items 
pulp_smash/tests/rpm/api_v2/test_crud.py ..................
============================= 18 passed in 1.71 seconds =============================
```
Test results for Pulp 2.8.5:
```
$ py.test pulp_smash/tests/rpm/api_v2/test_crud.py
================================ test session starts ================================
platform linux -- Python 3.4.3, pytest-2.9.2, …
```
> Add tests for CRUD repository group

- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_export.py
Add tests for repo group export with a custom checksum type defined.
Close #292 
Results for Pulp 2.8.5:
```
$ py.test pulp_smash/tests/rpm/api_v2/test_export.py
================================ test session starts ================================
platform linux -- Python 3.4.3, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/elyezer/code/pulp-smash, inifile: 
collected 8 items 
pulp_smash/tests/rpm/api_v2/test_export.py ssssss..
======================= 2 passed, 6 skipped in 190.68 seconds =======================
```
Results for Pulp 2.9:
```
$ py.test pulp_smash/tests/rpm/api_v2/test_export.py
================================ test session starts ================================
platform linux -- Python 3.4.3, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: …
```
> Add tests for repo group export

- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_updateinfo.py
- pulp_smash/tests/rpm/api_v2/test_upload_publish.py
- pulp_smash/tests/rpm/utils.py
- pulp_smash/utils.py
- tests/test_utils.py
The first commit performs a simple refactor, where a private function is moved into a `utils` module and made public. The second commit is where the real action happens: a brand new test case is added!
> Upload erratum

- pulp_smash/api.py
- pulp_smash/constants.py
- pulp_smash/exceptions.py
- pulp_smash/selectors.py
- pulp_smash/tests/ostree/api_v2/test_crud.py
- pulp_smash/tests/ostree/api_v2/test_sync_publish.py
- pulp_smash/tests/platform/api_v2/test_consumer.py
- pulp_smash/tests/platform/api_v2/test_content_applicability.py
- pulp_smash/tests/platform/api_v2/test_login.py
- pulp_smash/tests/platform/api_v2/test_repository.py
- pulp_smash/tests/platform/api_v2/test_search.py
- pulp_smash/tests/platform/api_v2/test_user.py
- pulp_smash/tests/puppet/api_v2/test_sync_publish.py
- pulp_smash/tests/rpm/api_v2/test_crud.py
- pulp_smash/tests/rpm/api_v2/test_export.py
- pulp_smash/tests/rpm/api_v2/test_iso_crud.py
- pulp_smash/tests/rpm/api_v2/test_orphan_remove.py
- pulp_smash/tests/rpm/api_v2/test_remove_unit.py
- pulp_smash/tests/rpm/api_v2/test_retain_old_count.py
- pulp_smash/tests/rpm/api_v2/test_schedule_publish.py
- pulp_smash/tests/rpm/api_v2/test_schedule_sync.py
- pulp_smash/tests/rpm/api_v2/test_search.py
- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
- pulp_smash/tests/rpm/api_v2/test_unassociate.py
- pulp_smash/tests/rpm/api_v2/test_upload_publish.py
- pulp_smash/tests/rpm/cli/test_search.py
- pulp_smash/utils.py
Pulp documentation in being moved from Read the Docs to the Pulp Project
domain. This commit update all references to the documentation to the new
location.
Close #313
`git grep readthedocs` now only shows:
```
README.rst:The `full documentation <http://pulp-smash.readthedocs.io/en/latest/>`_ is
docs/installation.rst:.. _Virtualenv: http://virtualenv.readthedocs.io/en/latest/
pulp_smash/cli.py:    .. _Plumbum: http://plumbum.readthedocs.io/en/latest/index.html
pulp_smash/cli.py:           http://plumbum.readthedocs.io/en/latest/api/commands.html#plumbum.commands.base.BaseCommand.run
pulp_smash/cli.py:        # https://plumbum.readthedocs.io/en/latest/api/commands.html#plumbum.commands.base.BaseCommand.run
```
> Update references to Pulp documentation

- pulp_smash/constants.py
* Make `PYTHON_FEED_URL` point to files generated from Pulp Fixtures,
instead of files hosted on PyPi.
* Derive `PYTHON_EGG_URL` from `PYTHON_FEED_URL`, instead of duplicating
path components.
* Drop `PYTHON_WHEEL_URL`, as it is unused.
> Update Python constants

- requirements-dev.txt
Some time back, a `<2.0` version specifier was added to flake8-quotes.
It's no longer needed, as the current version installs and behaves
correctly. See: d070f8ff3c9b7b8278663ab6954a244f69f9fdb3
> Allow the current flake8-quotes to be used

- requirements-dev.txt
flake8-quotes is incompatible with flake8 version 3. Require flake8
version 2, so that the flake8-quotes plugin may still be used. See:
* https://github.com/zheller/flake8-quotes/issues/43
* https://github.com/zheller/flake8-quotes/issues/29
> Pin flake8 version in requirements-dev.txt

- README.rst
- docs/index.rst
Pulp smash has a presence on ReadTheDocs, PyPi and GitHub. Ensure that
both the readme and `docs/index.rst` link to all three of these sites.
This ensures that readers can find all of the resources they need, no
matter which website they find themselves on, or even if they just have
the source code.
Drop the instructions for building from source. A user who wants to do
something like that is also probably adventurous enough to run the
various makefiles to see what they can do. In addition, it seems strange
to explain how to generate documentation from source, but not explain
how to generate a Python package.
> Update documentation in readme and docs/index.rst

- docs/Makefile
The `docs-html` make target uses `sphinx-build` to generate
documentation. Add the `-W` option, which turns warnings into errors.
This will help keep syntactic mistakes, like broken links and
incorrectly formatted code blocks, out of the documentation.
> Convert documentation build warnings into errors

- pulp_smash/tests/rpm/api_v2/test_no_op_publish.py
After Pulp was modified to support using docker rsync distributor as a predistributor
for docker web distributor, Pulp skips publishing for two different reasons. As the
result of this change, the task status for skipped publishes has changed. This commit
adjusts pulp-smash tests to expect the new string.
> Changes the expected message when no-op publish occurs.

- pulp_smash/tests/rpm/api_v2/test_download_policies.py
According to Pulp issue 2144, Nectar throwing tracebacks due to an
unbound method being called. As a result, tests in module
`pulp_smash.tests.rpm.api_v2.test_download_policies` fail. Skip these
tests until the issue is fixed.
Fixes https://github.com/PulpQE/pulp-smash/issues/349
See https://pulp.plan.io/issues/2144
> Skip tests failing due to Pulp issue 2144

- pulp_smash/constants.py
PulpQE/pulp-fixtures@c1fe92ab252cec73d2e3bc018524cabb51603251 updates
all of the RPMs, SRPMs and DRPMs with a new keypair. As a result, the
checksums of those files have changed.
> Update RPM_SHA256_CHECKSUM constant

- pulp_smash/tests/rpm/cli/test_sync.py
`ForceSyncTestCase` tests whether it's possible for a user to force Pulp
to perform a full sync. This feature is detailed in Pulp issue 1982. [1]
This test case should only run on Pulp 2.10.0 and above, as outlined by
that issue. Conditionally skip the test case so that this is so.
Fix #353
[1] https://pulp.plan.io/issues/1982
> Skip ForceSyncTestCase as appropriate

- pulp_smash/constants.py
The on-disk locations at which Pulp stores RPM packages have changed,
due to PulpQE/pulp-fixtures@c1fe92ab252cec73d2e3bc018524cabb51603251.
Update the RPM_ABS_PATH constant accordingly. This change fixes a
failure in
`pulp_smash.tests.rpm.api_v2.test_download_policies.FixFileCorruptionTestCase`.
> Update RPM_ABS_PATH constant

- pulp_smash/utils.py
`sudo` is not guaranteed to be present on a system, and even if it is,
there may be restrictions on its use. For example, consider this
interaction with an RHEL 7.2 system I recently laid my hands on:
$ ssh $hostname sudo -u apache pulp-manage-db
sudo: sorry, you must have a tty to run sudo
In this case, it is better to use `runuser` than `sudo`.
> Drop unnecessary usage of sudo

- pulp_smash/tests/rpm/cli/test_sync.py
Make sure to use sudo when the user is not root.
> Fix a typo on CLI test_sync

- docs/api.rst
- docs/api/pulp_smash.tests.rpm.api_v2.test_rsync_distributor.rst
- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
Implement two tests for the new RPM rsync distributor.
* `PublishTestCase` ensure that the RPM rsync distributor works in the
most basic sense. It doesn't do anything fancy like testing
fast-forward logic or perform multiple publishes.
* `PublishBeforeYumDistTestCase` ensures that publishing with the RPM
rsync distributor fails if the yum distributor hasn't yet been used
for a publish.
See: https://github.com/PulpQE/pulp-smash/issues/264
See: https://pulp.plan.io/issues/1759
> Add basic tests for the rsync rpm distributor

- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
The `runuser` command offers a `-u` option. It is used like so:
$ runuser -u alice whoami
alice
RHEL6 doesn't offer this option. Update a test accordingly.
> Make invocation of runuser compatible with RHEL6

- pulp_smash/tests/rpm/api_v2/test_export.py
- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
- pulp_smash/tests/rpm/api_v2/utils.py
The first commit refactors existing SELinux management logic. It moves the logic out of a `test*` module and into a `utils` module.
The second commit uses the just-refactored SELinux management logic to make a failing test pass.
> Refactor and expand SELinux logic

- requirements-dev.txt
Allow the current version of flake8 to be installed, instead of some
version before version 3. See:
* b5309f6bab0a99c8a5f5dba70a14a4c5fe19dd16
* https://github.com/zheller/flake8-quotes/issues/29
> Un-pin dependency on 'flake8<3'

- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
This commit adds a check for the state of SELinux in the rsynx distributor
test. On systems where SELinux is disabled, running chcon produces a non-zero
exit code.
> Fixes rsync distributor test in situations where SELinux is Disabled

- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
This new constant represents the number of RPMs available in the
repository at `RPM_FEED_URL`.
> Add constant RPM_FEED_COUNT

- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
- pulp_smash/tests/rpm/cli/test_sync.py
Expand `pulp_smash.tests.rpm.cli.test_sync.ForceSyncTestCase`.
Currently, the test case will:
1. Create and sync a repo.
2. Remove an RPM. Verify one RPM is missing.
3. Sync the repo with `--force-full true`. Verify all RPMs are present.
This test procedure shows that the second sync restores the removed RPM,
but it doesn't show that the `--force-sync true` option was the cause of
that restoration. It could be that syncs *always* restore removed RPMs.
(This would indicate a different issue with the fast-forward logic.)
Update the test so that it will:
1. Create and sync a repo.
2. Remove an RPM. Verify one RPM is missing.
3. Sync the repo. Verify one RPM is missing.
4. Sync the repo with `--force-full true`. Verify all RPMs are present.
> Expand test for pulp-admin's --force-sync option

- docs/api.rst
- docs/api/pulp_smash.tests.rpm.api_v2.test_signatures_checked_for_syncs.rst
- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_signatures_checked_for_syncs.py
- pulp_smash/tests/rpm/api_v2/test_signatures_checked_for_uploads.py
Add a new module,
`pulp_smash.tests.rpm.api_v2.test_signatures_checked_for_syncs`. This
new module verifies whether RPM repository importers configured to
perform package signature ID checks do so when packages are synced in to
repositories.
The new test cases exercise importers that:
* allow unsigned packages and specify a valid key ID.
* allow unsigned packages and specify an invalid key ID.
* allow unsigned packages and specify no key ID.
* require signed packages and specify a valid key ID.
* require signed packages and specify an invalid key ID.
* require signed packages and specify no key ID.
See: https://github.com/PulpQE/pulp-smash/issues/347
See: 7779cea52adeb009b280190fd4050c6abebdb2af
> Test key ID checks when syncing packages

- pulp_smash/tests/rpm/api_v2/test_signatures_checked_for_syncs.py
According to Pulp issue 2242, package signature ID checking is not done
when packages are synced into a repository. Skip the relevant tests.
See: https://pulp.plan.io/issues/2242
> Skip tests affected by Pulp issue 2242

- pulp_smash/tests/rpm/api_v2/test_signatures_checked_for_syncs.py
Given the following assertion:
d = {1: 2, 3: 4}
self.assertNotIn(1, d)
At least the nose and unittest2 test runners will print a message like
the following:
AssertionError: 1 unexpectedly found in {1: 2, 3: 4}
Thus, the following assertion produces an unnecessarily verbose failure
message.
d = {1: 2, 3: 4}
self.assertNotIn(1, d, d)
> Make test failure messages more succinct

- docs/api.rst
- docs/api/pulp_smash.tests.docker.api_v2.test_sync.rst
- pulp_smash/constants.py
- pulp_smash/tests/docker/api_v2/test_sync.py
- pulp_smash/tests/docker/cli/test_sync_publish.py
The first commit performs a simple refactor: it makes a private constant public. This is a useful standalone change, and it's used by the second commit.
The second commit adds tests for [Pulp issue 2230](https://pulp.plan.io/issues/2230).
> Test Pulp issue 2230

- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_signatures_checked_for_uploads.py
- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
- pulp_smash/tests/rpm/api_v2/test_upload_publish.py
- pulp_smash/tests/rpm/cli/test_upload.py
Pulp Fixtures currently has:
* signed RPMs
* signed SRPMs
* unsigned DRPMs
* unsigned RPMs
* unsigned SRPMs
Pulp Fixtures does *not* have signed DRPMs. [1] Drop the `DRPM_FEED_URL`
and `DRPM_URL` constants, and update affected tests by either:
* referencing `DRPM_UNSIGNED_FEED_URL` and `DRPM_UNSIGNED_URL`, or
* dropping the test.
When signed DRPMs are made available through Pulp Fixtures, this topic
should be revisited.
[1] https://github.com/PulpQE/pulp-fixtures/issues/25
> Drop references to nonexistent signed DRPMs

- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_download_policies.py
- pulp_smash/tests/rpm/api_v2/test_export.py
- pulp_smash/utils.py
- tests/test_utils.py
As a replacement, add a get_sha256_checksum() function. The advantage of
calculating a checksum at runtime is that some details of the fixtures
used by the tests can change between test runs. For example, an RPM
fixture might gain or lose a PGP signature.
See: https://github.com/PulpQE/pulp-fixtures/pull/28
> Drop RPM_SHA256_CHECKSUM constant

- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_signatures_checked_for_copies.py
- pulp_smash/tests/rpm/api_v2/test_signatures_checked_for_syncs.py
- pulp_smash/tests/rpm/api_v2/test_signatures_checked_for_uploads.py
- pulp_smash/tests/rpm/api_v2/test_signatures_saved_for_packages.py
Signed DRPMs are now provided by Pulp Fixtures. Update tests to make use
of signed DRPMs where appropriate.
Fix: https://github.com/PulpQE/pulp-fixtures/issues/25
> Add signed DRPMs to test suite

- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_download_policies.py
The `RPM_ABS_PATH` constant defines the absolute path to the `RPM`
content unit on the Pulp filesystem.
For this constant to hold true, the `RPM` content unit must not change.
However, it has changed at least twice during the history of Pulp
Fixtures, as signatures have been added and removed. Also, its signature
might change in the future if the public/private keypair in Pulp
Fixtures changes for some reason, and the exact path to the content unit
is supposed to be an implementation detail.
Rewrite the one test case that uses this constant to use the `find` CLI
executable instead.
> Drop constant RPM_ABS_PATH

- pulp_smash/tests/rpm/api_v2/test_download_policies.py
Among other things, `FixFileCorruptionTestCase` does the following:
1. Corrupt a content unit on disk.
2. Tell Pulp to download a repository with ``verify_all_units`` set to
false.
3. Tell Pulp to download a repository with ``verify_all_units`` set to
true.
One can make at least the following assertions about this:
1. The content unit's checksum changed as a result of step 1.
2. The content unit's checksum stayed the same as a result of step 2.
3. The content unit's checksum changed as a result of step 3.
4. The content unit's checksum is the same before step 1 and after step
3.
Add the third assertion. Revamp the test names and docstrings for the
other three steps.
> Strengthen tests in FixFileCorruptionTestCase

- pulp_smash/tests/rpm/api_v2/test_download_policies.py
According to Pulp issue 2272, background content units fail, affecting
repositories with a `background` or `on_demand` download policies. This
affects at least the following test cases:
* pulp_smash.tests.rpm.api_v2.test_download_policies.BackgroundTestCase
* pulp_smash.tests.rpm.api_v2.test_download_policies.FixFileCorruptionTestCase
Skip these test cases as appropriate.
See: https://pulp.plan.io/issues/2272
> Skip test affected by Pulp issue 2272

- pulp_smash/tests/rpm/api_v2/test_download_policies.py
All of the test cases in module
`pulp_smash.tests.rpm.api_v2.test_download_policies` are affected by
Pulp issue 2272. Skip them.
See: https://pulp.plan.io/issues/2272
> Skip tests affected by Pulp issue 2272

- requirements-dev.txt
pydocstyle 1.1.0 is not compatible with flake8.
See: https://github.com/PyCQA/pydocstyle/issues/207
> Pin dependency on pydocstyle==1.0.0

- pulp_smash/tests/rpm/cli/test_copy_units.py
Refactor module `pulp_smash.tests.rpm.cli.test_copy_units`. Aside from a
(hopeful) improvement in readability, fixture tear-down logic is more
robust.
> Refactor RPM copy test cases

- docs/api.rst
- docs/api/pulp_smash.tests.rpm.api_v2.test_mirrorlist.rst
- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_mirrorlist.py
Add module `pulp_smash.tests.rpm.api_v2.test_mirrorlist`. This module
contains test cases that exercise Pulp's support for mirrorlist feed
URLs.
Fix: https://github.com/PulpQE/pulp-smash/issues/384
> Add test cases for mirrorlists

- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
The test will sync a second time a repository that hasn't changed. Pulp must
report properly that no changes were made.
> Add test to verify no change on a second sync

- pulp_smash/tests/python/api_v2/utils.py
Pulp repositories don't have a "type" per se. However, practical
experience shows that repositories should include only a closely related
set of content types. This is reflected in repository metadata. If a
repository's type is listed in its metadata, then front-ends (like
pulp-admin) can better display repository information to users.
> Set repository type when creating Python repos

- pulp_smash/constants.py
- pulp_smash/tests/python/api_v2/test_sync_publish.py
Pulp is currently able to sync Python packages from PyPI. As of the
pulp_python plugin version 2.0, it should also be able to sync Python
packages from other Pulp systems. Update module
`pulp_smash.tests.python.api_v2.test_sync_publish` to test both of these
scenarios.
Fix: https://github.com/PulpQE/pulp-smash/issues/416
> Split Python repo sync test case in two

- pulp_smash/constants.py
Reference data generated by Pulp Fixtures instead of PyPI.
See: https://github.com/PulpQE/pulp-fixtures/pull/44
Fix: https://github.com/PulpQE/pulp-smash/issues/417
> Update constant PULP_FIXTURES_BASE_URL

- pulp_smash/constants.py
- pulp_smash/tests/platform/cli/test_content_sources.py
- pulp_smash/tests/rpm/api_v2/utils.py
Reference https://docs.pulpproject.org instead.
> Remove references to pulp.readthedocs.io

- docs/api.rst
- docs/api/pulp_smash.tests.rpm.cli.test_process_recycling.rst
- pulp_smash/tests/rpm/cli/test_process_recycling.py
Test whether Pulp's `PULP_MAX_TASKS_PER_CHILD` configuration option
works as advertised.
See: https://pulp.plan.io/issues/2172#note-21
Fix: https://github.com/PulpQE/pulp-smash/issues/427
> Test Pulp's ability to recycle processes

- pulp_smash/tests/rpm/api_v2/test_broker.py
- pulp_smash/tests/rpm/api_v2/test_download_policies.py
- pulp_smash/tests/rpm/api_v2/test_upload_publish.py
- pulp_smash/tests/rpm/utils.py
Add a new function, `check_issue_2387`, that checks whether the system
under test is affected by Pulp issue 2387. Use this function wherever
issue 2387 is referenced.
Add a check for issue 2387 into module
`pulp_smash.tests.rpm.api_v2.test_broker`. The tests in this module are
affected but not yet skipped.
See: https://pulp.plan.io/issues/2387
> Expand and clean up skips for Pulp issue 2387

- pulp_smash/tests/rpm/api_v2/test_mirrorlist.py
- pulp_smash/tests/rpm/api_v2/test_no_op_publish.py
Ensure that
``pulp_smash.tests.rpm.api_v2.test_{mirrorlist,no_op_publish}`` clean up
orphans when exiting. This ensures that later modules, namely
``pulp_smash.tests.rpm.api-v2.test_orphan_remove``, can successfully
execute.
> Improve clean-up logic in several modules

- docs/api.rst
- docs/api/pulp_smash.tests.rpm.api_v2.test_package_paths.rst
- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_package_paths.py
- pulp_smash/tests/rpm/utils.py
An RPM repository may have packages in arbitrary locations. By default,
Pulp stores packages in the root of a repository, but this need not be
so. The metadata in the ``repodata`` directory can point to RPM files
wherever they be. Add a test for this feature.
See: https://pulp.plan.io/issues/2354
See: https://github.com/PulpQE/pulp-fixtures/pull/45
> Test Pulp's handling of packages in alternate locs

- pulp_smash/tests/ostree/api_v2/test_publish.py
- pulp_smash/tests/rpm/api_v2/test_broker.py
- pulp_smash/tests/rpm/api_v2/test_comps_xml.py
- pulp_smash/tests/rpm/api_v2/test_export.py
- pulp_smash/tests/rpm/api_v2/test_force_full.py
- pulp_smash/tests/rpm/api_v2/test_mirrorlist.py
- pulp_smash/tests/rpm/api_v2/test_no_op_publish.py
- pulp_smash/tests/rpm/api_v2/test_package_paths.py
- pulp_smash/tests/rpm/api_v2/test_packages_directory.py
- pulp_smash/tests/rpm/api_v2/test_repomd.py
- pulp_smash/tests/rpm/api_v2/test_repoview.py
- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
- pulp_smash/tests/rpm/api_v2/test_unassociate.py
- pulp_smash/tests/rpm/api_v2/test_updateinfo.py
- pulp_smash/tests/rpm/api_v2/test_upload_publish.py
- pulp_smash/tests/rpm/api_v2/utils.py
- pulp_smash/utils.py
Add function `pulp_smash.utils.publish_repo`. Walk through package
`pulp_smash.tests` and replace existing code as appropriate.
Add function `pulp_smash.tests.rpm.api_v2.get_unit`. Walk through
package `pulp_smash.tests.rpm.api_v2` and replace existing code as
appropriate.
> Add and use two new utility functions

- pulp_smash/cli.py
- pulp_smash/exceptions.py
- tests/test_cli.py
Add exception `pulp_smash.exceptions.CalledProcessError`. Do this for
two reasons:
* `subprocess.CalledProcessError`, which is shipped with the standard
library, does not include stdout and stderr information in tracebacks.
This information is hugely valuable.
* It's good practice for applications to raise expected exceptions from
their own namespace, so as to provide a better abstraction from
dependencies.
> Add custom exception for failed CLI processes

- setup.py
The `setup.py` script uses function `setuptools.find_packages` to choose
which modules should be installed and which should not. By default, this
function incorrectly includes the top-level "tests" directory. Prevent
this by explicitly whitelisting the modules and packages to be included.
An even better solution is to place unit tests in a top-level "test"
directory. This is a common convention that allows unit tests to be run
on installed packages. However, the exact requirements and conventions
for doing this are unclear.
> Prevent setup.py from installing a "tests" package

- pulp_smash/tests/platform/cli/test_selinux.py
Add test case `FileLabelsTestCase` in module
`pulp_smash.tests.platform.cli.test_selinux`.
Fix: https://github.com/PulpQE/pulp-smash/issues/442
> Test SELinux filesystem labels

- pulp_smash/tests/platform/cli/test_selinux.py
Using sudo if not root use will prevent permission denied error when
trying to getfattr on /var/log/pulp.
> Use sudo when running getfattr

- pulp_smash/selectors.py
- pulp_smash/tests/rpm/api_v2/test_orphan_remove.py
Add a new method, `pulp_smash.selectors.skip_if`. This method is similar
to `@unittest.skipIf`, but more flexible: it lets one execute skipping
logic at runtime and is capable of accessing class and instance
attributes.
Why make this method available? It exists because of the structure of
the unittest module:
1. The `setUpClass` method lacks access to certain tools like the
`addCleanup` method. As a result, it is desirable to move
failure-prone code to other locations, such as test methods.
2. Some failure-prone code should control whether or not the test
methods in a test case should execute, but this is difficult to do,
because all test methods execute regardless of how many test methods
execute.
3. The `skip_if` decorator lets one move failure-prone code into a
regular test method …
> Make test case more resilient against errors

- pulp_smash/cli.py
- pulp_smash/tests/rpm/api_v2/test_broker.py
- pulp_smash/tests/rpm/cli/test_process_recycling.py
- pulp_smash/utils.py
- tests/test_cli.py
- tests/test_utils.py
The `Service` class represents a service (such as httpd) on a host. It
provides methods such as `start` and `stop`, and it abstracts away which
service manager is in use on the target host.
A drawback of the `Service` class is that it encourages serial code to
be written. If three services are to be restarted, it's easy to write
something like this:
services = (Service(cfg, name) for name in ('foo', 'bar', 'biz'))
for service in services:
service.stop()
for service in services:
service.start()
The `ServiceManager` class represents the service manager (such as
systemctl) on a host. It's used like so:
services = ('foo', 'bar', 'biz')
svc_mgr = ServiceManager(cfg)
svc_mgr.stop(services)
svc_mgr.start(services)
Depending on the service manager used by the target system, `stop` and
`start` …
> Replace Service with ServiceManager

- pulp_smash/tests/platform/cli/test_selinux.py
Module `pulp_smash.tests.platform.cli.test_selinux` contains CLI
command-building logic. Here's an example of a command that might be
built:
getfattr --recursive --name=security.selinux /var/cache/pulp
Unfortunately, if `sudo` is required, the following command is built:
sudo --recursive getfattr --name=security.selinux /var/cache/pulp
Fix this. Build the CLI command in strictly left-to-right order, in
order to ease human understanding of what's going on.
> Fix how command is built

- pulp_smash/tests/rpm/api_v2/test_orphan_remove.py
As of Pulp 2.12.0, Pulp reports how many content units were deleted when
a DELETE /pulp/api/v2/content/orphans/ API call is made. Only make
assertions about this fact when the Pulp system under test is Pulp
2.12.0 or newer.
See: https://pulp.plan.io/issues/1268
See: 0a063c063defaec4dd122974ca4f99716ab823b4
> Skip some orphan tests for older versions of Pulp

- pulp_smash/tests/rpm/api_v2/test_unassociate.py
Rewrite test cases in module
`pulp_smash.tests.rpm.api_v2.test_unassociate`. Improve them in some key
ways:
* Make test case set-up and tear-down logic more robust in the face of
failures.
* Make test method assertions more thorough, especially regarding the
``last_unit_added``, ``last_unit_removed`` and ``last_publish``
attributes.
Fix: https://github.com/PulpQE/pulp-smash/issues/461
> Rewrite test cases for RPM unit unassociation

- pulp_smash/tests/rpm/api_v2/test_remove_unit.py
- pulp_smash/tests/rpm/api_v2/test_unassociate.py
- pulp_smash/tests/rpm/api_v2/utils.py
The first commit is a simple refactor that replaces a private function with a more re-usable public function. The second commit is more substantial. It re-writes module `pulp_smash/tests/rpm/api_v2/test_remove_unit.py`, and it fixes #463.
> Expand test for removing units from a repository

- pulp_smash/tests/rpm/api_v2/utils.py
The paths to packages in published repositories have changed. In Pulp
2.11 and earlier, packages ended up in the root of published
repositories, alongside the "repodata" directory. In Pulp 2.12, packages
default to being placed elsewhere, and users have the option to
customize the exact path.
The end result of this change is that clients should consult the
`repodata/...primary.xml` file when finding packages. This commit is not
so elegant, and instead implements a stop-gap solution. This stop-gap
solution should fix many broken tests, but does not yet consult with the
XML files.
See: https://github.com/PulpQE/pulp-smash/issues/472
> Change how package paths are calculated

- pulp_smash/api.py
- pulp_smash/constants.py
- pulp_smash/exceptions.py
- pulp_smash/tests/rpm/api_v2/test_iso_crud.py
Added two commits:
1. Added `task` attr to TaskReportError to allow inspecting the failed task information
2. Added the tests to make sure Pulp will properly handle valid file feed and invalid file feed. In the latter it should fail stating all the files that were not able to find. 
Fix #482
> Add tests for ISO repos from a feed URL

- pulp_smash/tests/rpm/api_v2/test_download_policies.py
- pulp_smash/tests/rpm/api_v2/test_packages_directory.py
- pulp_smash/tests/rpm/api_v2/test_republish.py
As of Pulp 2.12, the layout of published RPM repositories has changed.
Fix several tests, so that they work with both earlier and later
versions of Pulp.
> Fix several tests that rely on package paths

- docs/about.rst
Instead of labels, use GitHub's built-in "pull request reviews" feature.
See: https://help.github.com/articles/about-pull-request-reviews/
> Do not use labels to categorize pull requests

- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
Add `SyncInvalidMetadataTestCase` to module
`pulp_smash.tests.rpm.api_v2.test_sync_publish`. This new test case
checks to see if Pulp can gracefully fail when syncing a repository with
incorrect metadata in its `repodata` directory.
Fix: https://github.com/PulpQE/pulp-smash/issues/457
See: https://pulp.plan.io/issues/1287
See: https://github.com/PulpQE/pulp-fixtures/pull/49
> Test whether Pulp can handle bad metadata

- pulp_smash/tests/rpm/api_v2/test_comps_xml.py
- pulp_smash/tests/rpm/api_v2/test_updateinfo.py
- pulp_smash/tests/rpm/api_v2/test_upload_publish.py
- pulp_smash/tests/rpm/api_v2/utils.py
Rewrite functions for dealing with the XML files in a published RPM
repository's `repodata/` directory.
> Rewrite repodata/* parsing logic

- pulp_smash/tests/rpm/cli/test_search.py
Run pulp_admin_login before creating a repository on search tests, that
will ensure the login certificates are in place and the repository can
be created.
This fixes an automation failure.
> Login before creating a repo for CLI search test

- docs/api.rst
- docs/api/pulp_smash.tests.rpm.api_v2.test_packages_directory.rst
- docs/api/pulp_smash.tests.rpm.api_v2.test_repository_layout.rst
The toctree in docs/api.rst and several other supporting files were out
of date.
See: d90fe0a6ec36a6e3c0fb5bc4aaf5ffe6b82a65a7
> Fix documentation

- pulp_smash/tests/rpm/api_v2/test_export.py
Make sure to use the new repository layout when asserting for RPMs
exported to a directory by the export distributor. Use the old layout
when testing Pulp < 2.12.
> Update export distributor package path

- pulp_smash/tests/rpm/api_v2/test_broker.py
- pulp_smash/tests/rpm/api_v2/test_download_policies.py
- pulp_smash/tests/rpm/api_v2/test_mirrorlist.py
- pulp_smash/tests/rpm/api_v2/test_package_paths.py
- pulp_smash/tests/rpm/api_v2/test_republish.py
- pulp_smash/tests/rpm/api_v2/test_upload_publish.py
- pulp_smash/tests/rpm/api_v2/utils.py
When an RPM repository is published, several XML files are placed in a
`repodata/` directory. These XML files describe various attributes of
the repository, including the relative paths to the RPM files. Make
function `pulp_smash.tests.rpm.api_v2.utils.get_unit` use these XML
files.
Fix: https://github.com/PulpQE/pulp-smash/issues/472
> Make get_unit() use repodata/*.xml

- scripts/release.sh
Pulp Smash is compatible with Python 3.4+. Given this, it seems better
to use the virtualenv feature that ships with Python 3.3+ than a
third-party package.
> Use `python3 -m venv`, not virtualenv package

- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
Module `pulp_smash.tests.rpm.api_v2.test_rsync_distributor` manages the
`pulp_manage_rsync` SELinux policy if appropriate. As part of that task,
it executes `which semanage`. On some platforms, the executable is
installed in `/sbin`, which causes the check to fail when run as a
non-root user.
Fix this check to use `sudo` if appropriate.
> Better manage pulp_manage_rsync SELinux policy

- pulp_smash/constants.py
- pulp_smash/tests/python/api_v2/test_sync_publish.py
- pulp_smash/tests/python/api_v2/utils.py
Rewrite module `pulp_smash.tests.python.api_v2.test_sync_publish`. Make
at least the following changes:
* Change which issues are queried when deciding whether or not to raise
a `SkipTest` exception, and as a consequence, increase the amount of
test code that's executed.
* Expand the tests, so that repo-to-repo syncs are performed.
* Expand the tests, so that content unit uploads are performed.
Fix: https://github.com/PulpQE/pulp-smash/issues/492
Fix: https://github.com/PulpQE/pulp-smash/issues/493
Fix: https://github.com/PulpQE/pulp-smash/issues/494
> Rewrite Python tests

- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_crud.py
The test case will ensure Pulp only published distribution files listed
on a repo's `PULP_DISTRIBUTION.xml` file which path is outside the
metadata directory. The published `PULP_DISTRIBUTION.xml` must no
include any extra file in the metadata directory from the original
repository.
Close #476
> Add PulpDistributionTestCase

- docs/api.rst
- pulp_smash/tests/docker/api_v2/test_tags.py
Ensure that Pulp is able to create and update Docker tags, also ensure
that it can't create a tag to a manifest digest from another repository
and create a tag from an invalid manifest digest.
Close #436
> Add tests for Docker tags

- pulp_smash/tests/python/api_v2/test_sync_publish.py
Tests in module `pulp_smash.tests.python.api_v2.test_sync_publish` will
already skip if the relevant Pulp issues are open. However, the
"Platform Release" field is not set on the relevant issues, meaning that
the tests will run even for very old versions of Pulp, and thus causing
unnecessary test failures. Fix this.
> Skip some Python tests unless testing Pulp 2.12+

- pulp_smash/tests/rpm/api_v2/test_crud.py
Make sure to run the command using sudo when running `cat` on Pulp
content files.
> Update CLI commands to use sudo when needed

- pulp_smash/tests/docker/api_v2/test_tags.py
- pulp_smash/tests/puppet/api_v2/test_sync_publish.py
- pulp_smash/tests/python/api_v2/test_sync_publish.py
- pulp_smash/tests/rpm/api_v2/test_remove_unit.py
- pulp_smash/tests/rpm/api_v2/test_republish.py
- pulp_smash/tests/rpm/api_v2/test_signatures_saved_for_packages.py
- pulp_smash/tests/rpm/api_v2/test_unassociate.py
- pulp_smash/tests/rpm/api_v2/test_updateinfo.py
- pulp_smash/tests/rpm/api_v2/test_upload_publish.py
- pulp_smash/tests/rpm/api_v2/utils.py
- pulp_smash/utils.py
- tests/test_utils.py
Create function `pulp_smash.utils.search_units`. Use it in place of all
similar functions and all direct API calls to path
`{repo_href}/search/units/`.
> Consolidate logic for searching for units

- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
Add `AddUnitsTestCase` to module
`pulp_smash.tests.rpm.api_v2.test_rsync_distributor`. From its
docstring:
> When executed, this test case does the following:
>
> 1. Create a yum repository with a yum and rsync distributor.
> 2. Add some content to the repository.
> 3. Publish the repository with its yum distributor.
> 4. Add additional content to the repository.
> 5. Publish the repository with its rsync distributor. This publish
>    shouldn't distribute the new content unit, as the new content unit
>    wasn't included in the most recent publish with the yum
>    distributor.
> 6. Publish the repository with its yum distributor.
> 7. Publish the repository with its rsync distributor. This publish
>    should distribute the new content unit, as the new content unit was
>    included in …
> Add rsync distributor test: AddUnitsTestCase

- pulp_smash/tests/rpm/api_v2/test_download_policies.py
Several tests in module
`pulp_smash.tests.rpm.api_v2.test_download_policies` verify that HTTP
messages from Pulp have correct headers. When these tests fail, they
don't print information about the actual contents of the headers. Fix
this.
> Make tests more verbose

- pulp_smash/tests/rpm/api_v2/test_download_policies.py
Pulp's on_demand download policy isn't working correctly.
See: https://pulp.plan.io/issues/2587
> Skip tests affected by Pulp issue 2587

- pulp_smash/tests/rpm/api_v2/test_download_policies.py
Make sure the assertion checks for the content not for the order of the
values.
> Improve assertion for download policies test

- pulp_smash/constants.py
- pulp_smash/tests/puppet/api_v2/test_duplicate_uploads.py
- pulp_smash/tests/puppet/api_v2/test_sync_publish.py
- pulp_smash/tests/puppet/cli/test_sync.py
Pulp Fixtures has grown the ability to generate a Puppet module. Make
use of this module, where possible.
The new fixtures provided by Pulp Fixtures are not comprehensive, so
there are still references to the Puppet Forge. To make this distinction
clear, and to ensure that users default to using the fixtures provided
by Puppet Fixtures when possible:
* Append ``_1`` to fixtures provided by Pulp Fixtures.
* Append ``_2`` to fixtures provided by the Puppet Forge.
> Use Puppet fixtures from Pulp Fixtures

- pulp_smash/tests/docker/cli/test_sync_publish.py
The bug is entitled:
> "blob" files are delivered with incorrect content headers
See: https://pulp.plan.io/issues/2618
> Skip test failing due to a bug in docker

- pulp_smash/tests/rpm/api_v2/test_remove_unit.py
- pulp_smash/tests/rpm/api_v2/test_republish.py
- pulp_smash/tests/rpm/api_v2/test_search.py
- pulp_smash/tests/rpm/api_v2/test_signatures_saved_for_packages.py
- pulp_smash/tests/rpm/api_v2/test_unassociate.py
- pulp_smash/tests/rpm/api_v2/test_updateinfo.py
- pulp_smash/tests/rpm/api_v2/test_upload_publish.py
- pulp_smash/tests/rpm/cli/test_copy_units.py
- pulp_smash/tests/rpm/cli/test_sync.py
- pulp_smash/tests/rpm/utils.py
The title of Pulp issue 2620 is:
> All RPM repo searches are broken
See: https://pulp.plan.io/issues/2620
> Skip tests affected by Pulp issue 2620

- docs/api.rst
- docs/api/pulp_smash.tests.rpm.api_v2.test_character_encoding.rst
- docs/api/pulp_smash.tests.rpm.cli.test_character_encoding.rst
- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_character_encoding.py
- pulp_smash/tests/rpm/cli/test_character_encoding.py
According to Pulp issue 1903, it should be possible to upload an RPM to
Pulp even when that RPM has non-utf8 metadata in its header. Add API and
CLI tests to check whether this is true.
See: https://pulp.plan.io/issues/1903
Fix: https://github.com/PulpQE/pulp-smash/issues/524
> Add tests for RPM metadata character encodings

- pulp_smash/tests/python/api_v2/test_sync_publish.py
The tests in module `pulp_smash.tests.python.api_v2.test_sync_publish`
make use of features that are introduced in Python plugin version 2.
This plugin will be added in Pulp 2.13.
Ensure that the tests in this module don't run unless Pulp 2.13 or later
is being tested.
Fix: https://github.com/PulpQE/pulp-smash/issues/588
> Only run certain Python tests when appropriate

- pulp_smash/tests/puppet/api_v2/test_sync_publish.py
- pulp_smash/tests/puppet/api_v2/utils.py
Rewrite test case `SyncValidFeedTestCase` in module
`pulp_smash.tests.puppet.api-v2.test_sync_publish`. Make at least the
following changes:
* Drop the call to function `reset_pulp`. This call worked around an
issue fixed in Pulp 2.8. We're now developing Pulp 2.13, and keeping
it in simply lengthens the test suite execution time.
* Make the test case more robust in the case of failures, by ensuring
that repositories are deleted even when unexpected failures occur.
* Drop several assertions relating to the tasks spawned during a
repository sync. These checks are already done by
`pulp_smash.api.safe_handler` and `pulp_smash.api.json_handler`.
* Add assertions to verify that the content units synced into a
repository can be downloaded. This is the most important addition.
Fix: …
> Test Puppet download HTTP headers

- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
- pulp_smash/tests/rpm/api_v2/test_upload_publish.py
Tweak several existing RPM test cases. Add assertions verifying that,
when a client downloads an RPM, that RPM is identified with a correct
content-type header.
> Test RPM download HTTP headers

- docs/api.rst
- docs/api/pulp_smash.tests.puppet.api_v2.test_install_distributor.rst
- pulp_smash/tests/puppet/api_v2/test_install_distributor.py
- pulp_smash/tests/puppet/api_v2/utils.py
Make sure the puppet_install_distributor publishes Puppet modules as
expected.
> Add API tests for puppet install distributor

- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
Pulp issue 1376 claims that, for a certain type of failed task, the
`["progress_report"]["yum_importer"]["content"]["error_details"]`
attribute should list error details. However, further discussion shows
that this is not true. The actual fix is to improve the contents of the
`["error"]["description"]` attribute.
Update the test for Pulp issue 1376 so that assertions are made about
the `["error"]["description"]` attribute.
See: https://pulp.plan.io/issues/1376
> Update test for Pulp issue 1376

- pulp_smash/tests/puppet/api_v2/test_install_distributor.py
Commit 9e435390eb467741ba16ba632b8b7b9a61b51471 updated
`InstallDistributorTestCase` by ensuring that the correct permissions
are in use when inspecting the files created by Pulp. However, that
commit removes a necessary repository publish step, and uses the
`runuser` executable incorrectly. Fix these *glaring* errors. Mea culpa.
> Un-break Puppet test case

- pulp_smash/tests/rpm/api_v2/test_broker.py
The title of Pulp issue 2613 is:
> Broker reconnect support broken
See: https://pulp.plan.io/issues/2613
> Skip test affected by Pulp issue 2613

- pulp_smash/tests/python/api_v2/test_sync_publish.py
The tests in module `pulp_smash.tests.python.api_v2.test_sync_publish`
should run when Pulp 2.13 or newer is under test.
> Run Python sync tests for Pulp 2.13+

- pulp_smash/tests/docker/cli/test_sync_publish.py
`SyncPublishV2TestCase` in module
`pulp_smash/tests/docker/cli/test_sync_publish.py` syncs and publishes a
v2 Docker repository. Unfortunately, this test case also interacts with
the pulp_docker plugin directly, instead of talking to the Crane
plug-in. As a result, the changes to pulp_docker in Pulp 2.13 break this
test case.
Updating the test case to work well with either version of Pulp is
infeasible. The changes to pulp_docker are extensive, and they're
internal anyway: clients should talk to Crane.
Skip this test case if Pulp 2.13 or newer is under test. This "fix" is a
band-aid. The test should be re-written to use Crane — and the CI jobs
should be updated to install and configure Crane!
> Skip Docker v2 tests on Pulp 2.13 (for now!)

- docs/api.rst
- docs/api/pulp_smash.tests.rpm.api_v2.test_iso_sync_publish.rst
- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_iso_sync_publish.py
- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
- pulp_smash/tests/rpm/api_v2/utils.py
The first commit refactors existing code, by pushing private code into module `pulp_smash.tests.rpm.api_v2.utils`. The second commit adds a new module, `pulp_smash.tests.rpm.api_v2.test_iso_sync_publish`. See the individual commit messages for details.
> Add ISO rsync distributor tests

- requirements-dev.txt
flake8-docstrings is incompatible with pydocstyle version 2. Pin
pydocstyle to an older version until flake8-docstrings is updated.
See: https://gitlab.com/pycqa/flake8-docstrings/issues/19
> Pin version of pydocstyle in requirements-dev.txt

- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_iso_sync_publish.py
Add `UploadIsoTestCase`. This new test case uploads an ISO file to an
ISO repository.
The test case is simple and can (should!) be expanded, but even in its
current state, it adds some much-needed coverage for a very basic use
case.
> Add an ISO upload test case

- pulp_smash/__main__.py
- pulp_smash/api.py
- pulp_smash/cli.py
- pulp_smash/config.py
- pulp_smash/tests/docker/api_v2/test_tags.py
- pulp_smash/tests/docker/cli/test_copy.py
- pulp_smash/tests/docker/cli/utils.py
- pulp_smash/tests/platform/cli/test_content_sources.py
- pulp_smash/tests/platform/cli/test_pulp_manage_db.py
- pulp_smash/tests/puppet/cli/test_sync.py
- pulp_smash/tests/rpm/api_v2/test_broker.py
- pulp_smash/tests/rpm/api_v2/test_export.py
- pulp_smash/tests/rpm/api_v2/test_mirrorlist.py
- pulp_smash/tests/rpm/api_v2/test_repository_layout.py
- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
- pulp_smash/tests/rpm/api_v2/utils.py
- pulp_smash/tests/rpm/cli/test_copy_units.py
- pulp_smash/tests/rpm/cli/test_process_recycling.py
- pulp_smash/tests/rpm/cli/test_sync.py
- pulp_smash/tests/rpm/cli/utils.py
- pulp_smash/tests/rpm/utils.py
- pulp_smash/utils.py
- tests/test_api.py
- tests/test_cli.py
- tests/test_config.py
- tests/test_utils.py
Improve the configuration in order to support clustered Pulp deployment
where multiple machines compose a Pulp system. But it still supporting
deployments where all services are running within the same machine.
The new format adopt the system with roles format where each system
(machine) have one or more roles. Each role provide information about a
given fact, for example, the api role tells Pulp Smash that the API can
be accessed on a given system. Also it helps Pulp Smash check which
systems have a Pulp service running, then Pulp Smash can access that
system and manage the service if that is needed.
> Implement new configuration file format

- pulp_smash/api.py
- pulp_smash/cli.py
- pulp_smash/tests/docker/cli/test_sync_publish.py
- pulp_smash/tests/docker/cli/utils.py
The tests in `pulp_smash/tests/docker/` talk directly to the pulp_docker
plugin. This isn't a good idea. It is assumed that clients such as
Docker will talk to the API exposed by Crane, and as a result,
pulp_docker changes more frequently and in more significant ways than is
typical for other plugins. In addition, testing pulp_docker directly
means that Pulp Smash isn't verifying the behaviour that real clients
see.
Re-write the module, so that its tests communicate with the interface
exposed by Crane, not the interface exposed by pulp_docker.
See: b470bfb59554d31aa7eb74725d1118c7ea485378
> Rewrite CLI Docker sync & publish tests

- pulp_smash/tests/docker/cli/test_sync_publish.py
- pulp_smash/tests/docker/cli/utils.py
The `repo_registry_id` setting defines a repository's name as seen by
clients such as the Docker CLI. It's traditionally a two-part name such
as `docker/busybox`, but according to `Pulp #2368`, it can contain an
arbitrary number of slashes. This test case verifies that the
`repo_registry_id` can be set to values containing varying numbers of
slashes.
Fix: https://github.com/PulpQE/pulp-smash/issues/625
See: https://pulp.plan.io/issues/2368
> Test pulp_docker's repo_repository_id option

- pulp_smash/tests/docker/cli/test_sync_publish.py
- setup.py
Add a new dependency to `setup.py`: jsonschema. This library lets one
define schemas for JSON documents, and validate that arbitrary JSON
documents abide by those schemas.
Expand `SyncPublishV2TestCase`. Let the test case make HTTP GET requests
to `/v2/{repo_id}/manifests/latest` with varying headers, and use
jsonschema to assert that the response is as described by one of the
following:
* https://docs.docker.com/registry/spec/manifest-v2-1/
* https://docs.docker.com/registry/spec/manifest-v2-2/
Fiddle with `SyncPublishV1TestCase` so that it's structured like
`SyncPublishV2TestCase`.
See: https://python-jsonschema.readthedocs.io/en/latest/
See: https://github.com/PulpQE/pulp-smash/issues/555
> Add jsonschema dependency, test docker manifests

- requirements-dev.txt
flake8-quotes version 0.10 incorrectly flags valid docstrings as being
invalid.
See: https://github.com/zheller/flake8-quotes/issues/55
> Pin flake8-quotes to an older version

- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
`PublishTwiceTestCase` verifies that the rpm rsync distributor performs
a fast-forward publish when the same content is published two or more
times. The logic used to count the number of units rsync'd to the
destination is incorrect. Fix it.
See: 0b16e140a9120af404de8dfb82820374b27c9ad4
> Fix logic error in rpm rsync distributor test case

- pulp_smash/__main__.py
- requirements-dev.txt
flake8-quotes version 0.10.1 fixes an error introduced in version 0.10.
See: dcb63a5f766ed479dc483f00f66a7723283c92bd
> Unpin flake8-quotes requirement

- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
Pulp issue 2721 describes how a race condition can arise when multiple
repositories with identical errata are synchronized at the same time.
This issue should be fixed in Pulp 2.13.1. Add a test case for this
issue.
See: https://pulp.plan.io/issues/2721
Fix: https://github.com/PulpQE/pulp-smash/issues/638
> Add test case for parallel errata synchronization

- pulp_smash/config.py
Make sure to proper list all the searched XDG compliant paths searched,
also take advantage of `BaseDirectory.load_first_config` function to get
the configuration file.
What these changes are improving:
* `load_config_paths` only returns paths that exists on the filesystem (see http://pyxdg.readthedocs.io/en/latest/_modules/xdg/BaseDirectory.html#load_config_paths). This information will not be useful when raising the exception because if no config file and config dir is present on any of the searched paths then it will print a blank list of searched path, which is not true.
* Proper list all searched paths by joining each dir in `BaseDirectory.xdg_config_dirs` with 'pulp_smash/settings.json', this will provide the full list of searched paths.
* The previous logic was doing the same that …
> Improve pulp_smash.config._get_config_file_path

- pulp_smash/tests/__init__.py
Requests recently dropped vendor packages so urllib3 is now being
installed as a dependency. Update the
`urllib3.exceptions.InsecureRequestWarning` filter to import from the
`urllib3` instead of `requests.packages.urllib3`.
> Update warning ignore filter for urllib3

- pulp_smash/pulp_smash_cli.py
Tell the user which message broker will be configured if the default of
Qpid is not chosen. (It's RabbitMQ.)
> Fiddle with `pulp-smash settings create` wording

- docs/api.rst
- docs/api/pulp_smash.tests.rpm.cli.test_retain_old_count.rst
- pulp_smash/tests/rpm/cli/test_retain_old_count.py
Add a test for pulp-admin's `--retain-old-count` flag. Specifically,
ensure that `--retain-old-count 0` works correctly. This new test
mirrors the API test in
`pulp_smash.tests.rpm.api_v2.test_retain_old_count`. Neither of these
tests verify that `--retain-old-count` works with non-zero values.
Related: https://github.com/PulpQE/pulp-smash/issues/662
See: https://pulp.plan.io/issues/2785
> Test --retain-old-count option via CLI

- pulp_smash/tests/rpm/api_v2/test_retain_old_count.py
The API test case for the `retain_old_count` feature already ensures
that the flag works correctly when set to zero. However, it doesn't
ensure that the flag works for values greater than zero. Fix this
omission.
See: https://github.com/PulpQE/pulp-smash/issues/662
See: https://pulp.plan.io/issues/2785
> Expand API test case for `retain_old_count`

- docs/installation.rst
`pyvenv` is deprecated in favor of `python -m venv`. Update the docs
accordingly.
`pip install ...` offers some advantages over `python setup.py install`.
Update the docs accordingly. See: https://stackoverflow.com/a/15731459
> Update installation document

- pulp_smash/tests/rpm/api_v2/test_download_policies.py
- pulp_smash/tests/rpm/api_v2/test_package_paths.py
- pulp_smash/tests/rpm/utils.py
Pulp issue 2798 describes how background and on demand downloads are
broken. See: https://pulp.plan.io/issues/2798
> Skip tests affected by Pulp issue 2798

- docs/api.rst
- docs/api/pulp_smash.tests.rpm.api_v2.test_content_applicability.rst
- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_content_applicability.py
Add module `pulp_smash.tests.rpm.api_v2.test_content_applicability`.
Give this module a test case that performs several variations of the
following:
1. Create a repository and consumer.
2. Bind the consumer to the repository.
3. Create a consumer profile that includes several RPMs in the
repository.
4. Regenerate applicability for the consumer.
5. Get an applicability report for the consumer, and verify that the
correct consumers and RPMs are listed in the report.
Fix: https://github.com/PulpQE/pulp-smash/issues/676
> Add content applicability test case

- pulp_smash/tests/platform/cli/test_pulp_manage_db.py
> Create test to ensure `pulp-manage-db --dry-run` has exit code 0

- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
- pulp_smash/tests/rpm/utils.py
The test continues to run when Pulp 2.13.1 systems and newer are under
test.
See: https://pulp.plan.io/issues/2844
> Skip test affected by Pulp issue 2844

- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
When executed, `PublishTwiceTestCase` will:
1. Create a yum repository with a yum and rsync distributor.
2. Add some content to the repository.
3. Publish with the yum and rsync distributor.
4. Publish with the yum and rsync distributor again.
The second publish with the rsync distributor should be a fast-forward
publish, as no new units were added to the repository between the first and
second publishes.
Update the test case. In step 2, upload two RPMs, not one. In step 3,
assert that the "unit query step" processes exactly two RPMs, instead of
some vague number greater than zero. In step 4, continue to assert that
the "unit query step" processes exactly zero RPMs.
The rsync distributor uses iterators for much of its functionality,
meaning that several steps will always state that one …
> Tweak with assertions in rsync test case

- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_content_applicability.py
- pulp_smash/tests/rpm/api_v2/test_upload_publish.py
Closes #693
Unblocks #667
I also updated two tests that hard coded in these values.
In the future, more metadata could be added.
@preethit @Ichimonji10 if either of you could give this a review I'd appreciate it!
I'm not sure about nesting some of the fields under `RPM_DATA['metadata']` and some not. I differentiated them soley based on what information actually constitutes the `RPM` name and what is additional information.
> Provide RPM name, version, etc in constants.py

- pulp_smash/tests/rpm/api_v2/test_upload_publish.py
Closes #667 
@Ichimonji10 I'm not sure about how I am "skipping" these tests. When I tried it out, calling skipTest would skip the ENTIRE test case, not just the subTest, so this seemed like a middle ground.
If you could give this a review sometime next week, that would be great.
This bug is not yet fixed, and the tests "skip" (i.e., don't execute at all) on a Pulp 2.13.2 install on a Fedora 25 machine. They fail as expected if I force the subTests to run.
Also, I'm still getting some aberrant behaviour out of my pylint. I'll try and look into it. We'll see what Travis thinks.
> Add tests for metadata on uploaded rpm packages.

- docs/api.rst
- docs/api/pulp_smash.tests.rpm.api_v2.test_service_resiliency.rst
- pulp_smash/api.py
- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_service_resiliency.py
- tests/test_api.py
Add a new module, `pulp_smash.tests.rpm.api_v2.test_service_resiliency`.
This module should contain tests that check Pulp's ability to continue
working in the face of service failures. Initially, it contains only
`MissingWorkersTestCase`. When executed, it will:
> 1. Ensure there is only one Pulp worker.
> 2. Create a repository. Let its feed reference a large repository.
>    (For example, EPEL.)
> 3. Start a sync. Immediately restart the ``pulp_workers`` service.
>    (It's important that ``pulp_workers`` be restarted, not started and
>    stopped.  For details, see `Pulp #2835`_.) This should cause the
>    first sync to abort.
> 4. Update the repository. Let its feed reference a small repository.
>    (For example, :data:`pulp_smash.constants.RPM_UNSIGNED_FEED_URL`.)
> 5. Start a …
> Test failing Pulp workers

- pulp_smash/tests/ostree/api_v2/test_sync.py
- pulp_smash/tests/puppet/api_v2/test_sync_publish.py
- pulp_smash/tests/rpm/api_v2/test_sync_publish.py
Let the newly added function `pulp_smash.api.code_handler` can replace
several calls to `requests.response.raise_for_status` throughout the
code base.
> Use `code_handler` throughout code base

- pulp_smash/tests/rpm/api_v2/test_unassociate.py
* Fix a misstatement in the docstring.
* Skip the test if the version of Pulp under test warrants it.
See: 228983d6610d3447f3d47c1f2aae9ede754b9320
> Tweak new test for last_unit_removed

- pulp_smash/tests/rpm/api_v2/test_updateinfo.py
Continues to address #693 
I ran the tests in the affected file in Fedora 25 VM with pulp 2.13.2 installed. All is well.
@Ichimonji10 I was working on another issue and noticed these hard coded values. 
I could perhaps put the 'sum' in the `constants.py` RPM_DATA metadata as well, if that seems like a good idea. Let me know what you think.
> Use RPM_DATA instead of hard coded values

- pulp_smash/tests/rpm/api_v2/test_upload_publish.py
- pulp_smash/tests/rpm/cli/test_upload.py
Includes tests in both API and CLI
Closes #585 
@Ichimonji10 
Let me know what you think.
While re-creating this issue, [Pulp issue #2871](https://pulp.plan.io/issues/2871) was discovered. The consequence of 2871 is that if a checksumtype is specified that does not match a specified checksum, no error is thrown, which is a problem. 
Another consequence seems to be that, no matter what "checksumtype" is specified, "sha256" is chosen.
I have not filed a pulp-smash issue yet because it seems there is still some debate about what the problem is -- i.e. should all references be "checksumtype" or is it valid for some to be "checksum_type".
> Add tests that specify checksumtype in drpm upload

- pulp_smash/tests/rpm/api_v2/test_rsync_distributor.py
The test for fastforward functionality falsely fails due
to a fuzzy timestamp issue in Pulp which likely won't be
fixed in Pulp 2.
> Work around a Pulp 2 defect causing false positive

- pulp_smash/constants.py
- pulp_smash/tests/ostree/api_v2/test_publish.py
- pulp_smash/tests/ostree/api_v2/test_sync.py
From now on OSTree files will be generated using pulp_fixtures scripts.
OSTree fixtures are now available. See: https://github.com/PulpQE/pulp-fixtures/pull/56
> Update OSTree constants and tests that use them.

- pulp_smash/tests/docker/cli/test_copy.py
Use `pulp_smash.constants.DOCKER_UPSTREAM_NAME` instead of a private
constant.
> Drop duplicate private constant

- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_upload_publish.py
There are at least three ways to measure the size of an RPM package:
* installed size
* archive size
* package size
The `RPM_DATA` constant already lists the installed size of an RPM. Add
another entry for the package size of an RPM.
See:
https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch-package-structure.html#id623000
> Add constant for RPM package size

- pulp_smash/constants.py
- pulp_smash/tests/docker/cli/test_sync_publish.py
The first commit renames several constants. The second commit adds a test to verify that Pulp can sync and publish a Docker repository with a manifest list.
These tests rightfully belong in `pulp_smash.tests.docker.api_v2.???`. However, this new test case inherits from `SyncPublishMixin`, and it will be easiest to move this test case and all of the other ones that also inherit from `SyncPublishMixin` at the same time. Tested against Pulp 2.14 beta 3 on F24, F25 and RHEL 7.
> Test docker manifests

- pulp_smash/constants.py
- pulp_smash/tests/docker/api_v2/test_copy.py
- pulp_smash/tests/docker/api_v2/test_sync_publish.py
There are two extremely similar Docker constants:
* `DOCKER_UPSTREAM_NAME`
* `DOCKER_UPSTREAM_NAME_MANIFEST_LIST`
Consolidate these two constants into just one: `DOCKER_UPSTREAM_NAME`.
Update the tests that depend on these constants as appropriate.
> Consolidate two Docker-related constants into one

- pulp_smash/constants.py
- pulp_smash/tests/rpm/api_v2/test_content_applicability.py
This adds a constant so future tests can use this RPM with vendor info that is present in pulp-fixtures.
> Add constant for rpm with vendor data

- pulp_smash/constants.py
Constant to a repository whose updateinfo file has an errata section.
> Add RPM_UPDATED_INFO_FEED_URL to constants.

- Makefile
Sphinx creates `docs/_build` when generating documentation. The files in
this directory can make flake8 unhappy. Make flake8 ignore this
directory.
> Don't lint generated files with flake8

- pulp_smash/utils.py
* In the utils module, `pulp_admin_login` function, it was using `'...'.format().split()`
what can produce unexpected results in case of whitespace sneaks in.
To avoid this situation the function was refactored, and the use of `.format` followed by `.split` was removed.
> Remove format string and split in the pulp_admin_login function.

- docs/api.rst
- docs/api/pulp_smash.pulp3.constants.rst
- docs/api/pulp_smash.pulp3.rst
- docs/api/pulp_smash.pulp3.tests.platform.rst
- docs/api/pulp_smash.pulp3.tests.platform.test_auth.rst
- docs/api/pulp_smash.pulp3.tests.rst
- docs/api/pulp_smash.pulp3.utils.rst
- pulp_smash/pulp3/__init__.py
- pulp_smash/pulp3/constants.py
- pulp_smash/pulp3/tests/__init__.py
- pulp_smash/pulp3/tests/platform/__init__.py
- pulp_smash/pulp3/tests/platform/test_auth.py
- pulp_smash/pulp3/utils.py
Why?
* Pulp-Smash will be used to test different versions major releases of Pulp.
Right now, there are 2 main Pulp X releases: Pulp2 and Pulp3.
* Since both releases will be tested using Pulp-Smas, it is convenient to separate tests, and files
related to a specific release. This will help address different needs, and run different test in a relative
easy manner.
* Add tests related to authentication, using `BasicAuth` and `JWT`.
* These tests will part of smoke test of Pulp3 , however there are still a lot of changes to adjust Pulp-Smash to fit all the needs of Pulp3.
> Add a new section related to Pulp3.

- docs/api.rst
- docs/api/pulp_smash.tests.platform.utils.rst
- pulp_smash/tests/docker/api_v2/test_sync_publish.py
- pulp_smash/tests/docker/utils.py
- pulp_smash/tests/ostree/utils.py
- pulp_smash/tests/platform/api_v2/test_consumer.py
- pulp_smash/tests/platform/api_v2/test_content_applicability.py
- pulp_smash/tests/platform/api_v2/test_login.py
- pulp_smash/tests/platform/api_v2/test_repository.py
- pulp_smash/tests/platform/api_v2/test_search.py
- pulp_smash/tests/platform/api_v2/test_user.py
- pulp_smash/tests/platform/cli/test_pulp_manage_db.py
- pulp_smash/tests/platform/cli/test_selinux.py
- pulp_smash/tests/platform/utils.py
- pulp_smash/tests/puppet/utils.py
- pulp_smash/tests/python/utils.py
- pulp_smash/tests/rpm/api_v2/test_service_resiliency.py
- pulp_smash/tests/rpm/cli/test_environments.py
- pulp_smash/tests/rpm/utils.py
- pulp_smash/utils.py
Update the existing `setUpModule` functions so that they cause tests to
skip if the incorrect version of Pulp is under test. Tests in
`pulp_smash.tests.pulp3` only execute when Pulp 3 is under test, and
other tests (which will eventually be moved to `pulp_smash.tests.pulp2`)
only execute when Pulp 2 is under test.
> Let tests skip based on Pulp's version

- pulp_smash/tests/pulp2/docker/api_v2/test_tags.py
- pulp_smash/tests/pulp2/platform/api_v2/test_search.py
- pulp_smash/tests/pulp2/rpm/cli/test_environments.py
- pulp_smash/utils.py
The `pulp_smash.utils.uuid4()` function is written with Python 2 in
mind. Given that Pulp Smash now requires Python 3, that
backwards-compatibility logic may be dropped. Do so.
Where appropriate, use `pulp_smash.utils.uuid4()` instead of
`uuid.uuid4()` from the standard library.
> Clean up usages of uuid4() function

- pulp_smash/config.py
- pulp_smash/pulp_smash_cli.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/test_auth.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crud_repos.py
- pulp_smash/tests/pulp3/utils.py
- tests/test_config.py
- tests/test_pulp_smash_cli.py
Expand the schema for the Pulp Smash configuration file, and allow users
to set a port number. (The config file typically lives at
`~/.config/pulp_smash/settings.json`.) By default, the port number to
use when communicating with Pulp's API is inferred. For example, if the
scheme is http, then Pulp Smash will communicate with Pulp's API on port
80. This commit makes it possible to override that behaviour. A user can
now specify a specific port number to use when communicating with Pulp's
API.
This is mainly useful for the Pulp 3 API tests. Currently, the API tests
have port number 8,000 hard-coded into them. This commit removes those
hard-coded port numbers.
> Let user specify a port number in config file

- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crud_repos.py
- pulp_smash/tests/pulp3/utils.py
Make the `get_auth` function return a cached JWT authentication object
when possible. This makes it possible to call `get_auth` with abandon,
without worrying about generating a huge number of tokens.
The cache used by the function can be easily cleared. This will likely
be useful in the future, when there is code that invalidates JWT tokens,
or that resets Pulp, or so on.
> Cache JWT authentication tokens

- pulp_smash/tests/pulp3/pulpcore/api_v3/test_auth.py
- pulp_smash/tests/pulp3/utils.py
The default authorization header used for JWT was update in Pulp3.
Instead of `JWT`, from now  on the `Bearer` will be standard one used in authorization header.
See: https://pulp.plan.io/issues/3107
> Update Authorization header used in JWT.

- pulp_smash/constants.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_upload_publish.py
There are 2 tests:
First:
1. Create a repository then upload content with **vendor information**
to this repository.
2. Assert that vendor information is present and according to the data
that was uploaded.
Second:
1. Create a repository then sync content with **vendor information**
to this repository.
2. Assert that vendor information is present and according to feed URL.
Closes: #680
> Verify vendor info in case of sync/upload of RPM. 

- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crud_repos.py
Remove the use of the word `that` twice in a row in a docstring. Besides to be grammatically correct, it can be misleading.
> Remove duplicate word in docstring.

- pulp_smash/tests/pulp3/pulpcore/api_v3/test_auth.py
Pulp3 - Add tests related to reset JWT, and invalidate secret keys.
Tests:
1. Verify whether resetting a secret key will invalidate all tokens of a certain use.
2. Verify whether deleting a user the user`s token will be invalidate as well.
See: #751
> Add tests to reset JWT.

- docs/usage.rst
Pulp2 tests were moved to its own dedicated namespce.
The reference for runnnig the example was outdated.
> Fix reference for running test example.

- pulp_smash/constants.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_upload_publish.py
Test whether one invalid RPM upload fails and produces error details.
Test:
1. Create a RPM repository.
2. Upload an invalid RPM to repository. Assert that upload fails, and that the
returned error contains a descriptive message.
3. Verify that the repository contains no RPMs.
Closes: #544
> Upload invalid RPM fails and produces error details.

- pulp_smash/constants.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_iso_crud.py
Verify how ISO repos handles changes in content already in Pulp.
Test:
1. Create and sync an ISO repository.
2. Update the repository's feed URL, and sync it. This simulates a
change in the contents of the source ISOs.
3. Assert that number of units remain the same, but the content has changed.
Closes: #784
> Verify how ISO repos handlers update in content.

- pulp_smash/constants.py
This constant isn't needed any more. See:
https://github.com/PulpQE/pulp-smash/commit/efaffb64b53867e276320c723a6cca315d3f4413
Fix: https://github.com/PulpQE/pulp-smash/issues/823
> Drop RPM_ERRATUM_URL

- pulp_smash/tests/pulp2/rpm/api_v2/utils.py
Pylint 1.8 now warns about inconsistent return statements. See:
https://pylint.readthedocs.io/en/latest/whatsnew/1.8.html
> Fix new pylint warning

- pulp_smash/tests/pulp2/rpm/api_v2/test_republish.py
The first commit just does some refactoring. The second adds a test case for [Pulp 2788](https://pulp.plan.io/issues/2788).
> Add test for Pulp 2788

- pulp_smash/api.py
- tests/test_api.py
Pulp3 task system still under development, but to be able to use the
current available reponse_handlers - mainly _handle_202 of API client,
few adjustments were created.
Adjusted functions: _check_tasks, _handle_202, poll_spawned_tasks and
poll_task.
Add test coverage to verify behaviour change in json_handler. Now
json_handler will treat in a different manner responses that status code
is equal to 204.
According to `HTTP/1.1 RFC 7231, Section 6.3.5`, 204 (No Content) status
code indicates that the server has sucessfully fullfiled the request and
that there is no additional content to send in response payload body.
See: #795
> Adapt task system to accept Pulp3 task system.

- pulp_smash/tests/pulp2/rpm/api_v2/test_republish.py
`RemoveOldRepodataTestCase` executes several commands that require root
permissions. Prepend "sudo" to these commands when they're executed as a
non-root user.
See: fe6de191d6ea06b5f22cb96e0a07d136fb0a277c
> Prepend "sudo" to shell commands as needed

- pulp_smash/tests/pulp3/pulpcore/api_v3/test_auth.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crud_repos.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crud_users.py
Refactor of Pulp3 tests to use the new version of `json_handler`, when
using API Client.
Remove the `sleep` function that was introduced to wait for asyncronous
calls to return.
See: #795
> Update Pulp3 tests to use new json_handler.

- docs/api.rst
- docs/api/pulp_smash.tests.pulp3.file.api_v3.test_crud_publishers.rst
- pulp_smash/tests/pulp3/constants.py
- pulp_smash/tests/pulp3/file/api_v3/test_crud_publishers.py
- pulp_smash/tests/pulp3/file/api_v3/utils.py
In order to CRUD publishers, a repository has to be created first.
Besides that, to run these newly added tests `file-plugin` has to be
installed.
See: #753
> Add tests to CRUD Publishers.

- .travis.yml
This should have the effect of speeding up builds. See:
* https://docs.travis-ci.com/user/customizing-the-build/
* https://docs.travis-ci.com/user/caching
> Cache Python wheels between Travis CI builds

- pulp_smash/tests/pulp2/rpm/api_v2/test_mirrorlist.py
Issue title:
> Pulp can't sync from mirrorlists
See: https://pulp.plan.io/issues/3310
> Skip tests affected by Pulp issue 3310

- pulp_smash/tests/pulp2/rpm/api_v2/test_iso_sync_publish.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_rsync_distributor.py
Issue title:
> rsync distributor broken on Fedora 27 due to SELinux denials
See: https://pulp.plan.io/issues/3313
> Skip tests affected by Pulp issue 3313

- pulp_smash/api.py
Add a link to `code_handler` as one of the `response_handlers` shipped
with Pulp-Smash.
> Add a link to code_handlers to the API docstring.

- pulp_smash/tests/pulp3/file/api_v3/test_sync.py
Update the description of docstring to sync mode, instead of download
policy in the docstring of `SyncFileRepoTestCase`.
> Fix description in docstring about sync mode. 

- pulp_smash/api.py
Poll asynchronous tasks every two seconds, instead of every five
seconds. Many of the asynchronous tasks that Pulp executes complete
within just a few polling cycles, such as five, ten or fifteen seconds.
As a result, the long (five second) polling periods mean that a
significant amount of Pulp Smash's time is spent waiting for tasks to
complete. Increasing the polling rate should reduce the amount of time
spent waiting by a significant amount.
> Poll asynchronous tasks more frequently

- pulp_smash/tests/pulp3/file/api_v3/test_sync.py
- pulp_smash/tests/pulp3/file/api_v3/utils.py
The deferred download policies (background, on_demand) aren't supported
by the file plugin importers at this time. Prevent the `gen_importer`
function from returning those download policies.
See: https://pulp.plan.io/issues/3320
> Restrict download policies for file repo importers

- pulp_smash/tests/pulp2/puppet/api_v2/test_install_distributor.py
- pulp_smash/tests/pulp2/rpm/api_v2/utils.py
In Fedora 26 and earlier, and on RHEL 7:
* `semanage` sets the default and current state of an SELinux policy.
* `setsebool` sets the current state of an SELinux policy.
In Fedora 27:
* `semanage` sets the default state of an SELinux policy.
* `setsebool` sets the current state of an SELinux policy.
This change in behaviour breaks tests that use `semanage` to modify the
current state of SELinux policies. Switch to using `setsebool`.
See: https://pulp.plan.io/issues/3347
> Change how booleans are set

- pulp_smash/tests/pulp3/file/api_v3/test_crud_importers.py
- pulp_smash/tests/pulp3/file/api_v3/test_crud_publishers.py
- pulp_smash/tests/pulp3/file/api_v3/test_sync.py
- pulp_smash/tests/pulp3/file/api_v3/utils.py
- pulp_smash/tests/pulp3/utils.py
Pulp3 is under active development, and many changes were added to
endpoints, and mandatory fields.
FK `repository` was removed from importers and publishers.
See: https://pulp.plan.io/issues/3341
Besides that, an importer can be associate with multiples repositories.
At the moment of sync the `href` to repository to be synced has to
informed.
See: https://pulp.plan.io/issues/3351
> Fix tests Pulp3 repo field importers, publishers and sync. 

- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crud_repos.py
Modify assertions performed on filtered repositories to be more generic.
It will comply with the same style of assertions used in equivalent test
scenarios.
> Modify assertions in filter tests for repositories.

- docs/api.rst
- docs/api/pulp_smash.tests.pulp3.pulpcore.api_v3.test_crud_distributions.rst
- pulp_smash/tests/pulp3/constants.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crud_distributions.py
- pulp_smash/tests/pulp3/pulpcore/utils.py
Add tests to CRUD distributions. A distribution is not associated within
a plugin, then the related tests were added as part of `pulp_core`.
See: #776
> Add tests to CRUD distributions.

- pulp_smash/tests/pulp3/constants.py
According to the issue https://pulp.plan.io/issues/3336 an exception
will be raised if a user tries to create/update an importer with
`additive` sync policy.
Then the `additive` mode was removed from the constant
`IMPORTER_SYNC_MODE`.
> Update constant sync modes for importers. 

- pulp_smash/pulp_smash_cli.py
- pulp_smash/tests/pulp3/file/api_v3/test_crd_publications.py
- pulp_smash/tests/pulp3/file/api_v3/test_crud_importers.py
- pulp_smash/tests/pulp3/file/api_v3/test_crud_publishers.py
- pulp_smash/tests/pulp3/file/api_v3/test_sync.py
- pulp_smash/tests/pulp3/file/api_v3/test_unlinking_repo.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/test_auth.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crud_distributions.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crud_repos.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crud_users.py
- pulp_smash/utils.py
- tests/test_pulp_smash_cli.py
This command prints the dotted name of each smoke test in Pulp Smash.
Sample usage:
python -m unittest $(pulp-smash smoke-tests)
> Add `pulp-smash smoke-tests` CLI command

- .github/ISSUE_TEMPLATE.md
In order to create a standard, and make easy to a new contributor file
an issue it was included a template with the the basics steps in how to
file a pulp-smash issue.
It was added a dir `.github` to the root system of the project, thus
avoiding to add extra files to the root system of smash.
Futures templates can be added to the same dir as well.
> Add a template for Pulp-Smash issues.

- docs/api.rst
- docs/api/pulp_smash.tests.pulp3.file.api_v3.test_repo_version.rst
- pulp_smash/tests/pulp3/constants.py
- pulp_smash/tests/pulp3/file/api_v3/test_repo_version.py
1. Add content to Pulp - using sync to a first repository.
2. Create a second repository.
3. Use ``add_content_units`` to pass an url for a unit to be added to second repository.
4. Assert that the repository version has changed for the second repository.
5. Assert that there is just one content unit in the second repository.
6. Remove the just added unit from the second repository using the ``remove_content_units``, and assert that the repository version has changed.
7. Assert that there are no content units present in the second repository.
Closes: #867
> Verify new repo version adding or removing units.

- pulp_smash/tests/pulp3/pulpcore/utils.py
This reverts commit 9bc6e8e7a3d01fee2ba68f8ecc5f35389197ec1a.
When a distribution has a trailing slash on its base path, files can't
be downloaded. This may be a bug.
> Revert Modify function gen_distribution for Pulp3.

- docs/api.rst
- docs/api/pulp_smash.tests.pulp3.file.api_v3.test_download_content.rst
- pulp_smash/tests/pulp3/file/api_v3/test_download_content.py
- pulp_smash/tests/pulp3/utils.py
1. Create, populate, publish, and distribute a repository.
2. Select a random content unit in the distribution.
3. For the schemes "http" and "https":
* If the distribution has enabled that scheme, then download the content unit from Pulp, and verify that the content unit has the same checksum when fetched directly from Pulp-Fixtures.
* If the distribution hasn't enabled that scheme, then verify that download requests fail.
Closes: #872
> Add test to download content served by Pulp.

- pulp_smash/tests/pulp3/pulpcore/utils.py
The canonical format for the `base_path` distributor option is unknown.
This is problematic, because the `gen_distribution` function generates a
`base_path`, meaning that the `gen_distribution` function might be
returning malformed values.
Pulp issue 3412 asks for clarification on the correct format of
`base_path`. If Pulp issue 3412 is resolved, then `gen_distribution`
should be updated to match.
See: https://pulp.plan.io/issues/3412
Fix: https://github.com/PulpQE/pulp-smash/issues/888
> Warn if gen_distribution function is out of date

- docs/api.rst
- docs/api/pulp_smash.tests.pulp3.file.api_v3.test_crd_artifacts.rst
- pulp_smash/tests/pulp3/constants.py
- pulp_smash/tests/pulp3/file/api_v3/test_crd_artifacts.py
- pulp_smash/tests/pulp3/utils.py
As of this writing, pulp3 does not handle upload of duplicate files.
Due that, there is a need to clean the artifacts present in pulp3, before
attempt to upload a new file to pulp3.
However, if a file exists as content unit and as artifact, the file has
to be deleted first as a content unit then as an artifact.
To solve this issue, 2 new functions were added to pulp3/utils.
- `clean_content_units()`
- `clean_artifacts()`
Add tests to CRD artifacts.
1. Create an artifact by uploading a file to pulp3.
2. Reads an artifact by its href.
3. Delete an artifact.
Closes: #726
> Add tests for CRD artifacts.

- pulp_smash/tests/pulp3/utils.py
Pulp3 allows mutliple repository versions. Adjust function
`read_repo_content` to reflect this.
Add the paramter `version` to the function `read_repo_content` thus
allowing read the content of a specific repository version. If `version`
is None, the latest repo version will be read.
This change will help future tests that require read content from the
same repo, but from different versions.
> Re-factor read_repo_content.

- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crud_repos.py
Expand CRUD repo tests to ensure that repository name is displayed as an
attribute when listing repositories with `/api/v3/repositories/`
There is already a test in place to filter single repository by its
name. Thus closing the second item mentioned in the issue.
Closes: #727
> Ensure repo name is displayed when listing repos.

- docs/api.rst
- docs/api/pulp_smash.tests.pulp3.file.api_v3.test_crud_content_unit.rst
- pulp_smash/tests/pulp3/file/api_v3/test_crud_content_unit.py
In order to create a content unit at least one artifact has to exist in
Pulp3, then metadata related to this artifact will be used to create a content
unit.
An artifact is just data on disk, a content unit is an entry in a
database that points to an artifact and gives it a name.
Closes:#870
> Add tests to CRUD content unit.

- pulp_smash/tests/pulp3/utils.py
Pulp3 will allow the user to specify what repository version should be
published.
See: https://pulp.plan.io/issues/3324
Add the version parameter to the function `publish_repo`. The body of
request will contain `repository` or `repository_version`, based on
version parameter being provided or not.
> Update publish_repo function.

- docs/api.rst
- docs/api/pulp_smash.tests.pulp2.docker.api_v2.test_upload.rst
- pulp_smash/tests/pulp2/docker/api_v2/test_sync_publish.py
- pulp_smash/tests/pulp2/docker/api_v2/test_upload.py
- pulp_smash/tests/pulp2/docker/api_v2/utils.py
- pulp_smash/tests/pulp2/docker/utils.py
Move `SyncPublishMixin` to docker/api_v2/utils. This class will be used
as a helper to existent tests, and for new ones. This change is
necessary to avoid DRY.
Refactor and rename existent tests to reflect the previous change.
Create a helper function `write_manifest_list` on docker/utils.
1. Create, sync and publish a repository.
2. Read the manifest list,and remove one of the existent architectures
from it.
3. From the modified manifest list create a new JSON valid on a
temporary dir on disk.
4. Upload the just created JSON file to the repository.
5. Assert that the number of `docker_manifest_list` present on the
repository has increased.
Closes: #829
> Test upload of a manifest list V2 without a sync.

- pulp_smash/tests/pulp3/file/api_v3/test_crud_content_unit.py
Test whether content unit used by a repo version can be deleted.
1. Sync content to a repository.
2. Attempt to delete a content unit present in a repository version. Assert that a HTTP exception was raised.
3. Assert that number of content units present on the repository does not change after the attempt to delete one content unit.
Closes: #900
> Add test to delete content unit used by a repo version.

- docs/api.rst
- docs/api/pulp_smash.tests.pulp3.file.api_v3.test_publish.rst
- pulp_smash/tests/pulp3/file/api_v3/test_publish.py
- pulp_smash/tests/pulp3/utils.py
Add function get_repo_versions to `pulp3/utils`.
Rename variable in `publish_repo`.
1. Create a repository with at least 2 repository versions.
2. Create a publication by supplying the latest `repository_version`.
3. Assert that the publication `repository_version` attribute points to the latest repository version.
4. Create a publication by supplying the non-latest `repository_version`.
5. Assert that the publication `repository_version` attribute points to the supplied repository version.
6. Assert that an exception is raised when providing two different repository versions to be published at same time.
Closes: #897
> Add test to verify publish of any repo version.

- pulp_smash/tests/pulp3/file/utils.py
- pulp_smash/tests/pulp3/utils.py
The current version of Pulp 3 status page /api/v3/status is returning the plugins
installed.
For example:
```json
"versions": [
{
"component": "pulpcore",
"version": "3.0.0a1"
},
{
"component": "pulp_file",
"version": "0.0.1a1"
}
]
```
Adjust the get_plugins function to make use of this feature.
> Update get_plugins function.

- docs/api.rst
- docs/api/pulp_smash.tests.pulp3.pulpcore.api_v3.test_status.rst
- pulp_smash/tests/pulp3/pulpcore/api_v3/test_status.py
Add basic test coverage to ``api/v3/status``.
Verify whether un-authenitcated user can view the status page.
Verify whether few parameters are present on the status page.
Verify whether an HTTP exception is raised. When using a not allowed
method.
Closes: #755
> Add tests to status page.

- pulp_smash/tests/pulp3/constants.py
- pulp_smash/tests/pulp3/file/api_v3/test_crd_artifacts.py
- pulp_smash/tests/pulp3/file/api_v3/test_crud_content_unit.py
- pulp_smash/tests/pulp3/utils.py
In order to avoid a race condition it was removed the feature to remove
content units.
See: https://pulp.plan.io/issues/3445
A new endpoint was added `/api/v3/orphans/` and using the
DELETE method and this endpoint all orphan content units will be
removed. This endpoint also removes orphan artifact units.
Adjust pulp-smash to this new scenario.
Remove:
* clean_content_units
* clean_artifacts
Add:
* delete_orphan_units
Closes:#926
Related:#914
> Remove delete content units.

- docs/api/pulp_smash.tests.pulp3.file.api_v3.test_crud_importers.rst
- docs/api/pulp_smash.tests.pulp3.file.api_v3.test_crud_remotes.rst
Importers were renamed to remotes.
Adjust documentation to this change.
See: f93f19a2106d22292639ddabfe191c265cb259bd
> Remove documentation related to importers.

- pulp_smash/tests/pulp3/file/api_v3/test_crd_publications.py
- pulp_smash/tests/pulp3/utils.py
Modify function `publish_repo` to issue a warning in case of number of
spawned tasks are different than one.
Adjust the `test_crd_publications` to use the `publish_repo` helper
function.
Closes:#925
Related:#795
> Notify when Pulp 3 returns multiples tasks.

- docs/api.rst
- docs/api/pulp_smash.tests.pulp3.file.api_v3.test_crd_artifacts.rst
- docs/api/pulp_smash.tests.pulp3.pulpcore.api_v3.test_crd_artifacts.rst
- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crd_artifacts.py
Artifacts are a pulpcore feature. Move `test_crd_artifacts` from
`pulp_smash.tests.pulp3.file.api_v3` to
`pulp_smash.tests.pulp3.pulpcore.api_v3`.
Fix: https://github.com/PulpQE/pulp-smash/issues/934
> Move test_crd_artifacts to pulpcore

- pulp_smash/tests/pulp3/file/api_v3/test_sync.py
1. Create a repository, and a remote.
2. Update the remote to point to a different url.
3. Immediately run a sync. The sync should fire after the update and
sync from the second url.
4. Assert that remote url was updated.
5. Assert that the number of units present in the repository is
according to the updated url.
Closes:#879
> Add test to verify multi-resource locking.

- docs/api.rst
- docs/api/pulp_smash.tests.pulp3.file.api_v3.test_orphans.rst
- pulp_smash/tests/pulp3/file/api_v3/test_orphans.py
Add tests to verify whether orphan files can be clean up.
Add new tests.
First:
1. Create, and sync a repo.
2. Remove a content unit from the repo. This will create a second
repository version, and create an orphan content unit.
3. Assert that content unit that was removed from the repo and its
artifact are present on disk.
4. Delete orphans.
5. Assert that the orphan content unit was cleaned up, and its artifact
is not present on disk.
Second:
1. Test whether orphan content units can be clean up. Verify whether
the file is present on disk, after orphans clean up.
See: https://pulp.plan.io/issues/3442
Closes:#914
> Add tests to clean up orphan files.

- Makefile
This ignore was added some time back to work around an issue with
flake8-docstrings, and it has subsequently been fixed.
See: 76dfc72a0ef0dbfc2b6c55507614b2c3bb3e3c29
> Don't ignore flake8 warning D203

- pulp_smash/tests/pulp3/file/api_v3/test_repo_version.py
Importers were rename to remotes. Adjust variable name to reflect this
change.
See: https://pulp.plan.io/issues/3488
> Update variable name from importer to remote.

- pulp_smash/api.py
In Pulp 3, async endpoints will always return a single task. For more info see https://pulp.plan.io/issues/3166.
Requires https://github.com/pulp/pulp/pull/3442
> Handle single task responses for Pulp 3

- pulp_smash/tests/pulp3/pulpcore/api_v3/test_status.py
Assure that test to verify access to status page is executed as
un-authenticated user.
See:#755
> Remove authentication from client status tests.

- docs/api.rst
- docs/api/pulp_smash.tests.pulp3.pulpcore.api_v3.test_workers.rst
- pulp_smash/tests/pulp3/constants.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/test_workers.py
Add basic test coverage to the `workers` endpoint.
Add tests to verify filters, and invalid HTTP method.
Closes:#945
> Add tests to workers.

- pulp_smash/tests/pulp3/file/api_v3/test_sync.py
- pulp_smash/tests/pulp3/file/api_v3/utils.py
https://github.com/pulp/pulp/pull/3450
These settings were removed from the Remote in pulpcore:
https://pulp.plan.io/issues/3492
Going forward, these settings will be passed as parameters to the
plugins. Currently however, the file plugin does not make use of either
of them, so we have removed the fields from sync calls altogether.
> Remove sync_mode and download_policy from Remote

- pulp_smash/tests/pulp3/pulpcore/api_v3/test_workers.py
Use a single variable for conceptually identical test code, and flatten
test logic.
See: 8c948e996fd8a6e61cd84e18a7f1cb945603a7e1
> Consolidate and flatten test logic

- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crud_distributions.py
Refactor test case `test_02_read_distributions` to accept query
parameters. Add `base_path` as a filter.
These tests were created using the MVP, and the auto generated API
documentation as technical reference.
See:#776
> Expand test case for read distributions.

- pulp_smash/tests/pulp3/file/api_v3/test_orphans.py
See: 1e9c99d898c4a429b35f6fe6c9df771e1c980510
> Drop extraneous `noqa` directive

- pulp_smash/tests/pulp3/file/api_v3/test_download_content.py
- pulp_smash/tests/pulp3/file/api_v3/utils.py
- pulp_smash/tests/pulp3/utils.py
`pulp_smash.tests.pulp3.utils.get_content_unit_paths` only works for
file repositories. Move it into
`pulp_smash.tests.pulp3.file.api_v3.utils`.
Fix: https://github.com/PulpQE/pulp-smash/issues/979
> Move a function to a more appropriate location

- pulp_smash/tests/pulp3/file/api_v3/test_crud_remotes.py
Add test to verify whether is possible to create a remote without
provide a url parameter.
Closes:#984
> Add test to create remote without url.

- pulp_smash/tests/pulp2/platform/api_v2/test_content_applicability.py
What's the point in having a loop hard-coded to a single element?
> Unroll a one-item loop

- pulp_smash/tests/pulp3/file/api_v3/test_crd_publications.py
- pulp_smash/tests/pulp3/file/api_v3/test_crud_content_unit.py
- pulp_smash/tests/pulp3/file/api_v3/test_download_content.py
- pulp_smash/tests/pulp3/file/api_v3/test_orphans.py
- pulp_smash/tests/pulp3/file/api_v3/test_publish.py
- pulp_smash/tests/pulp3/file/api_v3/test_repo_version.py
- pulp_smash/tests/pulp3/file/api_v3/test_sync.py
- pulp_smash/tests/pulp3/file/api_v3/test_unlinking_repo.py
- pulp_smash/tests/pulp3/utils.py
Few functions had the repo in their names. Simplify their names,
removing the word repo from it.
Rename the following functions:
1. `get_repo_versions` = `get_version_hrefs`
2. `sync_repo` = `sync`
3. `publish_repo` = `publish`
4. `delete_repo_version` = `delete_version`
Update the logic for `get_version_hrefs`.
Closes:#990
> Rename functions of utils pulp3.

- pulp_smash/tests/pulp3/file/api_v3/test_download_content.py
Distributions no longer have the attributes `http` and `https`. Update
dosctring on class `DownloadContentTestCase` to be according to this.
See: https://pulp.plan.io/issues/3413
> Update docstring class DownloadContentTestCase.

- pulp_smash/tests/pulp3/file/api_v3/test_orphans.py
- pulp_smash/tests/pulp3/file/api_v3/test_publish.py
- pulp_smash/tests/pulp3/file/api_v3/test_repo_version.py
- pulp_smash/tests/pulp3/utils.py
High-level general-purpose utilities are most useful when they return
complete or near-complete responses from Pulp, instead of attributes
extracted from Pulp's responses. The `get_version_hrefs` function
violates this design principle: it fetches the versions of a repository,
and then returns just the hrefs of each version.
Drop this function in favor of a `get_versions` function, which returns
the complete list of repository versions returned by Pulp. This lets the
function be used in more places, such as in the `get_repo_versions_attr`
function.
In addition, let the revamped function accept a `params` argument, which
can be used to filter which repositories Pulp returns. This lets it
replace the `filter_repo_version` function.
> Replace get_version_hrefs() with get_versions()

- docs/api.rst
- docs/api/pulp_smash.tests.pulp3.file.api_v3.test_auto_distribution.rst
- pulp_smash/tests/pulp3/file/api_v3/test_auto_distribution.py
1. Create a repository that has at least one repository version.
2. Create a publisher.
3. Create a distribution and set the repository and publishera to
the previous created ones.
4. Create a publication using the latest repository version.
5. Assert that the previous distribution has a  ``publication`` set as
the one created in step 4.
6. Create a new repository version by adding content to the repository.
7. Create another publication using the just created repository version.
8. Assert that distribution now has the ``publication`` set to the
publication created in the step 7.
9. Verify that content added in the step 7 is now available to
download from distribution, and verify that the content unit has the
same checksum when fetched directly from Pulp-Fixtures. …
> Add test for auto distribution of a repository.

- pulp_smash/tests/pulp3/file/api_v3/test_auto_distribution.py
- pulp_smash/tests/pulp3/file/api_v3/test_crd_publications.py
- pulp_smash/tests/pulp3/file/api_v3/test_crud_content_unit.py
- pulp_smash/tests/pulp3/file/api_v3/test_crud_remotes.py
- pulp_smash/tests/pulp3/file/api_v3/test_download_content.py
- pulp_smash/tests/pulp3/file/api_v3/test_orphans.py
- pulp_smash/tests/pulp3/file/api_v3/test_publish.py
- pulp_smash/tests/pulp3/file/api_v3/test_repo_version.py
- pulp_smash/tests/pulp3/file/api_v3/test_sync.py
- pulp_smash/tests/pulp3/file/api_v3/test_unlinking_repo.py
- pulp_smash/tests/pulp3/file/api_v3/utils.py
- pulp_smash/tests/pulp3/file/utils.py
- pulp_smash/tests/pulp3/utils.py
This function syncs file content into Pulp, then deletes the repository
and remote and repository used for the task. In a fresh Pulp 3 system,
the result is that orphaned file contents will be present.
Within Pulp Smash, modules may import from siblings or parents, but not
children. This helps to prevent circular imports. Unfortunately,
populate_pulp() imports gen_remote() from a child module. Move
gen_remote() up the namespace hierarchy.
> Add populate_pulp()

- pulp_smash/tests/pulp3/file/api_v3/test_auto_distribution.py
- pulp_smash/tests/pulp3/file/api_v3/test_crd_publications.py
- pulp_smash/tests/pulp3/file/api_v3/test_crud_content_unit.py
- pulp_smash/tests/pulp3/file/api_v3/test_crud_publishers.py
- pulp_smash/tests/pulp3/file/api_v3/test_crud_remotes.py
- pulp_smash/tests/pulp3/file/api_v3/test_download_content.py
- pulp_smash/tests/pulp3/file/api_v3/test_orphans.py
- pulp_smash/tests/pulp3/file/api_v3/test_publish.py
- pulp_smash/tests/pulp3/file/api_v3/test_repo_version.py
- pulp_smash/tests/pulp3/file/api_v3/test_sync.py
- pulp_smash/tests/pulp3/file/api_v3/test_unlinking_repo.py
- pulp_smash/tests/pulp3/file/utils.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crud_distributions.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/test_crud_repos.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/test_tasks.py
- pulp_smash/tests/pulp3/pulpcore/utils.py
- pulp_smash/tests/pulp3/utils.py
Move gen_distribution() and gen_repo() up the namespace hierarchy. This
lets tests for different plugins avoid importing from each other. In
this particular case, file plugin tests no longer need to import from
the pulp core tests. This is especially useful if plugins are going to
be pulled out of Pulp Smash and pushed into individual plugins.
> Move functions higher up namespace

- pulp_smash/api.py
- pulp_smash/cli.py
- pulp_smash/tests/pulp2/docker/cli/utils.py
- pulp_smash/tests/pulp2/ostree/api_v2/test_sync.py
- pulp_smash/tests/pulp2/puppet/cli/test_sync.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_comps_xml.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_download_policies.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_export.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_repository_layout.py
- pulp_smash/tests/pulp2/rpm/cli/utils.py
- pulp_smash/utils.py
- tests/test_api.py
- tests/test_utils.py
Both `server_config` and `cfg` are used to reference the same type of
object in various places throughout the code base. There's no good
reason to use two names. Settle on one.
Given the high likelihood that Pulp Smash will become a full-fledged
framework in the near future, now seems like a good time to make a push
for having the best interfaces possible.
> Rename server_config to cfg

- pulp_smash/tests/pulp3/pulpcore/api_v3/test_status.py
The attribute name in the status API changed when RQ with Redis replaced
AMQP brokers like RabbitMQ.
This PR is meant to be used with these core and pulp_file PRs:
https://github.com/pulp/pulp/pull/3454
https://github.com/pulp/pulp_file/pull/72
> Switch status API to RQ

- docs/usage.rst
- pulp_smash/api.py
- pulp_smash/cli.py
- pulp_smash/config.py
- pulp_smash/pulp_smash_cli.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_errata.py
- pulp_smash/tests/pulp2/rpm/cli/test_copy_units.py
- pulp_smash/tests/pulp3/file/api_v3/test_auto_distribution.py
- pulp_smash/tests/pulp3/file/api_v3/test_download_content.py
- pulp_smash/utils.py
- tests/test_api.py
- tests/test_cli.py
- tests/test_config.py
- tests/test_pulp_smash_cli.py
- tests/test_utils.py
The configuration file lets one declare information about a Pulp
application and the computers that it's deployed on. A good name to use
for these computers is "hosts." Consider a definition from Wiktionary:
> Any computer attached to a network.
However, the configuration file calls these hosts "systems." Consider a
definition from Wiktionary:
> The set of hardware and software operating in a computer.
"host" seems more appropriate than "system" for several reasons. First,
it makes more semantic sense to talk about computers than to talk about
the hardware and software in a computer. Second, Pulp makes services
available to a network, even if just the local network. If no network is
available, then Pulp can't function. It seems appropriate to use
terminology which reflects this focus. …
> Rename "systems" to "hosts" in config file

- pulp_smash/tests/pulp2/python/api_v2/test_duplicate_uploads.py
It's unclear whether a 'filename' is required when uploading an egg to
Python. The de-facto standard appears to be that one is required. Make
the affected Python tests use one.
See: https://pulp.plan.io/issues/2334
> Fix failing Python test

- pulp_smash/config.py
Let all application-wide parameters occur before per-host parameters. As
a bonus, this ordering is the same as is shown in documentation.
> Re-order PulpSmashConfig.__init__ parameters

- pulp_smash/tests/pulp2/python/api_v2/test_duplicate_uploads.py
The Python `DuplicateUploadsTestCase` is affected by Pulp issue 2334.
Rather than skipping the test case outright, and rather than hard-coding
a work-around into Pulp Smash, let the test case conditionally adapt to
the bug.
See: https://pulp.plan.io/issues/2334
See: 84f088d825746f4723e1d8e29be9486c2e75fe58
> Handle Pulp issue 2334 more gracefully

- pulp_smash/api.py
- pulp_smash/cli.py
- pulp_smash/config.py
- pulp_smash/pulp_smash_cli.py
- tests/test_api.py
- tests/test_cli.py
- tests/test_config.py
- tests/test_pulp_smash_cli.py
- tests/test_utils.py
The `PulpSmashConfig` object has a weird constructor: all arguments are
optional. As a result, it's excessively easy to create a new object that
has an invalid state. For example, this will raise an exception, as
necessary information is not available:
config.PulpSmashConfig().get_base_url()
From a design perspective, this is bad. No amount of linting can help
discover improperly written code when the underlying code doesn't even
define constructor parameters as required.
Why is this done? Because certain methods, like `read`, are instance
methods. This code needs to work:
config.PulpSmashConfig().read()
What's to be done? The obvious solution is to change methods which don't
require instance data from instance to class or static methods. This
makes it possible to define constructor …
> Revamp PulpSmashConfig object

- pulp_smash/config.py
The PulpSmashConfig constructor may gain additional arguments in the
future. For example, it might gain a `pulp_fips_enabled` argument,
stating whether FIPS tests should be enabled. If this occurs, it would
be ideal if this argument could be added after the other `pulp_*`
arguments, all of which define system-wide information, and before the
`hosts` argument, which defines per-host information. This can only
seamlessly occur if all users of the `PulpSmashConfig` object pass the
final `hosts` argument as a keyword argument, instead of as a positional
argument.
Make the final `hosts` argument to the `PulpSmashConfig` constructor
keyword-only.
> Make final argument to PulpSmashConfig kwarg only

- pulp_smash/tests/pulp2/python/api_v2/test_duplicate_uploads.py
As of Pulp 2.11, the Python plugin requires a filename when uploading an
egg. Update the Python upload test accordingly.
See: https://pulp.plan.io/issues/2334
> Pass filename when uploading eggs on Python 2.11+

- pulp_smash/pulp2/utils.py
- tests/test_pulp_smash_cli.py
It encourages fragile clean-up logic and slows down tests by
unnecessarily deleting orphans.
> Deprecate BaseAPITestCase

- pulp_smash/pulp_smash_cli.py
- tests/test_pulp_smash_cli.py
Deprecate `pulp-smash settings path` in favor of `pulp-smash settings
load-path`, and add `pulp-smash settings save-path`. This change has two
benefits:
* Users are made conscious of the fact that the path used when loading
settings may be different then the path used when saving settings.
Being aware of this distinction may help to prevent bugs.
* Users who wish to create a settings file in a non-interactive manner
(as opposed to with `pulp-smash settings create`) can now do so more
easily.
Without this commit, a user who wants to create a settings file must
both hard-code knowledge about the path at which a settings file should
be created, and must make sure to create parent directories. The
procedure looks like this:
mkdir -p ~/.config/pulp_smash
cat >~/.config/pulp_smash/settings.json …
> Update `pulp-smash settings` subcommands

- pulp_smash/api.py
An `api.Client` object should only be used to communicate with one host.
Its value proposition is that it trades off some flexibility for
convenience: when repeatedly communicating with a single host, certain
options and behaviours can be repeatedly sent with little effort.
If an `api.Client` object is used to communicate with some other host, a
warning is raised. Unfortunately, the logic used to generate this
warning is baroque. It goes like this:
1. Take `self.pulp_host`, a `PulpHost` object, and build a base URL by
passing it to a URL building method on `self._cfg`, a
`PulpSmashConfig` object.
2. Parse this URL, and extract the hostname.
3. Compare the extracted hostname to the hostname of the host a request
is being made to.
This logic is correct, but it's unnecessarily convoluted. …
> Simplify api.Client hostname warning

- pulp_smash/pulp_smash_cli.py
Fix typo on `settings_save_path` funciton.
> Fix typo on save-path function.

- pulp_smash/api.py
Use straightforward if/else logic to handle all "default to none"
api.Client constructor parameters.
> Make api.Client constructor more straightforward

- pulp_smash/api.py
- tests/test_api.py
Currently, API response handlers accept two arguments: a
`PulpSmashConfig` object and a `requests.Response` object. Here's a
typical method signature:
pulp_smash.api.json_handler(cfg, response)
This mostly works fine. But it does mean that the response handlers lose
some context about the state of the calling `pulp_smash.api.Client`
objects. For example, response handlers don't know if the calling API
client has been instructed to poll a specific
`pulp_smash.config.PulpHost`, as defined by the parent's `pulp_host`
attribute.
Re-write the API response handlers, so that the API client object which
is calling them is now passed to them. As an example of how this is
useful, the `_handle_202` function now knows which Pulp host it should
communicate with when polling asynchronous tasks.
This …
> Rewrite response handlers

- pulp_smash/tests/pulp3/file/api_v3/test_crud_remotes.py
Attempt to create a remote using the same `name` as a previous created
remote, and assert that an HTTP exception is raised.
Related to #1055
> Assert that remote has unique `name` attribute.

- pulp_smash/tests/pulp3/file/api_v3/test_crud_publishers.py
Attempt to create a publisher using the same name as a previous created
publisher, and assert that an HTTP exception is raised.
Closes:#1055
> Assert that publisher has unique `name` attribute.

- pulp_smash/pulp3/utils.py
Let the function return all repository versions, even if there is more
than can fit in one page of results.
See: https://github.com/PulpQE/pulp-smash/issues/918
> Let get_versions() handle pagination

- pulp_smash/pulp3/utils.py
- pulp_smash/tests/pulp3/file/api_v3/test_crud_content_unit.py
- pulp_smash/tests/pulp3/file/api_v3/test_orphans.py
- pulp_smash/tests/pulp3/file/api_v3/test_repo_version.py
- pulp_smash/tests/pulp3/file/api_v3/test_sync.py
- pulp_smash/tests/pulp3/file/api_v3/test_unlinking_repo.py
- pulp_smash/tests/pulp3/file/api_v3/utils.py
Let the function return all content, even if there is more than can fit
in one page of results.
See: https://github.com/PulpQE/pulp-smash/issues/918
> Let get_content() handle pagination

- pulp_smash/pulp3/utils.py
- pulp_smash/tests/pulp3/file/api_v3/test_auto_distribution.py
- pulp_smash/tests/pulp3/file/api_v3/test_repo_version.py
Let the function return all added content, even if there is more than
can fit in one page of results.
See: https://github.com/PulpQE/pulp-smash/issues/918
> Let get_added_content() handle pagination

- pulp_smash/pulp3/utils.py
- pulp_smash/tests/pulp3/file/api_v3/test_repo_version.py
Let the function return all content, even if there is more than can fit
in one page of results.
See: https://github.com/PulpQE/pulp-smash/issues/918
> Let get_removed_content() handle pagination

- pulp_smash/tests/pulp3/file/api_v3/test_crd_publications.py
Let these tests correctly handle the case where there are so many search
results for a given query that they don't all fit into a single page.
> Let Pulp 3 test_crd_publications use page_handler

- pulp_smash/cli.py
Add a try/finally around the `yield` of `_disable_selinux` method, since
we never know what exceptions can happen inside the `with` block.
See also: https://www.python.org/dev/peps/pep-0343/#generator-decorator
> Add try/finally to contextmanager.

- docs/Makefile
On the author's development machines, compiling documentation is a
CPU-bound task. In addition, all modern CPUs support parallelism. Thus,
letting Sphinx compile documentation using multiple workers has an
immediate and beneficial impact on documentation build times.
> Let sphinx build docs in parallel

- pulp_smash/selectors.py
- pulp_smash/tests/pulp2/platform/api_v2/test_repository.py
The `@require` decorator is designed to skip tests under certain
circumstances. This is easiest to do if some assumptions are made about
which test runner is being used. For example, if one assumes that a
unittest-compatible test runner is likely to be used, then it makes
sense for the function to raise `unittest.SkipTest`.
However, Pulp Smash is being turned into a library that should be
compatible with other test runners. An effective way to help prevent
bias toward unittest is to avoid any references to unittest within the
code base. Add an `exc` parameter to the function, which is the
exception to be instantiated and raised.
> Drop unittest from @require

- pulp_smash/pulp2/utils.py
- pulp_smash/tests/pulp2/docker/utils.py
- pulp_smash/tests/pulp2/ostree/utils.py
- pulp_smash/tests/pulp2/platform/utils.py
- pulp_smash/tests/pulp2/puppet/utils.py
- pulp_smash/tests/pulp2/python/utils.py
- pulp_smash/tests/pulp2/rpm/utils.py
The various `require_*` methods in `pulp_smash.pulp2.utils` are designed
to skip tests under certain circumstances. This is easiest to do if some
assumptions are made about which test runner is being used. For example,
if one assumes that a unittest-compatible test runner is likely to be
used, then it makes sense for the functions to raise
`unittest.SkipTest`.
However, Pulp Smash is being turned into a library that should be
compatible with other test runners. An effective way to help prevent
bias toward unittest is to avoid any references to unittest within the
code base. Add an `exc` parameter to the functions, which is the
exception to be instantiated and raised.
> Drop unittest from Pulp 2 require_* utils

- pulp_smash/pulp3/utils.py
- pulp_smash/tests/pulp3/file/utils.py
- pulp_smash/tests/pulp3/pulpcore/utils.py
The `@require_pulp_plugins` decorator is designed to skip tests under
certain circumstances. This is easiest to do if some assumptions are
made about which test runner is being used. For example, if one assumes
that a unittest-compatible test runner is likely to be used, then it
makes sense for the function to raise `unittest.SkipTest`.
However, Pulp Smash is being turned into a library that should be
compatible with other test runners. An effective way to help prevent
bias toward unittest is to avoid any references to unittest within the
code base. Add an `exc` parameter to the function, which is the
exception to be instantiated and raised.
> Drop unittest from @require_pulp_plugins

- pulp_smash/pulp3/utils.py
- pulp_smash/tests/pulp3/file/utils.py
- pulp_smash/tests/pulp3/pulpcore/utils.py
The `@require_pulp_3` decorator is designed to skip tests under certain
circumstances. This is easiest to do if some assumptions are made about
which test runner is being used. For example, if one assumes that a
unittest-compatible test runner is likely to be used, then it makes
sense for the function to raise `unittest.SkipTest`.
However, Pulp Smash is being turned into a library that should be
compatible with other test runners. An effective way to help prevent
bias toward unittest is to avoid any references to unittest within the
code base. Add an `exc` parameter to the function, which is the
exception to be instantiated and raised.
> Drop unittest from @require_pulp_3

- pulp_smash/pulp2/utils.py
Make the warning message point out that this class is coupled to
unittest.
> Update BaseAPITestCase deprecation warning

- pulp_smash/pulp2/utils.py
Make the warning message point out that this class is coupled to
unittest.
> Add deprecation warning to BaseAPICrudTestCase

- pulp_smash/tests/pulp2/docker/api_v2/test_sync.py
Rewrite `pulp_smash.tests.pulp2.docker.api_v2.test_sync`:
* Drop `BaseAPITestCase` from the module.
* Assert that `last_override_config` is an empty dict.
* Restructure the tests to be more independent.
See: https://github.com/PulpQE/pulp-smash/issues/763
Fix: https://github.com/PulpQE/pulp-smash/issues/1066
> Test last_override_config, drop a BaseAPITestCase

- pulp_smash/tests/pulp2/rpm/api_v2/test_upload_publish.py
`UploadInvalidRPMTestCase` verifies that a certain string is in a prose
error message. That prose error message has changed in the current
development branch of Pulp. Make the test case slightly more lax, so
that it passes on either version of Pulp, all without reducing the
integrity of the test case by an appreciable amount.
> Make assertion on prose more lax

- pulp_smash/tests/pulp2/rpm/api_v2/test_republish.py
* The various unittest `assert*` methods typically offer a parameter
that is only evaluated and printed if the test fails. The
aforementioned test case has several assertions like this:
self.assertEqual(len(foo[0]), len(foo[1]), foo[0])
In case of failure, this isn't terribly useful. Make the failure
message more verbose, like so:
self.assertEqual(len(foo[0]), len(foo[1]), foo)
* Reformat several lines of text for both legibility and compactness.
> Refactor RemoveOldRepodataTestCase

- pulp_smash/pulp2/utils.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_updateinfo.py
- tests/test_pulp2_utils.py
Update the `upload_import_erratum` function so that it accepts an entire
dict of information about a repository, instead of just a repository
href. This has two benefits:
* Variable passing is easier. Rather than worrying about which bits of
information are required where, one can typically just pass the
information returned by Pulp itself.
* The function is now more like other, similar functions, which makes
usage more intuitive.
> Change signature of upload_import_erratum()

- pulp_smash/tests/pulp2/rpm/api_v2/test_content_applicability.py
When Pulp returns a content applicability report for a consumer, it
should list not only the RPMs that are applicable, but also the erratum.
Pulp 2.16.2 included a regression wherein this information would not be
returned if the underlying `updateinfo.xml` file lacked certain
information. Pulp 2.16.3 fixes this issue.
Expand Pulp Smash's verification logic so that it checks for the
presence of erratum in content applicability reports.
See: https://pulp.plan.io/issues/3795
> Verify erratum are listed in applicability reports

- docs/api.rst
- docs/api/pulp_smash.tests.pulp3.file.api_v3.test_auto_distribution.rst
- docs/api/pulp_smash.tests.pulp3.file.api_v3.test_orphans.rst
- docs/api/pulp_smash.tests.pulp3.file.api_v3.test_pagination.rst
- docs/api/pulp_smash.tests.pulp3.file.api_v3.test_repo_version.rst
- docs/api/pulp_smash.tests.pulp3.file.api_v3.test_unlinking_repo.rst
- docs/api/pulp_smash.tests.pulp3.pulpcore.api_v3.plugin_involved.rst
- docs/api/pulp_smash.tests.pulp3.pulpcore.api_v3.plugin_involved.test_auto_distribution.rst
- docs/api/pulp_smash.tests.pulp3.pulpcore.api_v3.plugin_involved.test_orphans.rst
- docs/api/pulp_smash.tests.pulp3.pulpcore.api_v3.plugin_involved.test_pagination.rst
- docs/api/pulp_smash.tests.pulp3.pulpcore.api_v3.plugin_involved.test_repo_version.rst
- docs/api/pulp_smash.tests.pulp3.pulpcore.api_v3.plugin_involved.test_unlinking_repo.rst
- pulp_smash/tests/pulp3/pulpcore/api_v3/plugin_involved/__init__.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/plugin_involved/test_auto_distribution.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/plugin_involved/test_orphans.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/plugin_involved/test_pagination.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/plugin_involved/test_repo_version.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/plugin_involved/test_unlinking_repo.py
Some tests for the file plugin are really only testing pulpcore
functionality, however, they require a plugin in order to
exercise said functionality. re: discussion with Jeremy, it
makes sense to move these tests underneath pulpcore, but skip
them if the file plugin is not installed.
> Move certain "file" tests underneath the "pulpcore" dir

- pulp_smash/tests/pulp2/rpm/api_v2/test_repoview.py
- pulp_smash/utils.py
Since repoview logic doesn't work in FIPS enabled machine (Issue 3775)
skip logic for repoview checks are implemented for this commit
refer (https://pulp.plan.io/issues/3775)
> Adding logic to skip repoview checks for FIPS enabled machine

- pulp_smash/pulp2/utils.py
- pulp_smash/tests/pulp2/docker/api_v2/test_sync_publish.py
- pulp_smash/tests/pulp2/docker/api_v2/test_upload.py
- pulp_smash/tests/pulp2/docker/utils.py
- pulp_smash/tests/pulp2/puppet/api_v2/test_install_distributor.py
- pulp_smash/tests/pulp2/puppet/utils.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_download_policies.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_iso_sync_publish.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_package_paths.py
- pulp_smash/tests/pulp2/rpm/api_v2/test_rsync_distributor.py
- pulp_smash/tests/pulp2/rpm/utils.py
- pulp_smash/utils.py
- tests/test_config.py
- tests/test_utils.py
The `pulp_smash.utils.os_is_f2{6,7}` functions are not suitable for
inclusion within a top-level toolkit. There's an enormous number of
combinations of system facts that one might want to discover, and having
`os_is_*` functions is a recipe for an explosion in number of functions.
A framework should provide more generalized tools that individual users
can adapt to their needs.
Replace these functions with functions that report information from
`/etc/os-release`. This is more suitable for use within a toolkit: there
is a much more constrained set of values that one may wish to get from
`/etc/os-release`.
These functions are still somewhat susceptible to a surface-area
explosion. If users wish to get more and more information from
`/etc/os-release`, then it would be best to create a …
> Replace os_is_* functions

- pulp_smash/tests/pulp3/pulpcore/api_v3/plugin_involved/test_repo_version.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/test_tasks.py
With the release of django-filter 2.0, there's stricter filter validation which will raise 400 errors for bad dates and integers. Updating pulp-smash tests accordingly.
> Update pulp-smash tests for better filter validation

- docs/api.rst
- docs/api/pulp_smash.tests.pulp3.pulpcore.api_v3.plugin_involved.utils.rst
- pulp_smash/tests/pulp3/pulpcore/api_v3/plugin_involved/test_auto_distribution.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/plugin_involved/test_pagination.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/plugin_involved/test_repo_version.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/plugin_involved/test_unlinking_repo.py
- pulp_smash/tests/pulp3/pulpcore/api_v3/plugin_involved/utils.py
`pulp_smash.tests.pulp3.pulpcore` should not import from
`pulp_smash.tests.pulp3.file`. This is because these two different
packages will soon be moved into separate repositories that don't have
access to each others' namespaces.
Fix: https://github.com/PulpQE/pulp-smash/issues/1104
> Fix cross-plugin imports

- docs/usage.rst
- pulp_smash/cli.py
- pulp_smash/config.py
- pulp_smash/exceptions.py
- pulp_smash/pulp_smash_cli.py
- tests/test_cli.py
- tests/test_config.py
- tests/test_pulp_smash_cli.py
When applied, this commit will redefine what a "valid" configuration
file is. Existing configuration files will continue to be valid. But in
addition, entirely new (and similar-looking) configuration files may
also be written.
The old configuration files are suitable for use when testing Pulp 2.
They let one declare information like "host pulp.example.com is running
rabbitmq." The new configuration files are suitable for testing Pulp 3.
They lew one declare information like "host pulp.example.com is running
redis."
In addition, this commit will update two pieces of machinery that are
related to the configuration file. Specifically, this commit will
overhaul the entire CLI interface (as accessed by the `pulp-smash`
executable) and re-implement the `PulpSmashConfig.get_services` method. …
> Make settings machinery support Pulp 3

- Makefile
- docs/conf.py
- scripts/release.sh
Make the `dist` make target test the egg and wheel that it builds.
Don't require that the current VERSION file look like a date, e.g.
`2018.07.19`.
Overhaul `scripts/release.sh`:
* Give it proper argument parsing capabilities, and add several
arguments.
* Make it generate annotated tags, not lightweight tags. This greatly
improves traceability.
See: https://github.com/PulpQE/pulp-smash/issues/1050
> Upgrade release machinery

- tests/test_selectors.py
Adding Unit tests for checking the Skip If selectors in pulp-smash. This is done as a part of increasing code coverage in pulp-smash test suite.
refer  #1035
> Adding Unit Tests for testing Skip If selectors

- .travis.yml
Indent by two spaces, and only indent where syntactically required.
> Normalize indentation in .travis.yml

- pulp_smash/selectors.py
pulp.plan.io issues may now have a status of "CLOSED - COMPLETE." Update
`pulp_smash.selectors` to deal with this new state of affairs.
> Deal with new pulp.plan.io issue status

- pulp_smash/pulp3/utils.py
- tests/test_pulp3_utils.py
Since Remote has one, it makes sense for Publisher to have one,
especially since Publisher is less likely to need custom behavior.
> Add a function for generating a publisher dict

- pulp_smash/pulp3/utils.py
Pulp has a "content_summary" field on repository versions which provides an easy way to see how many of each content type are in the repository.  It looks like (e.g.) {'file': 5, 'rpm': 10, 'errata': 2}. This utility function provides an easy way to get these counts without manually taking a len() of the list content, and is also necessary for plugins which have multiple content types, such as the RPM plugin with both RPMs and Errata.  It avoids the issue of all different types of content being mixed together when taking counts.
> Add a utility function for getting the "content_summary" from Pulp

- pulp_smash/cli.py
- tests/test_cli.py
Fix #1037 
As part of our `less boilerplate` effort I added a new method `sudo` argument
to `cli.Client.run`.
In a lot of test cases there are code like:
```python
sudo = () if cli.is_root(cfg) else ('sudo',)
...
client.run(sudo + ('command_name', 'argument1', ...))
```
The idea is to replace the above boilerplate with
```python
client.run(('command_name', 'argument1', ...), sudo=True)
```
With this change we will be able to remove the `sudo = () if cli.is_root(cfg) else ('sudo',)` boilerplate in 28 Pulp-2-tests references:
```bash
pulp_2_tests/tests/docker/utils.py:    sudo = '' if cli.is_root(cfg) else 'sudo'
pulp_2_tests/tests/puppet/api_v2/test_install_distributor.py:        sudo = () if cli.is_root(self.cfg) else ('sudo',)
pulp_2_tests/tests/rpm/api_v2/test_content_sources.py: …
```
> Added a `sudo` argument to `cli.Client.run` to avoid boilerplate.

- pulp_smash/pulp3/utils.py
- tests/test_pulp3_utils.py
As (some) plugins support "mirror" parameters now, allow to call sync() with
customized parameters.
> Make Pulp 3 sync() function accept `**kwargs`

- Makefile
Add another section to Make file to install Pulp smash in dev mode.
`make install-dev` command will be available. A good use of this command will
be:
```python
python3 -m venv ~/env
source ~/env/bin/activate
make install-dev
```
> Add install-dev to Make file

- pulp_smash/pulp3/constants.py
Add a new constant to pulp 3 namespace. `CONTENT_GUARDS_PATH`.
See:https://pulp.plan.io/issues/3968
> Add a new constant to pulp 3

- Makefile
Add W504, ``W504 line break after binary operator``, for errors to be
ignored.
Failed Job can be seen [here](https://travis-ci.org/PulpQE/pulp-smash/jobs/443414844)
New flake8 version added new rule.
See:http://flake8.pycqa.org/en/latest/release-notes/3.6.0.html
> Update Makefile to ignore new flake8 rules

- docs/about.rst
From now on `pulp.plan.io` will be used to track issues for Pulp 2 and Pulp 3.
Update docs to reflect this.
> Update docs to reflect tool to track issues

- pulp_smash/cli.py
- tests/test_cli.py
Related to pulp/pulp_file#129
```python
pm = PackageManager(cfg)
pm.raise_if_unsupported(unittest.SkipTest, 'Test requires yum/dnf')
pm.install('foobar')
```
or
```python
pm = PackageManager(cfg, raise_if_unsupported=(unittest.SkipTest, 'Test requires yum'))
pm.install('foobar')
```
The main idea is to replace this:
```py
try:
PackageManager(cgf).name
except exceptions.NoKnownPackagemanager:
raise unittest.SkipTest("This test requires dnf/yum")
```
> Added `raise_if_unsupported` on Packagemanager

- Makefile
- tests/test_cli.py
- tests/test_config.py
pylint newest version 2.2.0  doesn't allow `simplifiable-if-expression`. This
commit adds an ignore statement in the MakeFile.
See: https://pypi.org/project/pylint/2.2.0/
> Fix pylint 2.2.0 errors

- pulp_smash/pulp3/utils.py
The schema looks like this:
```
"_content": {
"file": "/pulp/api/v3/content/file/files/?repository_version=..."
},
"_content_added": {
"file": "/pulp/api/v3/content/file/files/?repository_version_added=..."
},
"_content_removed": {}
```
Change the get_*content() functions to return a dictionary of types
matched to the respective list of content of that type.
Fix the get_artifact_paths() function to use those new functions
properly.
> API Changes

- pulp_smash/pulp3/utils.py
It doesn't make as much sense as it does for the other get_content
functions.
> Don't use defaultdict for summaries

- pulp_smash/pulp3/utils.py
This name of field is changing inside core and in
plugins to show it is 'core' field of pulp.
https://pulp.plan.io/issues/4282
Signed-off-by: Pavel Picka <ppicka@redhat.com>
> Rename 'artifact' to '_artifact'

- scripts/release.sh
Modify `release.sh` script in order to add metadata to annoted tags.
Closes: #1167
> Add metadata to created tags

- pulp_smash/config.py
- pulp_smash/pulp_smash_cli.py
- tests/test_cli.py
- tests/test_config.py
- tests/test_pulp_smash_cli.py
Added `content` as a valid role for config hosts
Added helper methods in `cfg` to get content_host Base URL.
Added `content` as a new option on `pulp-smash settings create`
Note: In cases where `content` role is not defined then the `api`
host is assumed as the content host.
https://docs.pulpproject.org/en/3.0/nightly/components.html#content-serving-application
> Introduced the Pulp 3 'content' role.

- pulp_smash/pulp3/constants.py
Pulp 3 is removing the endpoints realated to user management. Remove
this constant.
See: https://pulp.plan.io/issues/4398
> Remove constant USER_PATH

- pulp_smash/pulp3/utils.py
Updates pulp-smash for repo layout changes
This is designed to go along with these changes in Pulp 3.0
~https://github.com/pulp/pulp/pull/3896~
https://github.com/pulp/pulpcore/pull/2
The response format changed you we have to adjust how the utils parse
the response data for tests.
https://pulp.plan.io/issues/4283
re #4283
> Updates pulp-smash for repo layout changes

- pulp_smash/pulp3/constants.py
Add a constant `LAZY_DOWNLOAD_POLICIES` to ease tests related to lazy
sync on Pulp 3.
> Add lazy download policies constant

- pulp_smash/cli.py
- pulp_smash/exceptions.py
Adds a new class to the cli to deal with registry clients
currently supporting `podman` and `docker`.
```py
>>> from pulp_smash import cli, config
>>> registry = cli.RegistryClient(config.get_config())
>>> registry.pull('image_name')
>>> image_data = registry.inspect('image_name')
>>> print(image_data)  # see details below
```
<details>
<summary>Click to see image_data results</summary>
```json
[
{
"Id": "d8233ab899d419c58cf3634c0df54ff5d8acc28f8173f09c21df4a07229e1205",
"Digest": "sha256:4415a904b1aca178c2450fd54928ab362825e863c0ad5452fd020e92f7a6a47e",
"RepoTags": [
"fedora-29-pulp-3:8080/foo:latest",
"docker.io/library/busybox:latest"
],
"RepoDigests": [
"fedora-29-pulp-3@sha256:4415a904b1aca178c2450fd54928ab362825e863c0ad5452fd020e92f7a6a47e", …
```
> Adds `RegistryClient` to talk with container registries.

- pulp_smash/pulp3/utils.py
It needs to be able to handle content types with no artifact associated.
> Update get_artifact_paths() to be more correct

- pulp_smash/pulp3/utils.py
When using a `certguard` it is needed to pass aditional headers
containing certificate to allow the download of the content.
> add kwargs to download_content_unit function

- pulp_smash/utils.py
Unittest will not execute tearDownClass if an error occurs on classmethods
this contextmanager will ensure that method is executed in case of error.
Usage:
```py
@classmethod
def setUpClass(cls):
with ensure_teardownclass(cls):
1 / 0  # raises ZeroDivisionError
```
without `ensure_teardownclass` after that exception, tearDownClass
would never be executed, but the context manager ensure it.
> Add `ensure_teardownclass` context manager to pulp_smash.utils

- pulp_smash/api.py
Usage examples:
Create a distribution using `json_handler`
```py
client = Client(cfg, api.json_handler)
spawned_task = client.post(DISTRIBUTION_PATH, body)
>>> {'task': ...}
task_resources = client.get(spawned_task['_href'])
distribution_href = task_resources['created_resources'][0]
distribution = client.get(distribution_href)
>>>  {'_href': ..., 'base_path': ...}
```
Create a distribution using `task_handler`
```py
client = Client(cfg, api.task_handler)
distribution = client.post(DISTRIBUTION_PATH, body)
>>> {'_href': ..., 'base_path': ...}
```
Having an existent client it is possible to use the shortcut::
```py
client.using_handler(api.task_handler).post(DISTRIBUTION_PATH, body)
```
to save few lines of code and some aditional imports when having to use a different handler o a client. …
> Add api.task_handler and related Client.using_handler

- docs/about.rst
- pulp_smash/pulp_smash_cli.py
```bash
$ pulp-smash shell --help      
Usage: pulp-smash shell [OPTIONS]
Run a Python shell with Pulp-Smash context.
Start an interactive shell with pulp-smash objects available, if `ipython`
is installed it will start ipython session, else it will start standard
python shell.
Options:
--ipython / --no-ipython
--help                    Show this message and exit.
```
```bash
$ pulp-smash shell       
Welcome to Pulp-Smash interactive shell
Auto imported: api, cli, config, utils, pulp2, pulp3, constants, exceptions
Available objects: api.client, cli.client, cfg
In [1]: api.client.get('/pulp/api/v2/status/').json()
Out[1]: 
{'known_workers': [{'_ns': 'workers',
'last_heartbeat': '2019-03-20T18:44:57Z',
'_id': 'scheduler@rhel-76-pulp-2'},
{'_ns': 'workers',
'last_heartbeat': …
```
> Add 'pulp-smash shell' command.

- .pre-commit-config.yaml
- .travis.yml
- Makefile
- README.rst
- docs/about.rst
- docs/conf.py
- pulp_smash/api.py
- pulp_smash/cli.py
- pulp_smash/config.py
- pulp_smash/constants.py
- pulp_smash/exceptions.py
- pulp_smash/pulp2/constants.py
- pulp_smash/pulp2/utils.py
- pulp_smash/pulp3/constants.py
- pulp_smash/pulp3/utils.py
- pulp_smash/pulp_smash_cli.py
- pulp_smash/selectors.py
- pulp_smash/utils.py
- setup.py
- tests/test_api.py
- tests/test_cli.py
- tests/test_config.py
- tests/test_pulp2_utils.py
- tests/test_pulp3_utils.py
- tests/test_pulp_smash_cli.py
- tests/test_selectors.py
- tests/test_utils.py
This PR does:
* Drop Python 3.4 support.
* Drop linters from setup.py
* Adopt black code sytle.
* Fix flake8 issues.
* Remove pylint as linter.
* Update MakeFile.
* Update Docs.
> Overhaul CI and apply code format

- pulp_smash/cli.py
- tests/test_cli.py
Everytime we instantiate a new instance of `cli.Client` its `__init__` method
code tries to make communication with the remote host to determine if it is
a local or ssh machine to be used.
The communication with `machine` should be done only when it is necessary,
which is when the `run` command is called.
```json
{
"hosts": [
{
"hostname": "this-host-does-not-exists-or-server-is-down",
...
}
]
}
```
```bash
$ export PULP_SMASH_CONFIG_FILE=/path/to/above/settings.json
$ python -c "from pulp_smash import cli, config; c = cli.Client(config.get_config()); print(c)"
Traceback (most recent call last):
plumbum.machines.session.SSHCommsError: No communication channel detected. Does the remote exist?
```
**We have not called the **run** method, so the communication with server should not be done …
> Lazy load the cli.Client machine

- pulp_smash/pulp3/constants.py
There is an existing constant called CONTENT_GUARD_PATH which includes
plugin-specific portions to its URL. This changes the name to indicate
it's only a BASE path and includes only the URL portions that are
specified by core.
The corresponding viewset comes from here: https://github.com/pulp/pulpcore/blob/7fdc5626559051e540509f7b699c28684e1043a9/pulpcore/app/viewsets/publication.py#L49
> Introduce BASE_CONTENT_GUARD_PATH

- pulp_smash/selectors.py
- tests/test_selectors.py
Many Pulp 2 issues were closed as WONTFIX. Based on the previous setup
of bug_is_fixed a few tests started to run and failed. Update the
bug_is_fixed function to keep skipping those tests, and
adding a warning message. Main goal is to be able to keep those tests in
the cose basis for future reference. Now the bug_is_fixed function will
behave a bit different based on Pulp version under test. For Pulp 3 the
old behave was kept.
> Modify bug_is_fixed to reflect Pulp 2 issues status

- pulp_smash/pulp3/utils.py
Pulp 3 API endpoint to delete orphans returns a 202 and a task object.
Adjust the reponse_handler used by the delete_orphans function.
See: https://pulp.plan.io/issues/4555
> Modify response_handler for delete_orphans

- pulp_smash/selectors.py
Verify what type of parameter is provided to the function `bug_is_fixed`
to assure that `pulp_version` is a valid choice.
> Verify type of paramater pulp_version in bug_is_fixed

- pulp_smash/api.py
- tests/test_api.py
This handler can decide which handler to use based
on content response.
> Add smart_handler as the default for api.Client

- docs/api/pulp_smash.log.rst
- docs/configuration.rst
- pulp_smash/api.py
- pulp_smash/cli.py
- pulp_smash/log.py
- pulp_smash/pulp3/utils.py
- pulp_smash/utils.py
Adding some DEBUG loggings on api and cli Clients.
By default the logger will output on `ERROR` level, (only ERROR and CRITICAL messages)
To enagle debug logging the log level needs to be changed.
`export PULP_SMASH_LOG_LEVEL=DEBUG`
That variable holds the string name of `logging` levels `NOTSET,INFO,DEBUG,ERROR,CRITICAL,WARNING`
Examples and outputs:
<details>
<summary>Pulp Smash Shell</summary>
```logtalk
PULP_SMASH_LOG_LEVEL=DEBUG pulp-smash shell
In [1]: response = api.Client(cfg).get('/pulp/api/v3/status/', headers={'foo': 'bar'})
2019-04-23:17:59:47,147 DEBUG    [api.py:530 - __init__] New <api.Client({'response_handler': <function smart_handler at 0x7fd712b3dc80>, 'host': PulpHost(hostname='fedora-29-pulp-3', roles={'api': {'port': 80, 'scheme': 'http', 'service': 'nginx', …
```
> Add pulp_smash.log.logger and some logger.debug calls

- pulp_smash/pulp_smash_cli.py
Readline provides autocomplete for std python shell
(when ipython is not used)
But in Python3.7 under a virtualenv gnu-readline may not be installed
so to avoid exception we need to suppress its import error.
The recommendation is to always use ipython :)
> Fix pulp-smash shell on Python3.7

- pulp_smash/api.py
- pulp_smash/config.py
- pulp_smash/pulp_smash_cli.py
- tests/test_api.py
- tests/test_cli.py
- tests/test_config.py
- tests/test_pulp2_utils.py
- tests/test_pulp_smash_cli.py
Add optional timeout variable as part of settings.json. This will allow one to
specify the timeout for the task system in seconds from now, if not
defined it will be set to default value of 1800s. This was the previous
used value.
Tweak the task system timeout to use seconds, and query Pulp more often.
Reduce the sleep time on `poll_task` function to 0.3s.
Adjust unittests, and remove old tests.
closes:#1173
> Add optional timeout to settings.json 

- pulp_smash/pulp3/utils.py
Sync was returning a task. Update the reponse_handler to parse the
retuned task. This will make the sync a bit more robust.
> Update sync for Pulp 3 to use smart_handler

- pulp_smash/api.py
Temporarily update task polling system to address Pulp 2 issue.
Pulp-smash was polling at a 0.3s rate that is occasionally returning
a task "COMPLETE" but the values for the task had yet to be reset.
Adjust the task system to use the previous value of 2s for Pulp 2.
See: https://pulp.plan.io/issues/4795
> Temporarily update task polling system for Pulp 2

- pulp_smash/pulp3/utils.py
`get_served_content_url` will return the URL that content is served
given a distribution.
Adjust function `download_content_unit` to use the newly added function.
> Add util get_served_content_url for Pulp 3

- pulp_smash/pulp3/constants.py
With https://github.com/pulp/pulpcore/commit/59f3450286d0a3a88e4b9fd1edb3568ee65bf54f
the download policy by default only includes 'immediate'.
[noissue]
> Changing download_policies

- pulp_smash/cli.py
Add local flag to CLI client. This will force the client to run the
CLI commands in the same box that pulp-smash is installed. This will
remove the need to call subprocess to run commands locally.
Besides that, it will allow to reuse the tooling already in
place for the CLI client.
> Add local flag to CLI client

- pulp_smash/config.py
Remove names of services for the api role. This change was required due
to changes in test approach for Pulp 3.
See: https://pulp.plan.io/issues/4965
> Remove service names from api role

- pulp_smash/cli.py
Solution: add ability to specify 'kubectl' as shell transport
> Problem: can't run CLI related tests on kubernetes

- pulp_smash/api.py
some endpoints do not include `spawned_tasks` so treat it as optional when polling for tasks
> Task polling fix for pulp_ansible Galaxy V3 API tests

- docs/index.rst
- docs/release.rst
Add section about release process in the documentation.
> Add section about release process documentation

- pulp_smash/pulp3/utils.py
Pulp 3 is adjusting the use of relative URLs, adjust utils functions
accordingly.
https://pulp.plan.io/issues/5629
> Update Pulp 3 utils to use absolute URL

- pulp_smash/pulp3/utils.py
This stops the pulp-smash client to warn about the wrong hostname and
prevents sending the admin credentials to the content server.
[noissue]
> Use requests directly to download content

- pulp_smash/pulp3/utils.py
The `pulp_smash.pulp3.utils:download_content_unit` method now forms the
content url to fetch from using the pulp-smash config. Previously this
was formed from the distribution.base_url, but the issue is that
directly users back to nginx/apache which is not how pulp-smash is
intented to test Pulp.
Instead pulp-smash should fetch content directly from the content app
whose port, e.g. 24816, is in the pulp-smash config.
> `download_content_unit` now uses smash config

- pulp_smash/pulp3/bindings.py
This change attempts to use the new
`POST /pulp/api/v3/orphans/cleanup/` API. It's only available in 3.14+
so there is a fallback implementation to the old style call if the new
one isn't available.
[noissue]
> Ports orphan cleanup to new API call

- pulp_smash/config.py
- pulp_smash/pulp3/fixture_utils.py
- pulp_smash/pulp3/pytest_plugin/__init__.py
- setup.py
This provides a common place for any pytest fixtures to be added.
> Makes pulp_smash a pytest plugin

- pulp_smash/pulp3/pytest_plugin/__init__.py
pulp-smash doesn't use data typing so these 5 lines should be consistent
with the current use.
[noissue]
> Removed lingering typing

- setup.py
These are not used directly in pulp-smash, but pytest-xdist is going to
be used by everyone who uses pulp-smash soon, so let's make it available
everywhere by adding it here.
[noissue]
> Adds pytest and pytest-xdist as a dependency

- setup.py
In some situations pytest may run tests and collect non, e.g. when a
plugin has not added any `parallel` marks. This plugin allows the
`pytest-custom_exit_code` to be added when that's possible and not fail
the CI.
[noissue]
> Adds custom-exit-code pytest plugin

- pulp_smash/pulp3/constants.py
This discovers the API_ROOT for the server under test and then builds
URLs in pulp-smash built off of that instead of the hardcoded
`/pulp/api/v3/`.
[noissue]
> Adds rerooting auto-support

- setup.py
We should test this and use proxy.py==2.4.1 when it's released.
[noissue]
> Use a proxy.py pre-release with a bugfix we need
